### ISSUE TITLE
Unable to install Appium Python client.

### ISSUE THREAD

**Issue by karbon62** [appium/python-client#100]
Hi,

I've installed appium and would like to start using it with python scripts - although each time I try to install it via the steps given I am given this error:

"error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/test-easy-install-14834.pth'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /Library/Python/2.7/site-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable."

Thanks,
Karbon62

**Comment by imurchie** [comment]
This is a general Python problem. Can you install any packages from `pip`? I would suggest using a [virtual environment](http://docs.python-guide.org/en/latest/dev/virtualenvs/) in order to better control what is installed where.

**Comment by karbon62** [comment]
I am currently having problems with installing pip also. Would updating Python help?

Thanks for helping.

**Comment by LiuShengchieh** [comment]
You can try "pip install --user Appium-Python-Client".
