### ISSUE TITLE
bug: How to switch between different APKs for interaction testing on Android?

### ISSUE THREAD

**Issue by taop929** [appium/python-client#1016]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

execute_script This error indicates that the server does not support this method.

### Expected Behavior

You can switch between different apks in the Android version to achieve interactive testing

### Minimal Reproducible Example

import unittest
from appium import webdriver
from appium.options.android import UiAutomator2Options
from appium.webdriver.common.appiumby import AppiumBy
import time
import logging
from selenium.webdriver.support.ui import WebDriverWait
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException

logging.basicConfig(filename='appium_test_logs.log', level=logging.INFO,
                    format='%(asctime)s - %(levelname)s - %(message)s', )

appium_server_url = 'http://localhost:4723'

class TestAicMusic(unittest.TestCase):
    def setUp(self) -> None:
        self.driver = webdriver.Remote(appium_server_url, options=UiAutomator2Options().load_capabilities({
            'platformName': 'Android',
            'automationName': 'uiautomator2',
            'deviceName': 'Android',
            'appPackage': 'com.aic.music',
            'appActivity': 'com.aic.music.ui.component.main.MainActivity',
        }))

        logging.info("Test setup completed for com.aic.music")

    def tearDown(self) -> None:
        if self.driver:
            self.driver.quit()

        logging.info("Test teardown completed for com.aic.music")

    def test_find_battery_aic(self) -> None:
        logging.info("Starting test_find_battery for com.aic.music app")
        current_song_name_before = None
        for a in range(1):
            logging.info(f"Current value of a: {a}")
            
            self.driver.tap([(519, 566)], 100)
            logging.info("Clicked on the home button.")
            time.sleep(1)
            
            elements = self.driver.find_elements(by=AppiumBy.ID, value="im_back")
            if not elements:
                logging.info("Element with ID 'im_back' not found on the page. Click operation successful.")
            else:
                logging.info("Element with ID 'im_back' is found on the page. Click operation failed.")

                           
            self.driver.execute_script('mobile: shell', {
                'command': 'startActivity',
                'args': {
                    'appPackage': 'com.elink.carsettings',
                    'appActivity': 'com.elink.carsettings.SettingsActivity'
                }
            })

            try:
                self.driver.tap([(654, 569)], 100)
                logging.info("Clicked on the application list button.")

                wait = WebDriverWait(self.driver, 2)
                

### Environment

appium2.11.2
Python 3.8
UiAutomator2    3.7.2

**Comment by KazuCocoa** [comment]
i guess you would like to try out https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#mobile-startactivity

**Comment by taop929** [comment]
> 我想你想试试 https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#mobile-startactivity

Hello, startactivity are there any examples

**Comment by KazuCocoa** [comment]
https://github.com/appium/python-client/blob/87ec96177e9a4bcec67099fbd3acb6d3e0a838fb/test/functional/android/activities_tests.py#L24
Available arguments are listed in https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#mobile-startactivity

**Comment by taop929** [comment]
> https://github.com/appium/python-client/blob/87ec96177e9a4bcec67099fbd3acb6d3e0a838fb/test/functional/android/activities_tests.py#L24
> 
> 
> https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#mobile-startactivity 中列出了可用的参数

It's been resolved, thank you

**Comment by taop929** [comment]
> > https://github.com/appium/python-client/blob/87ec96177e9a4bcec67099fbd3acb6d3e0a838fb/test/functional/android/activities_tests.py#L24
> > 
> > https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#mobile-startactivity 中列出了可用的参数
> 
> It's been resolved, thank you

Hello, I can't find the element after switching to the page of another app, is there any way to find the element?

**Comment by taop929** [comment]
<img width="1198" alt="9a760ed46d3366358f06410011bf350" src="https://github.com/user-attachments/assets/93db140b-3715-465f-9e3b-5d0b9f0abc40">
After switching from the first app to the second app, I can't find the inner elements of the second app, is there any way to solve it?

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#elements-cannot-be-found might help.
The method to start an activity is not different from the main one, thus the result could depend on the query itself. What the result of `driver.page_source`?

**Comment by taop929** [comment]
> https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#elements-cannot-be-found 可能会有所帮助。启动 Activity 的方法与主要方法没有区别，因此结果可能取决于查询本身。结果是什么？`driver.page_source`
The way I currently switch between multiple applications is as follows:

**Comment by taop929** [comment]
> https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#elements-cannot-be-found 可能会有所帮助。启动 Activity 的方法与主要方法没有区别，因此结果可能取决于查询本身。结果是什么？`driver.page_source`
The way I currently switch between multiple applications is as follows:
appium_server_url = 'http://localhost:4723'

class TestAicMusic(unittest.TestCase):
    def setUp(self) -> None:
        self.driver = webdriver.Remote(appium_server_url, options=UiAutomator2Options().load_capabilities({
            'platformName': 'Android',
            'automationName': 'uiautomator2',
            'deviceName': 'Android',
            'appPackage': 'com.aic.music',
            'appActivity': 'com.aic.music.ui.component.main.MainActivity',
        }))
        logging.info("Test setup completed for com.aic.music")

    def test_music_app(self):
        
        
 

        
        self.driver.quit()

        
        self.driver = webdriver.Remote(appium_server_url, options=UiAutomator2Options().load_capabilities({
            'platformName': 'Android',
            'automationName': 'uiautomator2',
            'deviceName': 'Android',
            'appPackage': 'com.elink.carsettings',
            'appActivity': 'com.elink.carsettings.SettingsActivity',
        }))
        logging.info("Settings app started")

        
        

    def tearDown(self) -> None:
        self.driver.quit()
        logging.info("Test teardown completed")

if __name__ == '__main__':
    unittest.main()
Is there a way to switch between applications without having to restart them, and after switching, still be able to locate the elements?

**Comment by KazuCocoa** [comment]
Asking such a question in https://discuss.appium.io/ might help.
`driver.page_source` result shows some hints about available element trees on there. Try out configs in https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#elements-cannot-be-found would also help
