### ISSUE TITLE
Cannot install with Python v3.5 due to enum34

### ISSUE THREAD

**Issue by jessehudl** [appium/python-client#102]
Python 3.5 became the default version downloaded from python.org on 9/13 - https://www.python.org/downloads/

`Appium-Python-Client` currently requires package `enum34`: https://github.com/appium/python-client/blob/ae8bbd6b6dce43a318fdf3f2e2e86c52b70864d9/setup.py#L53

`enum34` doesn't seem compatible with Python 3.4+:
https://bitbucket.org/stoneleaf/enum34/issues/5/enum34-incompatible-with-python-35#comment-19462547
https://github.com/opentok/Opentok-Python-SDK/pull/70

This means `Appium-Python-Client` can't be installed:
```python
Collecting enum34 (from Appium-Python-Client==0.17->-r requirements.txt (line 4))
  Downloading enum34-1.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/private/var/folders/d6/t61563nd7xjg32ggy0qkqsbh0000gn/T/pip-build-in3maf22/enum34/enum/__init__.py", line 371, in __getattr__
        return cls._member_map_[name]
    KeyError: '_convert'
    
    During handling of the above exception, another exception occurred:
```

I'm not sure what the best solution is since the `enum34` issue was closed as `wontfix`. Perhaps only require if on Python < 3.4?

**Comment by drtwisted** [comment]
I have faced the same issue? Any updates on that?

**Comment by imurchie** [comment]
Cut a new version (0.18). It works for me now. Let me know if it doesn't for you in 3.5.

**Comment by toejough** [comment]
the pypi version has not been updated: https://pypi.python.org/pypi/Appium-Python-Client takes you to version 0.17

![screen shot 2015-10-09 at 10 06 14 am](https://cloud.githubusercontent.com/assets/5317312/10395917/7d424c5e-6e6d-11e5-8db1-5a2921277367.png)

**Comment by imurchie** [comment]
Ooops. Missed the upload.

That being said, it was an issue on the server-side, not the client (the standard Selenium client, which this extends, sends the `sessionId` in a way that the other clients don't, and it wasn't being handled).

**Comment by imurchie** [comment]
Updated.
