### ISSUE TITLE
Can't load the appium

### ISSUE THREAD

**Issue by Damji7** [appium/python-client#1035]
Hi there, 

i want to automate app in the bluestacks emulator, well, when i load it with the appium inspector it works normaly, but when i launch the script wich is this

import time
from appium import webdriver

from appium.options.android import UiAutomator2Options

options = UiAutomator2Options()
options.platformName = "Android"
options.deviceName = "emulator-5554"
options.appPackage = "com.vfs.italyglobal"
options.appActivity = "com.vfs.italyglobal.activities.SplashActivity"
options.noReset = True

driver = webdriver.Remote('http://localhost:4723/', options=options)

 it prints me this message " Error starting Appium session: Message: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource " am i wrong in something Appium v 2.11.5,

**Comment by KazuCocoa** [comment]
Could you share the Appium server log?

**Comment by KazuCocoa** [comment]
Please attach appium server log if still this is occurring
