### ISSUE TITLE
v0.19 breaks swiping Android

### ISSUE THREAD

**Issue by jwallis** [appium/python-client#107]
Isaac, I'm curious why the latest release is 0.14 but it's from march, while much newer code exists.  I'm sure you have a reason, just curious.  This last change a couple days ago I guess was picked up by Testdroid because my tests are running fine locally but failed on testdroid.com.  I can't really see behind their curtain because I'm just a contractor with my company.

Anywho, I guess it's not released code, but I believe the change from Oct 9th [840b93e] broke swiping.  controller.js is looking for "actions" in the json.

Tested with appium 1.4.3 and 1.4.10

old call succeeds
info: --> POST /wd/hub/session/0aa6d12d-3d06-4cc3-a916-83bd96582f82/touch/perform {"sessionId":"0aa6d12d-3d06-4cc3-a916-83bd96582f82","actions":[{"action":"press","options":{"y":672,"x":355}},{"action":"wait","options":{"ms":1500}},{"action":"moveTo","options":{"y":70,"x":355}},{"action":"release","options":{}}]}
info: [debug] Pushing command to appium work queue: ["swipe",{"startX":355,"startY":672,"endX":355,"endY":70,"steps":42}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"swipe","params":{"startX":355,"startY":672,"endX":355,"endY":70,"steps":42}}
...
info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"0aa6d12d-3d06-4cc3-a916-83bd96582f82"}
info: <-- POST /wd/hub/session/0aa6d12d-3d06-4cc3-a916-83bd96582f82/touch/perform 200 784.224 ms - 76 {"status":0,"value":true,"sessionId":"0aa6d12d-3d06-4cc3-a916-83bd96582f82"}

new call results in stack
info: --> POST /wd/hub/session/961923c0-fa5a-4fbf-883c-d7152c64b46a/touch/perform {"sessionId":"961923c0-fa5a-4fbf-883c-d7152c64b46a","gestures":[{"action":"press","options":{"y":672,"x":355}},{"action":"wait","options":{"ms":1500}},{"action":"moveTo","options":{"y":70,"x":355}},{"action":"release","options":{}}]}
info: <-- POST /wd/hub/session/961923c0-fa5a-4fbf-883c-d7152c64b46a/touch/perform 500 24.002 ms - 96 
TypeError: Cannot read property 'length' of undefined
    at exports.performTouch (/usr/local/lib/node_modules/appium/lib/server/controller.js:329:15)
    at Layer.handle [as handle_request](/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:110:13)...

controller.js code looks like:

```
exports.performTouch = function (req, res) {
  // touch actions do not work in webview
  if (req.device.isWebContext()) {
    return notYetImplemented(req, res);
  }

  // first, assume that we are getting and array of gestures
  var gestures = req.body;

  // some clients, like Python, send an object in which there is an `actions`
  // property that is the array of actions
  // get the gestures from there if we don't already have an array
  if (gestures && !Array.isArray(gestures)) {
    gestures = gestures.actions;
  }

  // press-wait-moveTo-release is `swipe`, so use native method
  if (gestures.length === 4 &&
      gestures[0].action === 'press' &&
      gestures[1].action === 'wait' &&
      gestures[2].action === 'moveTo' &&
      gestures[3].action === 'release') {
      return exports.mobileSwipe(req, res, gestures);
  }

  req.device.performTouch(gestures, getResponseHandler(req, res));
};
```

**Comment by imurchie** [comment]
Not sure why 0.14 is the last available to you. `pip install Appium-Python-Client -v` gives `0.20, 0.19, 0.18, 0.17, 0.16, 0.15, 0.14, 0.13, 0.12, 0.11, 0.10, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1`.

I've fixed the `actions` issue and published `0.20`.

**Comment by jwallis** [comment]
What I mean it's when you go to the releases tab https://github.com/appium/python-client/releases
There are only a handful and the latest is 0.14, so I thought the latest stuff was still beta

**Comment by jwallis** [comment]
ps thanks for the fix
