### ISSUE TITLE
 AttributeError: 'dict' object has no attribute 'to_capabilities'

### ISSUE THREAD

**Issue by gelodefaultbrain** [appium/python-client#1077]
## The problem

I simply just run the test code [here](https://appium.io/docs/en/2.0/quickstart/test-py/) and then I am getting this error

```
    self.driver = webdriver.Remote(appium_server_url,options=capabilities)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "***", line 227, in __init__
    super().__init__(
  File "***", line 218, in __init__
    capabilities = options.to_capabilities()
                   ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'to_capabilities'
```

## Environment
- Appium version (or git revision) that exhibits the issue: 4.4.0
- Last Appium version that did not exhibit the issue (if applicable): 4.4.0
- Desktop OS/version used to run Appium: WSL/Windows Subsystem for Linux
- Node.js version (unless using Appium.app|exe):
- Mobile platform/version under test:
- Real device or emulator/simulator:
- Appium CLI or Appium.app|exe:

## Details

Not much more detail. It's just that

## Link to Appium Logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.

## Code To reproduce issue
Just run the test code [here](https://appium.io/docs/en/2.0/quickstart/test-py/)

**Comment by gelodefaultbrain** [comment]
This error `AttributeError: 'dict' object has no attribute 'to_capabilities'` comes from [here ](https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/remote/webdriver.py)by the way. It comes from selenium -- my selenium is `selenium                 4.27.1`. Is it version incompatibility?

**Comment by KazuCocoa** [comment]
Please follow https://github.com/appium/python-client

hm, I think the document should be a simple reference to the client’s live document. I’ll update the Appium's documentation to refer to this repository's readme

**Comment by KazuCocoa** [comment]
The link you referred in the description was old documentation. Please take a look at https://appium.io/docs/en/latest/quickstart/test-py/ to check the latest documentation
