### ISSUE TITLE
Cannot use 'new UiSelector.resourceId()' method to find elements by ID

### ISSUE THREAD

**Issue by LohitRaj** [appium/python-client#114]
Trying to work with UIAutomator to find elements using the IDs of the elements. When tried to use the following approach popped with below error.

Client Used: Appium-Python-Client-2.0
To run the test used: py.test example.py
API Level of the Emulator: 18

_Code:_

```
   element = self.driver.find_element_by_android_uiautomator('new UiSelector.resourceId("com.gui.home.ui:id/username")')
   element.click()
```

_Error:_

```
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: find
info: [debug] [BOOTSTRAP] [debug] Finding new UiSelector.resourceId("com.gui.home.ui:id/username") using ANDROID_UIAUTOMATOR with the contextId:  multiple: false
info: [debug] [BOOTSTRAP] [debug] Parsing selector: new UiSelector.resourceId("com.gui.home.ui:id/username")
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"Could not parse UiSelector argument: UiSelector has no new UiSelector.resourceId method","status":9}
info: [debug] Condition unmet after 30352ms. Timing out.
info: [debug] Responding to client with error: {"status":9,"value":{"message":"The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource.","origValue":"Could not parse UiSelector argument: UiSelector has no new UiSelector.resourceId method"},"sessionId":"2364748e-5ffe-4db1-b91e-9e86f000c8a5"}
info: <-- POST /wd/hub/session/2364748e-5ffe-4db1-b91e-9e86f000c8a5/element 500 30353.480 ms - 323 
```

Is there any alternative to use UIAutomator to find elements by ID, or is there an issue with the above mentioned approach.

**Comment by softwarezhu** [comment]
I have the same issue, find elements by ID always fails.

**Comment by imurchie** [comment]
You need to instantiate the `UiSelector`.

```python
element = self.driver.find_element_by_android_uiautomator('new UiSelector().resourceId("com.gui.home.ui:id/username")')
element.click()
```

**Comment by ouguangqian** [comment]
i use the instance of the UiSelector , the same issue

**Comment by imurchie** [comment]
Can you provide logs @ouguangqian ? This issue is so old that things have most likely changed.

**Comment by ArchWalmart** [comment]
have the same issue, find elements by class always fails 
Appium verison -1.7.1
The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource.

**Comment by KazuCocoa** [comment]
What are your command and server logs?

`new UiSelector().resourceId(\"com.gui.home.ui:id/username\");` or `new UiSelector().resourceId("com.gui.home.ui:id/username");` probably can work with uiautomator2.

**Comment by khandelwalgarima** [comment]
I am facing the same issue
