### ISSUE TITLE
is there a way to parse log as a test condition 

### ISSUE THREAD

**Issue by xiaofengC** [appium/python-client#116]
in iOS, Can I capture my app custom log (inslog) and parse it for certain symbol as the result of a test. Since my company is developing an library with little ui, the only outputs are logs.

**Comment by imurchie** [comment]
I'm not sure. What happens if you write to the custom log and then use `driver.log_types`? Does the custom log type get into the result?

**Comment by xiaofengC** [comment]
no , it only returns syslog  , crashlog and performance.

**Comment by imurchie** [comment]
I don't think it will work, then. You can open an issue in the main Appium repository (https://github.com/appium/appium/issues) to try to get the feature added.
