### ISSUE TITLE
error: Could not set the device type in Info.plist

### ISSUE THREAD

**Issue by rsmamidi** [appium/python-client#117]
mac os : 10.10.5
xcode : 7.2
appium : 10.4.13

i am getting error when i am starting the IOS appium server, i had attached the xcode path and .app file path in the ios settings and launch the server . Log is pasted below

Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --command-timeout "7200" --session-override --pre-launch --debug-log-spacing --nodeconfig "/Users/me/nodeconfig.json" --robot-address "0.0.0.0" --robot-port "4" --platform-version "8.4" --platform-name "iOS" --app "com.intel.shgw" --show-ios-log --show-ios-log --device-name "iPhone 6 Plus" --native-instruments-lib

info: [debug] Starting Appium in pre-launch mode

info: Pre-launching app
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: ***\*        NEW SESSION           ***
info: ***\*        NEW SESSION           ***
info: ***\*        NEW SESSION           ***
info: ***\*        NEW SESSION           ***
info: ***\*        NEW SESSION           ***
info: ***\*        NEW SESSION           ***
info: ***\*        NEW SESSION           ***
info: ***\*        NEW SESSION           ***
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************

info: [debug] App is an iOS bundle, will attempt to run as pre-existing
info: [debug] Creating new appium session 46ce0f87-0385-44c2-a38d-a12b38aa1841
info: [debug] Removing any remaining instruments sockets

info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode version

info: [debug] Xcode version set to 7.2

info: [debug] Setting iOS SDK Version

info: [debug] iOS SDK Version set to 9.2
info: [debug] Checking whether instruments supports our device string
info: [debug] Getting list of devices instruments supports
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"7.2","iOSSDKVersion":"9.2","deviceName":"iPhone 6 Plus","platformVersion":"8.4"}

info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 Plus (8.4)'
info: [debug] iOS sim UDID is B42C4604-E96E-438E-B692-B6D974F811C4
info: [debug] Auto-detecting iOS udid...
info: [debug] Not auto-detecting udid, running on sim

info: [debug] Could not parse plist file (as binary) at /Applications/Appium.app/Contents/Resources/node_modules/appium/com.intel.shgw/en.lproj/Localizable.strings
info: Will try to parse the plist file as XML
info: [debug] Could not parse plist file (as XML) at /Applications/Appium.app/Contents/Resources/node_modules/appium/com.intel.shgw/en.lproj/Localizable.strings
warn: Could not parse app Localizable.strings assuming it doesn't exist
info: [debug] Creating instruments
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/octo/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"oneByOne"}
info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
info: [debug] Dynamic bootstrap path: /Users/octo/Library/Application Support/appium/bootstrap/bootstrap-f062718992d59810.js
info: [debug] Reusing dynamic bootstrap: /Users/octo/Library/Application Support/appium/bootstrap/bootstrap-f062718992d59810.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"7.2","iOSSDKVersion":"9.2","deviceName":"iPhone 6 Plus","platformVersion":"8.4"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 Plus (8.4)'
info: [debug] We're on iOS7.1+ so forcing defaultDevice on
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"7.2","iOSSDKVersion":"9.2","deviceName":"iPhone 6 Plus","platformVersion":"8.4"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 Plus (8.4)'
info: [debug] Could not parse plist file (as binary) at /Applications/Appium.app/Contents/Resources/node_modules/appium/com.intel.shgw/Info.plist
info: Will try to parse the plist file as XML
info: [debug] Could not parse plist file (as XML) at /Applications/Appium.app/Contents/Resources/node_modules/appium/com.intel.shgw/Info.plist
info: [debug] Cleaning up appium session

error: Could not set the device type in Info.plist

**Comment by imurchie** [comment]
Does `/Applications/Appium.app/Contents/Resources/node_modules/appium/com.intel.shgw/Info.plist` exist? Is the app already on the device?

**Comment by rushabh55** [comment]
I'm running into the same problem. I know that the simulator is running, app is installed inside the simulator and I know that all the paths exists including info.plist inside myApp.app, still running into this problem. 
My requested capabilities are :
   ```
 capabilities: [{
        browserName: '',
        'appiumVersion': '1.5.2',
        platformName: 'iOS',
        platformVersion: '9.3',
        deviceName: 'iPhone 6', 
        deviceOrientation: 'portrait',
        autoDismissAlerts: true,
        fullReset: false,
        app: path.join(process.env.myApp_iOS_Directory || '', '/Debug-iphonesimulator', '/myApp.app')
    }],
```

Any idea on how to fix this? 
Error I keep getting is 

`[iOS] Could not set the bundleId from app.
[MJSONWP] Encountered internal error running command: Error: Could not extract Info.plist from application: Plist file doesn't exist: '/Debug-iphonesimulator/myApp.app/Info.plist'
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at extractPlist$ (lib/extract.js:14:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
`

**Comment by imurchie** [comment]
The file `/Debug-iphonesimulator/myApp.app/Info.plist` exists?

**Comment by imurchie** [comment]
My guess is that `process.env.myApp_iOS_Directory` is supposed to have a value, and it does not. So the path gets set wrong for the app.

**Comment by rushabh55** [comment]
That path exists, its declared in ~/.bash_profile. Its loaded into the terminal instance. The /Debug-iphonesimulator/myApp.app/Info.plist also exsts

**Comment by imurchie** [comment]
Ok. Well, the system can't find it.

You can try setting the `bundleId` manually in your desired capabilities.
