### ISSUE TITLE
'WebDriver' object has no attribute 'context'

### ISSUE THREAD

**Issue by rams78** [appium/python-client#12]
> > > current = driver.context

Traceback (most recent call last):
  File "<pyshell#16>", line 1, in <module>
    current = driver.context
AttributeError: 'WebDriver' object has no attribute 'context'

You are not checking for Selenium package version and don't mention explicitly which version should be installed. I have selenium (2.41.0) - can this be the reason?

**Comment by tudi0410** [comment]
I have the samve problem, is there any solution?
