### ISSUE TITLE
install_app method  does not work

### ISSUE THREAD

**Issue by paulaladdin** [appium/python-client#120]
`self.driver.install_app(app_path)`

Has the result:

```
info: JSONWP Proxy: Proxying [POST /wd/hub/session/c003c5da54e5aa28bd5464a155e7ee63/appium/device/install_app] to [POST http://127.0.0.1:9515/wd/hub/session/c003c5da54e5aa28bd5464a155e7ee63/appium/device/install_app] with body: {"sessionId":"c003c5da54e5aa28bd5464a155e7ee63","appPath":"/totally/awesome/path/instant-dev-debug.apk"}
error: Could not proxy command to remote server. Original error: 404 - unknown command: session/c003c5da54e5aa28bd5464a155e7ee63/appium/device/install_app
```

(Note that `/totally/awesome/path` is not the actual path, I just changed it for this post)

**Comment by imurchie** [comment]
This is being proxied. Are you using Selendroid as a backend?

The full logs, as a [gist](https://gist.github.com/), would be helpful.

**Comment by claudemasso** [comment]
self.driver.install_app(app_path) and self.driver.remove_app(BUNDLE_ID) do not work anymore on appium 1.5 Is this going to be fix?

**Comment by imurchie** [comment]
Can you post the logs (as a gist) for the calls, so we can see what is going on and fix?
