### ISSUE TITLE
The description of swipe method is error in python language

### ISSUE THREAD

**Issue by wut0n9** [appium/python-client#123]
The method swipe was described in [here](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/appium-bindings.md#swipe):
`
driver.swipe(start=75, starty=500, endx=75, endy=0, duration=800)
`
the keyargs, such as **start**、**starty**、**endx**、**endy** are wrong;the method swipe was wrote:
```python
 def swipe(self, start_x, start_y, end_x, end_y, duration=None):
        """Swipe from one point to another point, for an optional duration.

        :Args:
         - start_x - x-coordinate at which to start
         - start_y - y-coordinate at which to start
         - end_x - x-coordinate at which to stop
         - end_y - y-coordinate at which to stop
         - duration - (optional) time to take the swipe, in ms.
        :Usage:
            driver.swipe(100, 100, 100, 400)
        """
```
TODO:
from  **start**  to  **start_x**
from  **starty** to **start_y**
from **endx** to **end_x**
from **endy**  to **end_y**
We may need to update the instruduction about the method  **swipe** in order to decrease error.
Thanks

**Comment by imurchie** [comment]
Thanks! I've updated the documentation. Thanks!
