### ISSUE TITLE
Problem with unescaped single quote

### ISSUE THREAD

**Issue by vsaraydarova** [appium/python-client#125]
I am searching for element with find_element_by_id and trying to set value using set_value - !\"#€%&&//()=[]{}'  function. I suspect that the problem is that the single quote at the end of the string is not escaped in the instruments js code - au.getElement('84').setValue('!"#€%&&//()=[]{}'')

automating iOS platform.
appium 1.4.16
Appium-python-client 0.21

> info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"f75ebf51-2715-4cd1-a89c-dc319bef7cba"}
> info: <-- POST /wd/hub/session/f75ebf51-2715-4cd1-a89c-dc319bef7cba/element/84/clear 200 951.585 ms - 74 {"status":0,"value":"","sessionId":"f75ebf51-2715-4cd1-a89c-dc319bef7cba"}
> info: --> POST /wd/hub/session/f75ebf51-2715-4cd1-a89c-dc319bef7cba/appium/element/84/value {"sessionId":"f75ebf51-2715-4cd1-a89c-dc319bef7cba","elementId":"84","value":["!\"#€%&&//()=[]{}'"],"id":"84"}
> info: [debug] Pushing command to appium work queue: "au.getElement('84').setValue('!\"#€%&&//()=[]{}'')"
> info: [debug] Sending command to instruments: au.getElement('84').setValue('!"#€%&&//()=[]{}'')
> info: [debug] [INST] 2016-03-09 09:18:12 +0000 Debug: responding with:
> info: [debug] [INST] 2016-03-09 09:18:12 +0000 Debug: Running system command #162: /usr/local/Cellar/node/5.6.0/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/ios1/instruments_sock 2,{"status":0,"value":""}...
> info: [debug] [INST] 2016-03-09 09:18:13 +0000 Debug: Got new command 162 from instruments: au.getElement('84').setValue('!"#€%&&//()=[]{}'')
> info: [debug] [INST] 2016-03-09 09:18:13 +0000 Debug: evaluating au.getElement('84').setValue('!"#€%&&//()=[]{}'')
> info: [debug] [INST] 2016-03-09 09:18:13 +0000 Error: SyntaxError: Unexpected EOF
> info: [debug] Socket data received (40 bytes)
> info: [debug] Socket data being routed.
> info: [debug] Got result from instruments: {"status":17,"value":"Unexpected EOF"}
> info: [debug] Responding to client with error: {"status":17,"value":{"message":"An error occurred while executing user supplied JavaScript.","origValue":"Unexpected EOF"},"sessionId":"f75ebf51-2715-4cd1-a89c-dc319bef7cba"}

**Comment by imurchie** [comment]
That does look like the problem. I will fix it on the server side.

**Comment by imurchie** [comment]
This should be fixed by https://github.com/appium/appium-ios-driver/pull/112

**Comment by vsaraydarova** [comment]
Thank you
