### ISSUE TITLE
Unable to run Inspector on Client

### ISSUE THREAD

**Issue by karbon62** [appium/python-client#128]
I am currently not able to run the Inspector feature on Client. The settings on Client are all set up; I've specified the device and also locations of the App but when I launch the Appium Server and Click on the 'Inspector' button - its throws an error.

**Comment by imurchie** [comment]
This sounds like an issue with the App (either Mac or Windows), not with the Python client library. Please open an issue on the respective application (Mac: https://github.com/appium/appium-dot-app; Windows: https://github.com/appium/appium-dot-exe).
