### ISSUE TITLE
set_text and set_value no longer working with appium 1.5

### ISSUE THREAD

**Issue by joshrlesch** [appium/python-client#129]
After upgrading to appium 1.5, it looks like the wrong parameters are being send for these methods.

`{WebDriverException}Message: Parameters were incorrect. We wanted {"required":{"value"}} and you sent ["id", "value","elementId","sessionId"]`

My code looks something like
element = self.driver.find_element_by_id("hello")
element.set_text("Name")

**Comment by imurchie** [comment]
Shoot. I thought we had handled all the extra parameters different clients send in.

Fixing.

**Comment by imurchie** [comment]
I have updated the Python client. Can you upgrade to 0.22 and try again. Sorry about that.

**Comment by joshrlesch** [comment]
:boom: Works well. Thank you on the quick turn around!

**Comment by imurchie** [comment]
You're welcome! And thanks for taking the time to report the problem.
