### ISSUE TITLE
self.w3c = "specificationLevel" in self.capabilities ;TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by rsmrahul1** [appium/python-client#132]
``` python
import unittest
 from appium import webdriver

desired_caps = {
 'platformName': 'WindowsModern',
 'app': 'Microsoft.WindowsCalculator_8wekyb3d8bbwe!App',

 }
 print desired_caps
 driver = webdriver.Remote('http://127.0.0.1:4723', desired_caps)
 print driver
 print driver.find_element_by_name('One')
```

---

https://github.com/Microsoft/WinAppDriver/
## Tried the WinAppDriver  with python and getting the below error from appium driver

in 
 driver = webdriver.Remote('http://127.0.0.1:4723', desired_caps)
 File "C:\Python27\lib\site-packages\appium\webdriver\webdriver.py", line 36, in init
 super(WebDriver, self).init(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
 File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 91, in init
 self.start_session(desired_capabilities, browser_profile)
 File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 181, in start_session
 self.w3c = "specificationLevel" in self.capabilities
##  TypeError: argument of type 'NoneType' is not iterable

In webdriver.py
 In the line
 self.capabilities = response['value']
 response['value'] seems to be null.

Did I miss anything in the python script ?

**Comment by imurchie** [comment]
It seems like the Microsoft WinAppDriver does not conform to the spec as the Python client want it. The code that is expecting a return value is in the standard Selenium client.

https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/webdriver.py#L176

I would open an issue on the WinAppDriver repository.

**Comment by rsmrahul1** [comment]
Thank you  imurchie .
