### ISSUE TITLE
MultiTouch MultiTap actions do not work

### ISSUE THREAD

**Issue by xukaipopo** [appium/python-client#135]
MultiTouch MultiTap actions do not work

**Comment by imurchie** [comment]
Can you be more specific with "do not work"? We cannot fix it if we don't know what is wrong. The command(s) used and the server logs would be great.

**Comment by viveksinghtt** [comment]
self.driver.zoom does not work stating method is not implemented.Multiaction just swipes down and does not do anything similar to zoom

**Comment by ki4070ma** [comment]
I've verified multiaction, multitap working on android during https://github.com/appium/python-client/pull/372.

* https://github.com/appium/python-client/blob/master/test/functional/android/multi_action_tests.py
   * test_parallel_actions
   * test_actions_with_waits
   * test_driver_multi_tap

Please freely reopen this issue if necessary.
