### ISSUE TITLE
How to run parallel appium tests in multiple android devices?

### ISSUE THREAD

**Issue by minar09** [appium/python-client#138]
Tried several ways with selenium grid, but so far only able to launch the app in multiple android devices simultaneously, but only one device run the test after that.

Anyone have a full solution?

**Comment by hicheng** [comment]
Sorry,I don't konw...

**Comment by bencebalint** [comment]
open another appium session with different port
<img width="971" alt="screen shot 2016-09-30 at 2 30 23 pm" src="https://cloud.githubusercontent.com/assets/22539279/18990456/9db83dba-871a-11e6-991a-6673c70c0d08.png">

**Comment by minar09** [comment]
Was able to lauch app in multiple devices using selenium grid in linux. But after launching, only one device could make it to the end of the test. Maybe I will give it a try in windows. Thanks @bencebalint

**Comment by hicheng** [comment]
thank you very much

在 2016-09-30 22:32:48，"Matiur Rahman Minar" <notifications@github.com> 写道：


Was able to lauch app in multiple devices using selenium grid in linux. But after launching, only one device could make it to the end of the test. Maybe I will give it a try in windows. Thanks @bencebalint

**Comment by fspinillo** [comment]
Appium provides [documentation](http://appium.io/slate/en/master/?python#parallel-android-tests) on how to perform parallel tests

**Comment by KazuCocoa** [comment]
https://github.com/appium/python-client/issues/138#issuecomment-298399316

**Comment by sreeja321** [comment]
@fspinillo  documentation url throwing the error like content not found.Can you resend the proper Url.
Thanks

**Comment by KazuCocoa** [comment]
http://appium.io/docs/en/advanced-concepts/parallel-tests/

**Comment by sreeja321** [comment]
@KazuCocoa  thanks for Quick response.
I need a favour,I could able to run pytest suite using appium and i could able to test the devices one by one.But i want to run parallel using **python client**.Can you send any documentation if possible.I can get the resource using (Java&selenium grid) combo.

**Comment by fspinillo** [comment]
@sreeja321 the information on parallel tests is here: http://appium.io/docs/en/advanced-concepts/parallel-tests/ and some other help can be found here https://nishantverma.gitbooks.io/appium-for-android/running_multiple_appium_server_for_parallel_execut.html

Where it's Java or Python the basic concept is the same: You need to start X instances of appium where X refers to the total number of devices

When starting the server you need to define a specific port & UDID (device-name when doing adb devices) with it:
```
appium -U udid -p port
```

And then in your desired capabilities you need to define the same UDID and port so the executor knows where to point.

**Comment by sreeja321** [comment]
thanks @fspinillo ..I went through the document.If i am correct here no selenium grid required know.
And In desired Capabilities do i need to maintain seperate file's for desired capabilites.Can you send sample file which include info about multiple devices desired caps.

**Comment by fspinillo** [comment]
@sreeja321 you can just use arguments inside of your conftest. If you're using python you can use the argparse class. If you're using pytest as your test runner it has a built in argument parser class that extends argparse.

Then just set your desired capabilities to be those variables passed

**Comment by saikrishna321** [comment]
@fspinillo 
>You need to start X instances of appium where X refers to the total number of devices

This is no more the case  with appium, from v 1.8.0 you can start single server and just send multiple client requests.

**Comment by KazuCocoa** [comment]
I implemented sample-code based parallel test running for iOS by pytest.
https://github.com/KazuCocoa/appium/commit/98034eb716d526fc54d7b3fac5acd249cd5fac9d

The difference between iOS and Android is port numbers and udid mentioned in http://appium.io/docs/en/advanced-concepts/parallel-tests/
But, https://github.com/KazuCocoa/appium/commit/98034eb716d526fc54d7b3fac5acd249cd5fac9d#diff-1f421ddc0a37b69e7525400235878fb2 will help you to how to change port numbers.

**Comment by sreeja321** [comment]
@KazuCocoa ,@fspinillo thanks a lot ...Your information is so valuable.

**Comment by sreeja321** [comment]
Hi all,
Please let me know if i am wrong my code is working fine but  appium lauches the app in mobiles devices one by one.
@fspinillo i could run x instances but below script fail to test parallely
class BaseTest(unittest.TestCase):

    # setUp runs before each test case
    def setUp(self):
        desired_caps = {}
        desired_caps['platformName'] = 'Android'
        desired_caps['platformVersion'] = '5.0.2'
        desired_caps['deviceName'] = 'LGD7228668e443'
        desired_caps['app'] = os.path.realpath(__file__ + "/../app-staging-1.2.1.1.apk")
        desired_caps['nosign']='true'
        desired_caps['noReset'] = 'true'
        desired_caps['newCommandTimeout'] = 240

        self.driver = webdriver.Remote('http://0.0.0.0:4723/wd/hub', desired_caps)

        
        
        
        desired_caps1 = {}
        desired_caps1['platformName'] = 'Android'
        desired_caps1['platformVersion'] = '6.0'
        desired_caps1['deviceName'] = 'emulator-5554'
        desired_caps1['app'] = os.path.realpath(__file__ + "/../app-staging-1.2.1.1.apk")
        desired_caps1['nosign']='true'
        desired_caps1['noReset'] = 'true'
        desired_caps1['newCommandTimeout'] = 240

        self.driver1 = webdriver.Remote('http://0.0.0.0:4733/wd/hub', desired_caps1)

        
        
        def tearDown(self):
        self.driver.quit()
        self.driver1.quit()

**Comment by sreeja321** [comment]
@fspinillo  ,Could you explain me bit clear.How can i pass above script desired caps dict using argphase in pytest.
 you can just use arguments inside of your conftest. If you're using python you can use the argparse class. If you're using pytest as your test runner it has a built in argument parser class that extends argparse.

Then just set your desired capabilities to be those variables passed

**Comment by fspinillo** [comment]
> but appium lauches the app in mobiles devices one by one.

You can't have two desired caps in a single conftest unless you're splitting them out

> How can i pass above script desired caps dict using argparse

See [here](https://docs.python.org/3/howto/argparse.html#id1) on how to use argparse. You can set the variables to port number and device name. So you can essenitally do python test.py -U [UDID] -P [port] then in your confest you look for the arguments and pass them in where needed.

**Comment by sreeja321** [comment]
Hi fspinillo thanks a lot.Now i could able to test two android devices parallel.But it always runs only one test case.have you any idea about to run entire suite.
Can i run pytest(unit test) suite parallel.I wrote 100 plus test cases.And i am using jenkins here

**Comment by KazuCocoa** [comment]
An appium server can handle 2 sessions in the example case. One is with WDA port 8100 and another one is WDA port 8101.
The configuration is like below.
```
pytest suite ==session1==> xdist(core1) ==session1/2==> Appium( port: 4723 ) ==session1==> run test 1 on `iPhone 6s - 8100`
             `=session2=> xdist(core2) =/                          `==session2==>  run test 2 on `iPhone 6s - 8101`
```

I think what you'd like to is:

```
pytest suite ==session1==> xdist(core1) ==session1==> Appium (port: 4723) ==session1=> run test 1 on `iPhone 6s - 8100`
              `=session2=> xdist(core2) ==session2==> Appium (port: 4733) ==session2=>  run test 2 on `iPhone 6s - 8101`
```

In this case, you can establish each sessions with `webdriver.Remote('http://0.0.0.0:4723/wd/hub', desired_caps)` and `webdriver.Remote('http://0.0.0.0:4733/wd/hub', desired_caps1)`. As already mentioned in http://appium.io/docs/en/advanced-concepts/parallel-tests/ , in android, especially `uiautomator2`, case, you must set `systemPort` as one of capabilities to avoid conflict. But both case is same between Appium and each devices.

How split one test suite to multiple test cases run on which xdist (core x) depend on pytest and xdist, I belive.

I can see your pytyon clients send actions for either below case

1. `session1` and `session2` 
    - But tests run only session1 <= I guess it happens in your env. In this case, I anticipate an issue exists between your test suite and xdist. (How split one test suite for each cores.)
    - Or tests run both session1 and session2 properly <= the example
2. only `session1` (or `session2`)
    - And tests run only session1 (or session2)

**Comment by tking16** [comment]
> As already mentioned in http://appium.io/docs/en/advanced-concepts/parallel-tests/ ,

@KazuCocoa The link is 404ing. Has it been moved elsewhere? 

I'm trying to get my test suite to run in parallel using Selenium Grid and Pytest-xDist, but I'm having trouble configuring the ports on the xdist side, I just followed this guide so I believe the selenium grid side is okay https://appium.io/docs/en/2.1/guides/grid/
