### ISSUE TITLE
Error when trying to get picker wheel values on iOS

### ISSUE THREAD

**Issue by rz-robsn** [appium/python-client#140]
Hi,

I am trying to get the list of available values for a picker wheel. To do so, I am using the call `picker_wheel_element.get_attribute("values")`. 

This should work, since UIAPickerWheel define such an attribute [here](https://developer.apple.com/library/ios/documentation/ToolsLanguages/Reference/UIAPickerWheelClassReference/#//apple_ref/javascript/instm/UIAPickerWheel/values). However, I am thrown the following error instead :

```
AttributeError: 'list' object has no attribute 'lower'
```

Which I believe is thrown in the following line from the `get_attribute()` method declared the selenium `WebElement` class:

```
if name != 'value' and attributeValue.lower() in ('true', 'false'):
```

It seems `get_attribute` always expect a string to be returned from the "getElementAttribute" command, which is not the case when calling `values` on a picker wheel.

So my question is: what is the best way to get the available options in a picker ?

**Comment by imurchie** [comment]
What comes back from getting `value`?

**Comment by rz-robsn** [comment]
`picker_wheel_element.get_attribute(“value”)` returns the currently
selected value of the wheel.
