### ISSUE TITLE
send_keys could not input the whole string  in the textfield

### ISSUE THREAD

**Issue by kentzhu1020** [appium/python-client#149]
Environment:
Appium v1.5.3
Nodejs v6.5.0
Android: Samsung Galaxy S5 - 4.4.4 - API 19 - 1080x1920 4.4.4
chromedriver:25

The component on Android system is **android.widget.EditText**
using driver.find_element_by_id("MY_ID").send_keys("2111") to input the string 2111 to the text field. It would always type "2" or "21" or "211" to the field. it could not input the whole string in the edit text correctly.

**Comment by KazuCocoa** [comment]
What about enabling `unicodeKeyboard`?
(and `resetKeyboard`?)
http://appium.io/docs/en/writing-running-appium/caps/

**Comment by llpan-github** [comment]
> What about enabling `unicodeKeyboard`?
> (and `resetKeyboard`?)
> http://appium.io/docs/en/writing-running-appium/caps/

 I have the same problem in ios，
using driver.find_element_by_ios_predicate('label == "请输入密码"').set_value("11111qQ.\n") to input the string  
log is POST http://127.0.0.1:4725/wd/hub/session/ebc66c68-65b2-4ac1-ba2a-60985c14f024/appium/element/AA000000-0000-0000-500D-000000000000/value {"id": "AA000000-0000-0000-500D-000000000000", "value": ["11111qQ.\n"]}
but the actual result is "1111qQ."  
occasional appearance
sometimes it‘s ok
