### ISSUE TITLE
I can't find elem by iOS predicates use element type

### ISSUE THREAD

**Issue by lunamagic1978** [appium/python-client#153]
Hi

Now I find two elements in page_source
 they have the same name by "问吧"
but one is Button, one is staticText
<XCUIElementTypeButton type="XCUIElementTypeButton" name="问吧" label="问吧" visible="true" enabled="true" x="866" y="27" width="88" height="59"/>
<XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="问吧" name="问吧" label="问吧" visible="false" enabled="true" x="0" y="0" width="54" height="28"/>

I read README.md of Appium Python Client

Finding elements by iOS predicates

This method allows finding elements using iOS predicates. The methods take a string in the format of a predicate, including element type and the value of fields.

el = self.driver.find_element_by_ios_predicate('wdName == "Buttons"')

so i use 
[el = self.driver.find_element_by_ios_predicate('wdName == "Buttons"')]
try to find buttons element ,but i get the result is failed
NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

If i use 
[bt = driver.find_element_by_ios_predicate("name == '问吧'")]
I can find the buttons element.

what can i do if i need use element type to find element?

**Comment by mykola-mokhnach** [comment]
Can you please attach page source received from driver.get_page_source() method call and Appium log?

**Comment by mykola-mokhnach** [comment]
Also, you can simply use location by accessibility id locator type, since for WDA it's the same string as wdName/name.

**Comment by lunamagic1978** [comment]
@mykola-mokhnach thx
this is my python
        bt = driver.find_element_by_ios_predicate("name == '问吧'")
        el = driver.find_element_by_ios_predicate('Type == "Buttons"')
------------------------------------------------------------------------------------
this is page_source 

<XCUIElementTypeButton type="XCUIElementTypeButton" name="问吧" label="问吧" visible="true" enabled="true" x="866" y="27" width="88" height="59"/>

<XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="问吧" name="问吧" label="问吧" visible="false" enabled="true" x="0" y="0" width="54" height="28"/>
------------------------------------------------------------------------------------
this is appium log
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/99B654A4-00DB-48A7-AD5C-D43239A88654/element] with body: {"using":"predicate string","value":"name == '问吧'"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"E967C91F-9C5C-4211-B905-609C6FAB79B6","type":"XCUIElementTypeButton","label":"问吧"},"sessionId":"99B654A4-00DB-48A7-AD5C-D43239A88654","status":0}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"E967C91F-9C5C-4211-B905-609C6FAB79B6","type":"XCUIElementTypeButton","label":"问吧"}
[HTTP] <-- POST /wd/hub/session/19409482-bfad-4bd7-9c74-ce9febe5de98/element 200 1542 ms - 170 
[HTTP] --> POST /wd/hub/session/19409482-bfad-4bd7-9c74-ce9febe5de98/element {"using":"-ios predicate string","sessionId":"19409482-bfad-4bd7-9c74-ce9febe5de98","value":"Type == \"Buttons\""}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["-ios predicate string","Type == \"Buttons\"","19409482-bfad-4bd7-9c74-ce9febe5de98"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/99B654A4-00DB-48A7-AD5C-D43239A88654/element] with body: {"using":"predicate string","value":"Type == \"Buttons\""}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"predicate string","value":"Type == \"Buttons\"","description":"unable to find an element"},"sessionId":"99B654A4-00DB-48A7-AD5C-D43239A88654","status":7}
[HTTP] <-- POST /wd/hub/session/19409482-bfad-4bd7-9c74-ce9febe5de98/element 500 850 ms - 164 
[HTTP] --> DELETE /wd/hub/session/19409482-bfad-4bd7-9c74-ce9febe5de98 {}
[debug] [MJSONWP] Calling AppiumDriver.deleteSession() with args: ["19409482-bfad-4bd7-9c74-ce9febe5de98"]
[debug] [JSONWP Proxy] Proxying [DELETE /session/19409482-bfad-4bd7-9c74-ce9febe5de98] to [DELETE http://localhost:8100/session/99B654A4-00DB-48A7-AD5C-D43239A88654] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"B0ADBFB0-3B8A-4AFA-AD08-E19BDFD16D33\",\n  \"status\" : 0\n}"
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down xcodebuild process (pid 817)
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[debug] [XCUITest] Reset not set, not ending sim
[debug] [iOSLog] Stopping iOS log capture
-----------------------------------------------------------------------------------

accessibility id is good idea.but i need add accessibility id into program.
sometime it is hard to do .

at first , i understand  wdName is name , it is help to me.

el = self.driver.find_element_by_ios_predicate('wdName == "Buttons"')

it is mean one element is locator by name , it is name is Buttons.

if have a way use iOS predicates to locator element by it's type, let me know.

**Comment by mykola-mokhnach** [comment]
Page source is still missing

**Comment by lunamagic1978** [comment]
sorry, i write page source but i think it is become a party of html.
i use "[]"  replace " <>"

[XCUIElementTypeButton type="XCUIElementTypeButton" name="问吧" label="问吧" visible="true" enabled="true" x="866" y="27" width="88" height="59"/]

[XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="问吧" name="问吧" label="问吧" visible="false" enabled="true" x="0" y="0" width="54" height="28"/]

**Comment by lunamagic1978** [comment]
i get the answer. 

el = driver.find_element_by_ios_predicate("name == '问吧' AND type ='XCUIElementTypeStaticText'")
el2 = driver.find_element_by_ios_predicate("name == '问吧' AND type ='XCUIElementTypeButton'")

there has one attribute [type].

thx my kola-mokhnach again

**Comment by oscheller87** [comment]
I think the real question is, why do we use `type` as a keyword in the predicate string, if the official keyword (defined in https://developer.apple.com/reference/xctest ) would be `XCUIElementType` ? Is there an overview of keywords that we can use within the `driver.find_element_by_ios_predicate` function from this python client? I know of `type` and `name`. What others are there?

**Comment by jlipps** [comment]
we have some docs here: https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios_predicate.md not sure it mentions other keywords though.

**Comment by mykola-mokhnach** [comment]
@oscheller87 Only FBElement property names are allowed. Check https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/Routing/FBElement.h   and https://github.com/facebook/WebDriverAgent/pull/397 for more details.

**Comment by oscheller87** [comment]
Thank you for the links. @mykola-mokhnach Is it possible to implement support for the accessibility identifier in the near future? Or is the accessibility identifier accessible in a different way? I'm rather new to predicates 

Also @jlipps, The page you linked shows that `appiumDriver.findElementsByIosUIAutomation("collectionViews()[0].cells().withPredicate(\"ANY staticTexts.isVisible == TRUE\")");
` equals `appiumDriver.findElementsByIosNsPredicate("isWDVisible == 1");
` with the new predicate search functions provided by appium. (python client in my case)

With this, I'm unable to search for an element using the element hierarchy (e.g. like i used to be with xpath). I've already played around with predicate in the appium python client and i feel like it's inconsistent with the official docs, or at least it can not be used how it's supposed to be used... - it feels super weird coming from xpath, which works so wunderful in every way (except that it's slow as hell ...)

**Comment by mykola-mokhnach** [comment]
@oscheller87 accessibility identifier is the same as wdName/name.
Regarding stability - we are working on it. Next version of Appium should already contain recent WDA changes ~~and will be the best of the best~~
And you are also welcome to contribute there.
