### ISSUE TITLE
[Proposal] Rename swipe function for relative changes

### ISSUE THREAD

**Issue by BasThomas** [appium/python-client#155]
As a swipe is now relative to the point from where you start, the definition is confusing.

The definition and its docstring can be seen below.

```python
def swipe(self, start_x, start_y, end_x, end_y, duration=None):
    """Swipe from one point to another point, for an optional duration.

    :Args:
     - start_x - x-coordinate at which to start
     - start_y - y-coordinate at which to start
     - end_x - x-coordinate at which to stop
     - end_y - y-coordinate at which to stop
     - duration - (optional) time to take the swipe, in ms.
    :Usage:
        driver.swipe(100, 100, 100, 400)
    """
```

According to the definition and the docstring:
- The starting point is (x: 100, y: 100)
- The stopping point is (x: 100, y: 400)

Although, as relative swiping is now used, what actually happens is the following:
- The starting point is (x: 100, y: 100)
- The stopping point is (x: 200, y: 500) aka (x: 100+100, y: 100+400)

I propose the change both the definition and docstring in the following:

```python
def swipe(self, start_x, start_y, move_x, move_y, duration=None):
    """Swipe from one point to another point, for an optional duration.

    :Args:
     - start_x - x-coordinate at which to start
     - start_y - y-coordinate at which to start
     - move_x - amount to move on the x-axis
     - move_y - amount to move on the y-axis
     - duration - (optional) time to take the swipe, in ms.
    :Usage:
        driver.swipe(100, 100, 100, 400)
    """
```

Thoughts?

**Comment by jlipps** [comment]
@BasThomas I agree with this _if_ we want to keep the relative behavior. I'm not at all sure that we want to. I think different drivers work differently on this for now. @imurchie we need to figure out once and for all whether things are absolute or relative, and adjust all the drivers accordingly. Maybe we should take a queue from the freshly baked w3c action spec?

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/issues/7702#issuecomment-365965000
