### ISSUE TITLE
BadParametersError while trying to connect to Appium server

### ISSUE THREAD

**Issue by luiscruz** [appium/python-client#158]
I am trying to create a driver:

```
desired_caps = {}
desired_caps['platformName'] = 'Android'
desired_caps['platformVersion'] = '4.2'
desired_caps['deviceName'] = 'Android Emulator'
desired_caps['app'] = PATH(
    '../../../sample-code/apps/ApiDemos/bin/ApiDemos-debug.apk'
)

self.driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
```

And I get this error:

```
[debug] [MJSONWP] Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":["desiredCapabilities"],"optional":["requiredCapabilities","sessionId","id","sessionId","id","sessionId","id","sessionId","id","sessionId","id"]} and you sent ["capabilities","desiredCapabilities"]
```

I am using Appium v1.5.3. Am I doing something wrong?

**Comment by mykola-mokhnach** [comment]
Probably, the same [fix](https://github.com/appium/java-client/pull/597) should be applied to python driver to make it compatible to Selenium 3.2+

**Comment by Mulley** [comment]
I experienced this issue today.
I was able to work around it by specifying selenium==3.3.1 before Appium-Python-Client in my requirements.txt.

Selenium put out 3.3.2 today which seems to be causing the issue.
https://github.com/SeleniumHQ/selenium/commit/fbc7acfa9ffda7158d3f06f1a17e78a62ae954e0

**Comment by luiscruz** [comment]
@Mulley that worked for me

**Comment by mwalla210** [comment]
Issue still experienced on Selenium 3.3.3 as of today with Appium-Python-Client 0.24 and Appium Gui 1.5.3. 
Rolling back to Selenium 3.3.1 is working.

**Comment by jlipps** [comment]
@mwalla210 try the latest appium (1.6.4), we made some updates to new session params.

**Comment by ki4070ma** [comment]
If this error still occurs, please reopen.
