### ISSUE TITLE
push_file example has encoding error

### ISSUE THREAD

**Issue by timyhou** [appium/python-client#164]
I am trying to use the .push_file() method described in the python wrapper for appium. I copy pasted the example from the [functional android appium tests](https://github.com/appium/python-client/blob/master/test/functional/android/appium_tests.py) and I keep getting the following error.

```
 def test_push_file(self):
    path = 'data/local/tmp/test_push_file.txt'
    data = 'This is the contents of the file to push to the device.'
    self.driver.push_file(path, data.encode('base64'))
    data_ret = self.driver.pull_file('data/local/tmp/test_push_file.txt').decode('base64')
    self.assertEqual(data, data_ret)
```

`
LookupError: 'base64' is not a text encoding; use codecs.encode() to handle arbitrary codecs
`

So I tried following the suggestion and making a tweak to get the encoding to work. However, then I get a JSON error

 ```
def test_push_file(self):
	import codecs
    path = 'data/local/tmp/test_push_file.txt'
    data = b'This is the contents of the file to push to the device.'
    self.driver.push_file(path, codecs.encode(data, 'base64'))
```

Error
```
self = <json.encoder.JSONEncoder object at 0x10c0cccf8>
o = b'VGhpcyBpcyB0aGUgY29udGVudHMgb2YgdGhlIGZpbGUgdG8gcHVzaCB0byB0aGUgZGV2aWNlLg==\n'

    def default(self, o):
        """Implement this method in a subclass such that it returns
            a serializable object for ``o``, or calls the base implementation
            (to raise a ``TypeError``).
    
            For example, to support arbitrary iterators, you could
            implement default like this::
    
                def default(self, o):
                    try:
                        iterable = iter(o)
                    except TypeError:
                        pass
                    else:
                        return list(iterable)
                    # Let the base class default method raise the TypeError
                    return JSONEncoder.default(self, o)
    
            """
>       raise TypeError(repr(o) + " is not JSON serializable")
E       TypeError: b'VGhpcyBpcyB0aGUgY29udGVudHMgb2YgdGhlIGZpbGUgdG8gcHVzaCB0byB0aGUgZGV2aWNlLg==\n' is not JSON serializable

../../../.pyenv/versions/3.5.1/lib/python3.5/json/encoder.py:180: TypeError

```

Can someone provide some guidance on this? 
For the record I am using
python 3.5.1
selenium (2.53.6)
Appium-Python-Client (0.24)
appium server 1.64

**Comment by jlipps** [comment]
Doesn't the `b` in front indicate it's binary? It needs to be a vanilla string in base 64 encoding.

**Comment by timyhou** [comment]
It seems the `b` is a byte literal. I was looking up [Base64 encoding ](http://stackoverflow.com/questions/8908287/base64-encoding-in-python-3) and found that using either import codecs or base64, the argument has to be bytes-like, not string. Either way, this results in a JSON Encoding error similar to above. 

It is possible to pass just a plain old string into `push_file`, however the assertion in the test fails like so. 

```
 def test_push_file(self):
    path = 'data/local/tmp/test_push_file.txt'
    data = 'This is the contents of the file to push to the device.'
    self.driver.push_file(path, data)
    data_ret = self.driver.pull_file('data/local/tmp/test_push_file.txt')
    # data_ret = 'Thisisthecontentsofthefiletopushtothedevice/'
    self.assertEqual(data, data_ret)
```
We seem to have lost the spaces, but at least something was sent to the device.

**Comment by timyhou** [comment]
I can make this work with a real file oddly enough. Maybe the test example is not the greatest one to follow. 

```
path = 'sdcard/Download/file.doc'
filepath ='/home/user/thefile.doc'
with open(file=filepath, mode='rb') as myfile:
    import base64
    encoded_file = base64.b64encode(myfile.read())
# We need to decode to get rid of the b'' bytes literal for the upload to work
self.webdriver.driver.push_file(path, encoded_file.decode())
# On the device, the file appears in the correct format
```

**Comment by timyhou** [comment]
I will close this, as it is working as intended. You just need to do some extra encoding/decoding to make it work as expected which was not documented anywhere that I could tell.
