### ISSUE TITLE
iOS 9.3 dirver.shake() can not effect

### ISSUE THREAD

**Issue by yaosum** [appium/python-client#165]
e-mail:yyaosumei@126.com

**Comment by imurchie** [comment]
Can you elaborate?

**Comment by yaosum** [comment]
I tried to use the function that driver.shake() to simulate shaking the phone. But it did not work. The mobile phone system I used is iOS9.3.

**Comment by KazuCocoa** [comment]
`Shake` is mentioned as the following.

- https://github.com/appium/appium-xcuitest-driver#known-issues
- https://github.com/appium/appium/issues/5966 (UIAutomation)
