### ISSUE TITLE
How to short circuit login step in tested app for some tests?

### ISSUE THREAD

**Issue by ibizaman** [appium/python-client#166]
As step 1, my app requires logging to a backend server. The user is required to enter a username and password. Testing that is done and works totally fine.

What I'd like to do now is, instead of needing to login in each test, short-circuit that step for every other test but the one testing the login. This could be easily done by starting the app with and intent having the login info. But that requires being able to start the application with a custom intent, which I don't think is yet possible.

Would there be a way to add that?
Or is there a way to short-circuit this logging step without using a custom intent?

**Comment by jlipps** [comment]
@ibizaman you can use the `start_activity` method to launch custom intents, once your appium session is loaded:

```py
driver.start_activity('app.package', 'app.activity', **args)
```

keyword args can be:

```
        - app_package - The package containing the activity to start.
        - app_activity - The activity to start.
        - app_wait_package - Begin automation after this package starts (optional).
        - app_wait_activity - Begin automation after this activity starts (optional).
        - intent_action - Intent to start (optional).
        - intent_category - Intent category to start (optional).
        - intent_flags - Flags to send to the intent (optional).
        - optional_intent_arguments - Optional arguments to the intent (optional).
        - dont_stop_app_on_reset - Should the app be stopped on reset (optional)?
```
