### ISSUE TITLE
Request: Please add support for -ios class chain

### ISSUE THREAD

**Issue by lavi-xu** [appium/python-client#171]
Since xpath is not recommand for xcuitest, we would like to have class chain method for our testing.

Thanks.

BR,

**Comment by KazuCocoa** [comment]
How about the following branch?

- https://github.com/KazuCocoa/python-client/tree/add_class_chain
    - commit: https://github.com/KazuCocoa/python-client/commit/01042ef5ad84ffcb83b6bc2ee16aa78f409882d1

**Comment by lavi-xu** [comment]
@KazuCocoa  

That works great. 
Could someone merge that back to this repo?

BR.

**Comment by KazuCocoa** [comment]
Thanks! I'll create a PR and ask other members.

**Comment by KazuCocoa** [comment]
I think we need to update README for the feature after merge ^.

**Comment by KazuCocoa** [comment]
@lavi-xu the PR has merged to master 👍

**Comment by KazuCocoa** [comment]
@lavi-xu method name is changed in current master branch.
find_elements_by_class_chain => find_elements_by_ **ios_** class_chain
https://github.com/appium/python-client/pull/174

And could you close this issue?
