### ISSUE TITLE
Extra headers on HTTP requests

### ISSUE THREAD

**Issue by mariusnita** [appium/python-client#176]
Hi, is there a way to attach extra headers to the HTTP requests issued by the `webdriver.Remote` object? My use case is I want to add a custom authentication layer on top of appium. This would look for an `Authorization` header on HTTP requests and reject if auth doesn't check out.

**Comment by imurchie** [comment]
I don't think there is provision for this. 

See https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/2047

**Comment by mariusnita** [comment]
Hi @imurchie thanks for the pointer!

**Comment by mariusnita** [comment]
BTW for posterity, I think a possible method for adding an auth layer would be to embed an auth token in the url like `https://<host>:<port>/<auth_token>/wd/hub` and the server would be a simple proxy that strips the token and checks it, and forwards the request down to the real appium server.
