### ISSUE TITLE
[question] aws-device-farm: can we set capabilities?

### ISSUE THREAD

**Issue by awitherow** [appium/python-client#178]
In local testing, I have simply done the following to test cross platform stuff

```
 if self.driver.capabilities['platformName'] == "iOS":
```

It works due to capabilities being passed in when local, but I have often seen people leaving these out when interacting with Amazon Device Farm.

Is it possible to pass capabilities like this to the Amazon Device Farm Driver, like below?

```python
local_capabilities = {
    'ios-develop': {
        'app': os.path.join(
            os.getcwd(),
            'app/ios/build/Build/Products/Release-iphonesimulator/one.app'
        ),
        'platformName': 'iOS',
        'platformVersion': '10.3',
        'deviceName': 'iPhone Simulator',
    },
    'android-develop': {
        'app': os.path.join(
            os.getcwd(),
            'app/android/app/build/outputs/apk/app-release.apk'
        ),
        'platformName': 'Android',
        'deviceName': 'Android Emulator',
    }
}

device_farm_capabilities = {
    'ios': {
        'platformName': 'iOS',
    },
    'android': {
        'platformName': 'Android',
    }
}


class BaseTest(unittest.TestCase):
    """Basis for all tests."""

    def setUp(self):
        """Sets up desired capabilities and the Appium driver."""
        url = 'http://127.0.0.1:4723/wd/hub'
        desired_caps = local_capabilities[device] if local else device_farm_capabilities[device]

        self.driver = webdriver.Remote(url, desired_caps)
```

**Comment by imurchie** [comment]
I don't understand what you are asking. Is it possible to just send something like `{'platformName': 'iOS'}` as the desired capabilities to Android Device Farm?

**Comment by awitherow** [comment]
I have a single test suite that I am trying to run for iOS and Android (react-native), and I use conditional statements within my unit tests to do certain actions on certain platforms.

```
if self.driver.capabilities['platformName'] == "iOS":
     self.do_action_that_is_iOS_only
```

I just need a way to identify the device without having to pass in capabilities. Or does it just not know?

**Comment by imurchie** [comment]
Hmm. The returned capabilities from creating the session ought to have distinguishing features, no matter where you are running the Appium server.

**Comment by awitherow** [comment]
which can be accessed with `get_capabilities`? This does not seem to be a driver method though, but that would probably be in the realms of selenium.

**Comment by imurchie** [comment]
Just `driver.capabilities`.
