### ISSUE TITLE
missing methods for iOS class chain

### ISSUE THREAD

**Issue by hectorv** [appium/python-client#180]
I'm using what seems to be the latest version of the Appium client
```
Appium-Python-Client (0.24)                   - Python client for Appium 1.5
  INSTALLED: 0.24 (latest)
```
but it's somehow missing the methods for the iOS class chain:
https://github.com/appium/python-client#finding-elements-by-ios-class-chain

are either PyPI or the README out of date?
Thanks!

**Comment by hectorv** [comment]
I can confirm that installing directly from GitHub _does_ include the iOS class chain methods:
```
pip install -e git+https://github.com/appium/python-client.git#egg=appium
```
so it seems like the published version on PyPI is out of date.

**Comment by jlipps** [comment]
@imurchie do you mind doing a release when you get a chance?

**Comment by hectorv** [comment]
@jlipps @imurchie ?

**Comment by sathaiahc** [comment]
@jlipps @imurchie can you please do a release when you get a chance?

**Comment by KazuCocoa** [comment]
https://pypi.python.org/pypi/Appium-Python-Client/0.25 should include this.

**Comment by hectorv** [comment]
@KazuCocoa thanks! It would be good to keep the repo releases in sync with PyPI:
https://github.com/appium/python-client/releases

**Comment by sathaiahc** [comment]
@KazuCocoa Thanks
