### ISSUE TITLE
Appium python touch action cannot moveTo for multiple elements

### ISSUE THREAD

**Issue by aray0322** [appium/python-client#183]
appium V1.6.5
ios: 10.12.6
real phone: iphone 5s

ta = TouchAction(driver)
ta.press(items[0]).wait(500).move_to(items[1]).wait(500).move_to(items[2]).wait(500).move_to(items[5]).wait(500).move_to(items[8]).release().perform()   

For IOS, it always returns the following messages.  It is works fine on Android with the same version.

Message: Support for press(options={"element":"24593525-0323-433D-BF7D-7197CFDCEFB6","x":null,"y":null})-wait(options={"ms":500})-moveTo(options={"element":"A6DE8BDC-553C-4434-8284-24BBC6A32739","x":null,"y":null})-wait(options={"ms":500})-moveTo(options={"element":"89D898BD-9015-41A2-B928-C161E9F47239","x":null,"y":null})-wait(options={"ms":500})-moveTo(options={"element":"719A7592-BF4F-4AF2-9FEF-159D789AD54A","x":null,"y":null})-wait(options={"ms":500})-moveTo(options={"element":"09149987-48FB-46DF-B646-FBC54223BD0C","x":null,"y":null})-release(options={}) gesture is not implemented. Try to use "mobile: *" interface to workaround the issue. Only these gestures are supported:
	doubleTap: 		doubletap
		tap(options={"count":2})
	tap: 		tap
		tap-release
		press-release
	longPress: 		longpress
		longpress-release
		press-wait-release
	drag: 		press-wait-moveTo-release
		longpress-moveTo-release
	scroll: 		press-moveTo-release

**Comment by mykola-mokhnach** [comment]
This cannot be done with XCTest. It just does not provide such APIs

**Comment by aray0322** [comment]
How can i complete it on XCTest?

**Comment by mykola-mokhnach** [comment]
Sorry, I didn't get you question.

**Comment by aray0322** [comment]
I have a nine miyagi that needs to slide unlocking.  So i need to touch 5 elements to complete it.
Just like touchaction(driver).press(ele1).move_to(ele2).move_to(ele3).move_to(ele4).release.perform()

how to complete on IOS?

**Comment by aray0322** [comment]
The following is Android code. It works fine. But it is not working on IOS with real phone.
def PasswordTouchActions(driver, items):
    ta = TouchAction(driver)
    ta.press(items[0]).move_to(items[1]).move_to(items[2]).move_to(items[5]).move_to(items[8]).release()
    ta.perform()
    ta.press(items[0]).move_to(items[1]).move_to(items[2]).move_to(items[5]).move_to(items[8]).release()
    ta.perform()

**Comment by mykola-mokhnach** [comment]
Currently there is no known way of doing it on iOS. Please share your findings with us if you find out how to perform such gesture with Apple's XCTest

**Comment by aray0322** [comment]
I want to complete this.  Just add my comment here.
http://upload-images.jianshu.io/upload_images/2156697-4afbd493717f54a7.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240

**Comment by aray0322** [comment]
@mykola-mokhnach Is there any update? Still does't support on IOS?

**Comment by mykola-mokhnach** [comment]
Try it with the latest appium@beta
