### ISSUE TITLE
Using appium on device services

### ISSUE THREAD

**Issue by avichaymeiri** [appium/python-client#186]
Is there any support for using appium in order to change any device state?
for example, can I turn on/off wifi or battery saving mode etc.?
Thanks in advance..

**Comment by KazuCocoa** [comment]
You can see in https://github.com/appium/appium/tree/master/docs/en/commands/device/network , for example.
@avichaymeiri 

---

ref:

- https://github.com/appium/python-client/blob/0a40589d6aa5ce817226dcf563f1b200eafa0ada/appium/webdriver/mobilecommand.py
- https://github.com/appium/appium/tree/master/docs/en/commands
