### ISSUE TITLE
Cannot use 'set_value' with Unity app

### ISSUE THREAD

**Issue by vnicolev** [appium/python-client#192]
**Prerequisites:**
I'm testing a Unity app on iPhone 6(ios 10.3.2) with Appium v1.7.1 and Python-client v0.14.
Since Appium is not able to locate Unity element, I've used OpenCV image recognition to get the coordinate of the text field that I want to tap and trying to send a value into the text field.

```
  def test_login(self):
      sleep(30)
      # Capturing the screen on real device
      directory = '%s/img/sceneImg/' % os.getcwd()
      file_name = 'loginPage.png'
      self.driver.save_screenshot(directory + file_name)

      # Getting the coordinate with openCV and sending value to text field
      imgpath = '%s/img/' % os.getcwd()
      mid_coordinate_x, mid_coordinate_y = getImgcoordinate(os.path.join(imgpath+'queryImg/inputId.png'),os.path.join(imgpath+'sceneImg/loginPage.png'),'input_id')
      self.driver.tap([(mid_coordinate_x,mid_coordinate_y)])
      self.driver.set_value('username')
      self.driver.hide_keyboard(strategy='tapOutside')  
```

**Expected Result:**
Input username into the text filed after taped the text filed with it's coordinate.

**Actual Result:**
```
TypeError: set_value() takes exactly 3 arguments (2 given)
```

Is there a way to call set_value without sending element?

**Comment by ochubey** [comment]
Not sure if it present in Python binding, but from java-client you can try to get the keyboard and set value. Of course, you need to click on the text field by coordinates.
Java:
> driver.getKeyboard().sendKeys(str);

**Comment by vnicolev** [comment]
Hi ochubey, I cannot find a method in Python-client to get the keyboard, only found 'hide_keyboard'. I've also tried to add 'get_keyboard' in my test script, but I got an error said: "AttributeError: 'WebDriver' object has no attribute 'get_keyboard'".
Anyway, still very appreciate your answer : )

**Comment by vnicolev** [comment]
I'm still stuck in this problem. Any idea or direction would be helpful. Thanks!

**Comment by vnicolev** [comment]
Just want to share that, this problem is solved by grabbing one of the keys before using set_value().
Here's my code:
```
action = TouchAction(self.driver)
action.tap(None, mid_coordinate_x, mid_coordinate_y, 1).perform()
shift = self.driver.find_element_by_name('shift')
shift.set_value('username')
self.driver.hide_keyboard('return')
```
Thanks @ochubey for giving me this idea!

**Comment by ochubey** [comment]
@vnicolev you are welcome.
