### ISSUE TITLE
Waiting for any element by ID

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [appium/python-client#193]
I can wait for an element by Id like this:

```
WebDriverWait(driver,time).until(expected_conditions.visibility_of_element_located((By.ID,id)));
```

Now, I have multiple elements (I have the ids) and I want to wait until _any_ of them is visible.
How can I do that?

**Comment by KazuCocoa** [comment]
I'm not sure Python case.
https://discuss.appium.io/ also probably help you.

**Comment by KazuCocoa** [comment]
I guess you can also use `uiautomator` strategy for Android and `predicate` strategy for iOS.
Or, you can also implement a loop method which breaks only an arbitrary element is visible, I believe.
