### ISSUE TITLE
unsupport find_elements_by_ios_nspredicate

### ISSUE THREAD

**Issue by wangtao169447** [appium/python-client#194]
unsupport find_elements_by_ios_nspredicate function.

Besides, i found that, sometimes, i have a button, named '返回',however, when i run this kind of commands: self.driver.find_elements_by_name("返回"), which retrun []

thanks。

**Comment by KazuCocoa** [comment]
Do you mean you'd like to know Appium specific API reference?
For example: https://github.com/appium/python-client#finding-elements-by-ios-predicates

**Comment by wangtao169447** [comment]
@KazuCocoa 
thanks for help!
i mean ,i can not find this kind of function:self.driver.find_elements_by_ios_predicate()

**Comment by KazuCocoa** [comment]
Which version of python client did @wangtao169447  use?

**Comment by ki4070ma** [comment]
Since no response
