### ISSUE TITLE
Standard Selenium orientation command does not support all orientations for WDA iOS 

### ISSUE THREAD

**Issue by marcin1337** [appium/python-client#199]
Currently the appium python client uses the default selenium implementation for orientation which only accepts either PORTRAIT or LANDSCAPE.

iOS for instance supports many more types of orientation specified in [WDA](https://github.com/facebook/WebDriverAgent/blob/06e20ba19075152f37fd58cdef2043ba151acdd9/WebDriverAgentLib/Commands/FBOrientationCommands.m):

```
      FBWDOrientationValues.portrait : @(UIDeviceOrientationPortrait),
      FBWDOrientationValues.portraitUpsideDown : @(UIDeviceOrientationPortraitUpsideDown),
      FBWDOrientationValues.landscapeLeft : @(UIDeviceOrientationLandscapeLeft),
      FBWDOrientationValues.landscapeRight : @(UIDeviceOrientationLandscapeRight),
```

Would it be possible to override the default selenium orientation command and remove the restriction of setting only Portrait or Landscape mode 

I understand if this also will require a separate issue with Appium Server itself

**Comment by mastrzyz** [comment]
@mykola-mokhnach How would I go ahead and help fix this issue?

**Comment by mykola-mokhnach** [comment]
Upside down orientation is anyway broken with XCTest. You'll need to fix XCTest first (or implemnt proper workarounds)

**Comment by KazuCocoa** [comment]
this isn't client side issue so close this
