### ISSUE TITLE
TouchAction clicks not affected by offset of WebView

### ISSUE THREAD

**Issue by jacobweber** [appium/python-client#207]
I have a hybrid iOS app using Cordova, with the statusbar plugin, and StatusBarOverlaysWebView=false. This means that the UIWebView's top Y coordinate is 20 (or 40, depending on the height of the status bar).

But when I do: `TouchAction(driver).press(el).release().perform()`
or `TouchAction(driver).press(None, x, y).release().perform()`

it actually clicks 20 pixels above where it's supposed to. It doesn't seem to be accounting for the offset of the web view.

I had to do something like this:
```
driver.switch_to.context(driver.contexts[0])
webview = driver.find_element_by_ios_predicate('type = "XCUIElementTypeWebView"')
driver.switch_to.context(driver.contexts[1])

def click(el):
    x = el.location['x'] + webview.offset['x']
    y = el.location['y'] + webview.offset['y']
    TouchAction(driver).press(None, x, y).release().perform()
```

**Comment by KazuCocoa** [comment]
This depends on appium/XCUITest side. W3C action might help as well.
(But I don't know how Cordova is iOS framework/WebInspector friendly.)
