### ISSUE TITLE
Python appium android update

### ISSUE THREAD

**Issue by langme** [appium/python-client#211]
Why  `find_element_by_android_uiautomator("new UiScrollable(new UiSelector().scrollable(true).instance(0))."
                                                   "scrollIntoView(new UiSelector().textContains(\"" + text +
                                                   "\").instance(0))")` doesn't work since i have updated appium ?

**Comment by KazuCocoa** [comment]
@langme 
Could you attach logs to understand what kind of `doesn't work`?
Both server side and client side are helpful for us.

**Comment by langme** [comment]
'An element could not be located on the page using the given search parameters.'

**Comment by KazuCocoa** [comment]
Thanks! but I could predict the request couldn't find the element from the data.

Could you give us the full logs and hopefully get the source of the page.

**Comment by KazuCocoa** [comment]
In my experience, the method depends on devices or OS versions, especially OS versions.
And if the scroll view is nested one, we should change a number of `instance(0)` like `instance(1)`.
