### ISSUE TITLE
double_tap not working on Appium 1.8.0

### ISSUE THREAD

**Issue by Veeenz** [appium/python-client#218]
Hello all, I got a problem with this method: actions.double_tap()
As I can see on the documentation https://appium.io/docs/en/commands/interactions/touch/double-tap/ there is _new_(?) import. TouchAction**s**

I cannot find anywhere this library. I tried with TouchAction() instead (it could be a typing error...) but no way to make it working.
Any suggeston? Inside TouchAction() there is not double_tap method.
Isn't it implemented?

Thanks in advance

**Comment by mykola-mokhnach** [comment]
Double tap might be emulated by setting the `count` value in tap `method` to 2.

**Comment by zhisays** [comment]
e.. neither  tap nor press-release worked..

**Comment by KazuCocoa** [comment]
As the link in the double_tap page, Python calls https://seleniumhq.github.io/selenium/docs/api/py/webdriver/selenium.webdriver.common.touch_actions.html

It appreciates if you could attach appium server log since it is difficult to assume the cause

**Comment by ki4070ma** [comment]
Not so active.
Please re-open when appium server log attached.
