### ISSUE TITLE
Does push_file really push file into the container of iOS Device(not simulator?)

### ISSUE THREAD

**Issue by x-yang11** [appium/python-client#219]
I'm using driver.push_file to push test data into device。

My code is
```
driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
driver.execute_script('mobile: alert', {'action': 'accept'})
time.sleep(5)
driver.close_app()
for imageid in range(35):
	content = open('/path/to/testData/image_%d.txt' % imageid, 'rb').read()
	encoded_file = base64.b64encode(content)
	driver.push_file('Documents/arlog/testData/image_%d.txt'%imageid, encoded_file.decode())
```
 
log is as follows:
```
[HTTP] --> POST /wd/hub/session/2cd1c784-e16b-4e56-bc60-1e66670f9706/appium/device/push_file
[HTTP] {"path":"Documents/arlog/testData/image_0.txt","data":"***..."
[debug] [MJSONWP] Calling AppiumDriver.pushFile() with args: ["Documents/arlog/testData/image_0.txt","***...
[debug] [XCUITest] Executing command 'pushFile'
[debug] [XCUITest] Starting ifuse with args '-u,myudid,/var/folders/bx/rknk38vj3p1f5gvyy44qxkzw0000gn/T/2018421-50322-1voe8wx.m4yd'...
[debug] [MJSONWP] Responding to client with driver.pushFile() result: null
[HTTP] <-- POST /wd/hub/session/2cd1c784-e16b-4e56-bc60-1e66670f9706/appium/device/push_file 200 386 ms - 76
```
And then, I downloaded the container of my app from Xcode-Windows-Device and Simulators...。However, I could not find any '/Documents/arlog/image_*.txt' in the path. But, when I use driver.pull_file('/Documents/arlog/image_*.txt' ), I can see the right data in log window of appium-server.

So, was my file really pushed into the device ? or just push into somewhere into my mac?

**Comment by jlipps** [comment]
Hi @x-yang11 this issue doesn't appear to be related to the python client specifically but rather to the implementation of push/pull file on the Appium server. Closing here; mind adding a new issue at the Appium issue tracker?
