### ISSUE TITLE
Appium Python Client doesn't see Appium Server

### ISSUE THREAD

**Issue by oskonstantinov** [appium/python-client#226]
# The problem

Try to run simple example code, but when i run it, nothing happens in Appium Server log. 

## Environment

* IDE: PyCharm
* Python version: 3.6.5
* Appium version: 1.6.2, also try 1.5.0
* Appium Python Client version: 0.26, also try 0.20 - 0.25
* Desktop OS/version used to run Appium: Windows 7 x64
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Nexus 5 on emulator Genymotion

## Details

Appium server run at localhost, Genymotion device also run. Appium server see emulator "from themself", when i start Inspector Session. 
Try to run my code, PyCharm console return:
D:\PythonAppiumAutomation\venv\Scripts\python.exe D:/PythonAppiumAutomation/Test.py
Process finished with exit code 0

Appium server log is clear -> IDE or code not see server. Code is very simple, so I doubt that problem in code. I try reinstall another version of the Appium Server and Appium Python Client, but it didn't help.

## Code To Reproduce Issue:

```
import unittest
from appium import webdriver

class Test(unittest.TestCase):

    def setUp(self):
        desired_caps = {}
        desired_caps['platformName'] = 'Android'
        desired_caps['deviceName'] = 'AndroidTestDevice'
        desired_caps['platformVersion'] = '6.0'
        desired_caps['automationName'] = 'Appium'
        desired_caps['appPackage'] = 'org.wikipedia'
        desired_caps['appActivity'] = '.main.MainActivity'
        desired_caps['app'] = 'D:/PythonAppiumAutomation/apks/org.wikipedia.apk'

        self.driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)

    def tearDown(self):
        self.driver.quit()

    def test(self):
        print("Test Run")


```

**Comment by KazuCocoa** [comment]
Can you access the server via any browser?
For example, when you open `http://127.0.0.1:4723/wd/hub` via chrome, what logs can you see?
In my case, I could see below.

![image](https://user-images.githubusercontent.com/5511591/41472423-5c1fb1cc-70f1-11e8-98c3-3af914d8d550.png)


```
[Appium] Welcome to Appium v1.8.0-beta (REV 27df40944e2adebfa17822185c1feb6a2f41e3e7)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub
[HTTP] {}
[debug] [HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- GET /wd/hub 404 13 ms - 49
[HTTP]
[HTTP] <-- GET /favicon.ico 200 4 ms - 1150
[HTTP]
[HTTP] <-- GET /favicon.ico 200 0 ms - 1150
[HTTP]
```

**Comment by oskonstantinov** [comment]
Ok, i try it and get this one:

![fc6947773e](https://user-images.githubusercontent.com/23136372/41472922-82478c20-70c0-11e8-9519-c84d3aefa527.jpg)

**Comment by KazuCocoa** [comment]
Can you see `Test Run`output with the below?
```
def setUp(self):
    desired_caps = {}
    desired_caps['platformName'] = 'Android'
    desired_caps['deviceName'] = 'AndroidTestDevice'
    desired_caps['platformVersion'] = '6.0'
    desired_caps['automationName'] = 'Appium'
    desired_caps['appPackage'] = 'org.wikipedia'
    desired_caps['appActivity'] = '.main.MainActivity'
    desired_caps['app'] = 'D:/PythonAppiumAutomation/apks/org.wikipedia.apk'

    print("Test Run")
    self.driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)
```

I'd like to know if the script reaches `self.driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)` or not.

---

Your code looks similar to https://github.com/appium/python-client/blob/master/test/functional/android/appium_tests.py . So, if your code reaches the `webdriver.Remote`, I anticipate your code works...

**Comment by oskonstantinov** [comment]
Unfortunately, no result. Try your variant and output the same:
```
D:\PythonAppiumAutomation\venv\Scripts\python.exe D:/PythonAppiumAutomation/FirstTest.py

Process finished with exit code 0
```

**Comment by KazuCocoa** [comment]
ah, it means the `FirstTest.py` doesn't work.
Did you call `__main__` like below? it's your python script issue.

```
if __name__ == "__main__":
    suite = unittest.TestLoader().loadTestsFromTestCase(AppiumTests)
    unittest.TextTestRunner(verbosity=2).run(suite)
```

https://github.com/appium/python-client/blob/master/test/functional/android/appium_tests.py#L270


https://docs.python.org/3/library/unittest.html#basic-example

**Comment by oskonstantinov** [comment]
Yep, it's the root of problem! Big thank you.
