### ISSUE TITLE
Can't run tests with Xcode 10.0

### ISSUE THREAD

**Issue by mihmonah** [appium/python-client#229]
After installing new beta macOS Mojave (10.14 Beta) and Xcode Version 10.0 beta 3 (10L201y) for trying `-parallel-testing-enabled` flag pytest gives the next output:

`E       selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Xcode version '0.0'. Support for Xcode 0.0 is not supported. Please upgrade to version 7.3 or higher`

I think it could be related to [this issue](https://github.com/appium/appium-xcode/pull/36), but I don't know how [appium-xcode repo](https://github.com/appium/appium-xcode) is correlated with [python-client repo](https://github.com/appium/python-client).
My current version of Appium Python Client is from today master (`commit 97cf837abe308044242bfd9950f2cbd5a48c7daf`)

**Comment by KazuCocoa** [comment]
What Appium server did you use?
Did you try out `appium@beta`?

**Comment by imurchie** [comment]
This is an issue with the Appium server. You need to install the latest beta (`npm uninstall -g appium && npm install -g appium@beta`) since the release came out before Xcode 10.

**Comment by mihmonah** [comment]
@imurchie thanks for your comment, it was useful advice!

But after building app with command
`xcodebuild -workspace $WORKSPACE -scheme $SCHEME -configuration AdHoc -derivedDataPath $DERIVEDIR -sdk iphonesimulator12.0 -destination "id=$UDID" clean build -parallel-testing-enabled YES -maximum-concurrent-test-simulator-destinations 2 -parallel-testing-worker-count 2`
another error appears:

`ios_tests/tests/test_send_message.py::test_send_message [XCUITest]` **Error: Command 'osascript -e 'tell application "System Events" to count processes whose bundle identifier is "com.apple.iphonesimulator"'' exited with code 1**
`[XCUITest]     at ChildProcess.<anonymous> (/Users/mikhailmonakhov/.nvm/versions/node/v8.11.1/lib/node_modules/appium/node_modules/teen_process/lib/exec.js:94:19)
[XCUITest]     at emitTwo (events.js:126:13)
[XCUITest]     at ChildProcess.emit (events.js:214:7)
[XCUITest]     at maybeClose (internal/child_process.js:925:16)
[XCUITest]     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
[MJSONWP]` **Encountered internal error running command: Error: Command 'osascript -e 'tell application "System Events" to count processes whose bundle identifier is "com.apple.iphonesimulator"'' exited with code 1**
`[MJSONWP]     at ChildProcess.<anonymous> (/Users/mikhailmonakhov/.nvm/versions/node/v8.11.1/lib/node_modules/appium/node_modules/teen_process/lib/exec.js:94:19)
[MJSONWP]     at emitTwo (events.js:126:13)
[MJSONWP]     at ChildProcess.emit (events.js:214:7)
[MJSONWP]     at maybeClose (internal/child_process.js:925:16)
[MJSONWP]     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
ERROR`

But I updated bundle ID in `updatedWDABundleId='{}'.format(MYBANDLEID)` of `desired_capabilities` for driver.
May be for parallel execution of tests via new Xcode some new options of `desired_capabilities` variable are needed (like for xcodebuild command)?

**Comment by imurchie** [comment]
This is a server problem. Please create an issue, with all required information, in the server repository: https://github.com/appium/appium/issues/new

**Comment by mihmonah** [comment]
@imurchie thanks for answer!
