### ISSUE TITLE
'WebDriver' object has no attribute 'find_element_by_image'

### ISSUE THREAD

**Issue by messianic** [appium/python-client#233]
Unable to use find_element_by_image() locator.
Appium client : python
Appium version: 1.8.0
Platform: Android 
Platform Versrion: 7.1.1
Device: Nexus_5X (emulator)

[python_findByImage.log](https://github.com/appium/python-client/files/2231745/python_findByImage.log)

**Comment by KazuCocoa** [comment]
Which client version do you use?

**Comment by messianic** [comment]
@KazuCocoa Its the latest one. I installed it using pip.

**Comment by KazuCocoa** [comment]
Did you call the method with `driver.find_element_by_image(self, ....)`?

```
driver.find_element_by_image(self, '/Users/ishansaini/Documents/python_appium/python-client/test/functional/android/find_by_image_success.png', 5)
```

What about getting rid of `self` from there? @messianic 

---

BTW, the method will change like https://github.com/appium/python-client/pull/236
