### ISSUE TITLE
not support endpoint keys

### ISSUE THREAD

**Issue by robin-xl** [appium/python-client#242]
please supoort endpoint `/keys`

`/wd/hub/session/:sessionId?/keys`

**Comment by KazuCocoa** [comment]
Do you mean support the command with W3C protocol? Since the command probably works with `send_keys` like below.
https://github.com/SeleniumHQ/selenium/blob/24aed0d781cd34c93b1d8392c24bb7d9203cd07e/py/selenium/webdriver/common/action_chains.py#L343-L356

According to the above URL, it works with MJONWP. You can force it works as MJONWP with `forceMjsonwp: true` capability.

**Comment by robin-xl** [comment]
@KazuCocoa yeah, i know this class `ActionChains `, when  switch to webview, i use it to type content in web page.
 But in my scene, test ios app, when type content on `NATIVE_APP` not webview , the endpoint `send_keys`  will find system keyboard appear, but our app use customer keyboard, so it not work for me. in here [wda endpoint](
https://github.com/appium/appium-xcuitest-driver/blob/master/docs/endpoints-wda.md) has the endpoint `/wd/hub/session/{sessionId}/keys` will be proxy to `/wda/keys` on appium side, this type mode work for me.
So,i need to call `/wd/hub/session/:sessionId?/keys`it is mean to support command with w3c protocol.

now i must inject this endpoint by
```
# inject endpoint
# driver  type: appium.webdriver.Remote
getattr(driver.command_executor, '_commands').update({'keys': ('POST', '/session/$sessionId/keys')})

# use
data = {'id': _web_element.id,'value': [content] }
driver.execute('keys', data)
```

BTW, `forceMjsonwp: true` not support on appium capability, can you point where to set it.

**Comment by robin-xl** [comment]
yep, the method `send_keys` in `WebElement` not work ,the appium log 
```
2018-08-16 14:11:20:645 - info: [debug] [JSONWP Proxy] Matched '/element' to command name 'findElement'
2018-08-16 14:11:20:645 - info: [debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:21106/session/811B3984-4833-4BBC-8C81-76AD9ABC1D02/element] with body: {"using":"class name","value":"XCUIElementTypeKeyboard"}
2018-08-16 14:11:20:723 - info: [debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"class name","value":"XCUIElementTypeKeyboard","description":"unable to find an element"},"sessionId":"811B3984-4833-4BBC-8C81-76AD9ABC1D02","status":7}
2018-08-16 14:11:20:724 - info: [debug] [MJSONWP] Matched JSONWP error code 7 to NoSuchElementError
```
show it alse need to find `//XCUIElementTypeKeyboard `, but in `/selenium/webdriver/remore/remote_connection.py` i find the `Command.SEND_KEYS_TO_ACTIVE_ELEMENT`, it's what i want , this endpoint can type content without keyboard, maybe its working principle is different from `send_keys` and `set_value`.

**Comment by mykola-mokhnach** [comment]
XCTest in general does not allow typing without keyboard. It is a framework limitation that you can only type into some field and cannot sent arbitrary key codes into the app.
