### ISSUE TITLE
WebDriver Exception when Background

### ISSUE THREAD

**Issue by HeEveret** [appium/python-client#244]
We have a recurring error testing android. When i do "self.driver.background_app(3)" sometimes happends a WebDriverException. 

We have to do background to update de xml tree of uiAutomator. If we dont do that, cant wait any element there because never appear.

My question are two:
- can we do another thing to refresh the xml tree?
- what can we do to avoid WebDriverExceptions? good practices or something like that...

**Comment by KazuCocoa** [comment]
Could you attach the log including the issue case?
`WebDriverException` is a general exception. We'd like to know more details.
If you also can get logcat, it will also help us.

**Comment by HeEveret** [comment]
@KazuCocoa @mykola-mokhnach 

Thanks so much for your support. Sorry if I cannot post comlpete code, I'm not allowed to do that due to IP issues.

In any case, after some further testing, I've realized that somehow the problem is related to the timing when doing background. So my previous failing code was something like this:

```
self.driver.background_app(3)
time.sleep(3)
makeSwipe("DOWN") # This swipes down the screen
time.sleep(3)
self.driver.background_app(3)
```

Making the background_app(3) delivered the error. But when I replaced that 3 by 1, the problem does not arise:

```
self.driver.background_app(1)
time.sleep(3)
makeSwipe("DOWN")  # This swipes down the screen
time.sleep(3)
self.driver.background_app(1)
```

This is kind of mystery for me. Why can fail if I set a timeout of 3 when doing a background?

Sorry I've lost the complete log of that session, I was able to save these lines however:

> '10:58:29:     DEBUG: Swipping to DOWN direction with 500 ms of duration
> 10:58:29: SWIPE FAIL!
> ('Unexpected error:', <class 'selenium.common.exceptions.WebDriverException'>)

No more info about the WebDriverException. I'll try to go on, but if you have any clue why this occurs, maybe I can plan my tests some other way.

Do you know if there's any other way to refresh the XML tree? Could this refresh be related to my issue? Is there any way to properly use background not to fail?

Thanks so much for your kind help.

**Comment by mykola-mokhnach** [comment]
@HeEveret 

I've prepared a [PR](https://github.com/appium/appium-uiautomator2-server/pull/183) 
Please check out it locally, build and deploy to your appium installation. The Appium itself should be at beta version. The original APKs to replace should be located at 

/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk
/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.13.0.apk

if you're on MacOS

**Comment by mykola-mokhnach** [comment]
The idea behind this PR is to refresh the accessibility tree each time before performing element lookup,, so you don't have to invent workarounds like backgrounding the app in order to have the tree always up to date.

**Comment by KazuCocoa** [comment]
```
$ git clone https://github.com/appium/appium-uiautomator2-server
$ cd appium-uiautomator2-server
$ gradle clean assembleServerDebug assembleServerDebugAndroidTest
# copy builded apks
$ cp app/build/outputs/apk/androidTest/server/debug/appium-uiautomator2-server-debug-androidTest.apk /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/
$ cp /Users/kazuaki/GitHub/appium-uiautomator2-server/app/build/outputs/apk/server/debug/appium-uiautomator2-server-v1.14.0.apk /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/
$ rm /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v1.13.0.apk # not necessary
```

What about above? @HeEveret

**Comment by HeEveret** [comment]
@KazuCocoa Thanks for your instructions. I'm trying to compile in Windows 10, so the paths are different than linux/mac. In any case, I followed your suggested steps, and I cannot find the compiled apks. Here is the complete compilation output:

-----------

C:\Users\everet\appium-uiautomator2-server (master -> origin) (appium-uiautomator2-server@1.14.0)
λ gradle clean assembleServerDebug assembleServerDebugAndroidTest

> Configure project :app
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
Configuration 'testCompile' in project ':app' is deprecated. Use 'testImplementation' instead.
Configuration 'androidTestCompile' in project ':app' is deprecated. Use 'androidTestImplementation' instead.
Checking the license for package Android SDK Build-Tools 26.0.2 in C:\Users\everet\AppData\Local\Android\Sdk\licenses
License for package Android SDK Build-Tools 26.0.2 accepted.
Preparing "Install Android SDK Build-Tools 26.0.2 (revision: 26.0.2)".
"Install Android SDK Build-Tools 26.0.2 (revision: 26.0.2)" ready.
Installing Android SDK Build-Tools 26.0.2 in C:\Users\everet\AppData\Local\Android\Sdk\build-tools\26.0.2
"Install Android SDK Build-Tools 26.0.2 (revision: 26.0.2)" complete.
"Install Android SDK Build-Tools 26.0.2 (revision: 26.0.2)" finished.
Checking the license for package Android SDK Platform 24 in C:\Users\everet\AppData\Local\Android\Sdk\licenses
License for package Android SDK Platform 24 accepted.
Preparing "Install Android SDK Platform 24 (revision: 2)".
"Install Android SDK Platform 24 (revision: 2)" ready.
Installing Android SDK Platform 24 in C:\Users\everet\AppData\Local\Android\Sdk\platforms\android-24
"Install Android SDK Platform 24 (revision: 2)" complete.
"Install Android SDK Platform 24 (revision: 2)" finished.
Download https://jcenter.bintray.com/com/squareup/okhttp/okhttp/2.5.0/okhttp-2.5.0.pom
Download https://jcenter.bintray.com/com/jayway/jsonpath/json-path/0.8.1/json-path-0.8.1.pom
Download https://jcenter.bintray.com/io/netty/netty-all/4.0.41.Final/netty-all-4.0.41.Final.pom
Download https://jcenter.bintray.com/com/squareup/okhttp/parent/2.5.0/parent-2.5.0.pom
Download https://jcenter.bintray.com/com/jayway/jsonpath/json-path-parent/0.8.1/json-path-parent-0.8.1.pom
Download https://jcenter.bintray.com/io/netty/netty-parent/4.0.41.Final/netty-parent-4.0.41.Final.pom
Download https://jcenter.bintray.com/org/sonatype/oss/oss-parent/5/oss-parent-5.pom
Download https://jcenter.bintray.com/commons-lang/commons-lang/2.6/commons-lang-2.6.pom
Download https://jcenter.bintray.com/net/minidev/json-smart/1.1.1/json-smart-1.1.1.pom
Download https://jcenter.bintray.com/org/apache/commons/commons-parent/17/commons-parent-17.pom
Download https://jcenter.bintray.com/net/minidev/parent/1.1.1/parent-1.1.1.pom
Download https://jcenter.bintray.com/org/apache/apache/7/apache-7.pom
Download https://jcenter.bintray.com/com/squareup/okio/okio/1.6.0/okio-1.6.0.pom
Download https://jcenter.bintray.com/com/squareup/okio/okio-parent/1.6.0/okio-parent-1.6.0.pom
Download https://jcenter.bintray.com/junit/junit/4.12/junit-4.12.pom
Download https://jcenter.bintray.com/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom
Download https://jcenter.bintray.com/org/hamcrest/hamcrest-parent/1.3/hamcrest-parent-1.3.pom
Download https://jcenter.bintray.com/org/robolectric/android-all/7.1.0_r7-robolectric-0/android-all-7.1.0_r7-robolectric-0.pom
Download https://jcenter.bintray.com/org/robolectric/android-all/7.1.0_r7-robolectric-0/android-all-7.1.0_r7-robolectric-0.jar
Download https://jcenter.bintray.com/com/jayway/jsonpath/json-path/0.8.1/json-path-0.8.1.jar
Download https://jcenter.bintray.com/net/minidev/json-smart/1.1.1/json-smart-1.1.1.jar
Download https://jcenter.bintray.com/com/squareup/okhttp/okhttp/2.5.0/okhttp-2.5.0.jar
Download https://jcenter.bintray.com/io/netty/netty-all/4.0.41.Final/netty-all-4.0.41.Final.jar
Download https://jcenter.bintray.com/com/squareup/okio/okio/1.6.0/okio-1.6.0.jar
Download https://jcenter.bintray.com/junit/junit/4.12/junit-4.12.jar
Download https://jcenter.bintray.com/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
Download https://jcenter.bintray.com/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar

> Task :app:compileServerDebugJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Download https://jcenter.bintray.com/org/ccil/cowan/tagsoup/tagsoup/1.2/tagsoup-1.2.pom
Download https://jcenter.bintray.com/javax/inject/javax.inject/1/javax.inject-1.pom
Download https://jcenter.bintray.com/com/squareup/javawriter/2.1.1/javawriter-2.1.1.pom
Download https://jcenter.bintray.com/org/hamcrest/hamcrest-library/1.3/hamcrest-library-1.3.pom
Download https://jcenter.bintray.com/com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.pom
Download https://jcenter.bintray.com/org/hamcrest/hamcrest-integration/1.3/hamcrest-integration-1.3.pom
Download https://jcenter.bintray.com/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.pom
Download https://jcenter.bintray.com/net/java/jvnet-parent/3/jvnet-parent-3.pom
Download https://jcenter.bintray.com/org/hamcrest/hamcrest-integration/1.3/hamcrest-integration-1.3.jar
Download https://jcenter.bintray.com/com/squareup/javawriter/2.1.1/javawriter-2.1.1.jar
Download https://jcenter.bintray.com/javax/inject/javax.inject/1/javax.inject-1.jar
Download https://jcenter.bintray.com/org/ccil/cowan/tagsoup/tagsoup/1.2/tagsoup-1.2.jar
Download https://jcenter.bintray.com/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar
Download https://jcenter.bintray.com/com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.jar
Download https://jcenter.bintray.com/org/hamcrest/hamcrest-library/1.3/hamcrest-library-1.3.jar
warning: Ignoring InnerClasses attribute for an anonymous inner class
(org.ccil.cowan.tagsoup.Parser$1) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 4m 37s
51 actionable tasks: 49 executed, 2 up-to-date

----------

I see some warnings, but in the end the  compilation was successful. I've looked for the build directory, but I cannot find it:

> C:\Users\everet\appium-uiautomator2-server (master -> origin) (appium-uiautomator2-server@1.14.0)
> λ dir
>  El volumen de la unidad C es Windows
>  El número de serie del volumen es: E846-03FA
> 
>  Directorio de C:\Users\everet\appium-uiautomator2-server
> 
> 21/08/2018  10:53    <DIR>          .
> 21/08/2018  10:53    <DIR>          ..
> 21/08/2018  10:43               121 .gitignore
> 21/08/2018  11:12    <DIR>          .gradle
> 21/08/2018  10:43                43 .npmignore
> 21/08/2018  10:43                18 .npmrc
> 21/08/2018  10:43             3.300 .travis.yml
> 21/08/2018  10:43    <DIR>          app
> 21/08/2018  10:43             1.431 build.gradle
> 21/08/2018  10:43    <DIR>          doc
> 21/08/2018  10:43    <DIR>          gradle
> 21/08/2018  10:43               926 gradle.properties
> 21/08/2018  10:43             5.131 gradlew
> 21/08/2018  10:43             2.404 gradlew.bat
> 21/08/2018  10:43               185 gulpfile.js
> 21/08/2018  10:43               373 index.js
> 21/08/2018  10:43            10.483 LICENSE
> 21/08/2018  10:43             1.570 package.json
> 21/08/2018  10:43             1.883 README.md
> 21/08/2018  10:43                16 settings.gradle
>               14 archivos         27.884 bytes
>                6 dirs  148.781.969.408 bytes libres




> C:\Users\everet\appium-uiautomator2-server (master -> origin) (appium-uiautomator2-server@1.14.0)
> λ dir app
>  El volumen de la unidad C es Windows
>  El número de serie del volumen es: E846-03FA
> 
> 
>  Directorio de C:\Users\everet\appium-uiautomator2-server\app
> 
> 21/08/2018  10:43    <DIR>          .
> 21/08/2018  10:43    <DIR>          ..
> 21/08/2018  10:43                 8 .gitignore
> 21/08/2018  10:43             4.110 build.gradle
> 21/08/2018  10:43    <DIR>          gradle
> 21/08/2018  10:43             5.131 gradlew
> 21/08/2018  10:43             2.404 gradlew.bat
> 21/08/2018  10:43               443 local.properties
> 21/08/2018  10:43               661 proguard-rules.pro
> 21/08/2018  10:43    <DIR>          src
>                6 archivos         12.757 bytes
>                4 dirs  148.781.969.408 bytes libres


For sure I'm doing something wrong... Sorry, I don't have any experience with gradle, so maybe it's just a flag, but after some googling I cannot find which one. I'd appreciate any help to follow your steps.

Thanks!

**Comment by KazuCocoa** [comment]
@HeEveret
ah..
I'm not familiar with Windows10... https://developer.android.com/studio/build/building-cmdline probably helps the case...

Anyway, if you can find `appium-uiautomator2-server-debug-androidTest.apk` and `appium-uiautomator2-server-v1.14.0.apk` somewhere in `appium-uiautomator2-server`, they are, I believe.

**Comment by QA2Dev** [comment]
@KazuCocoa I'm not able to build, getting following error "A problem occurred evaluating root project 'appium-uiautomator2-server'.
> Cannot add task 'clean' as a task with that name already exists.", Can you help on resolving this issue

**Comment by KazuCocoa** [comment]
@QA2Dev 
What about `./gradlew assembleServerDebug assembleServerDebugAndroidTest`?
If it's the first time to build in `appium-uiautomator2-server`, we don't need to run `clean`.

I haven't seen the gradle issue in the repository. 🤔

**Comment by QA2Dev** [comment]
@KazuCocoa when I ran "assembleServerDebug assembleServerDebugAndroidTest",still i'm getting the same error because of the task in the gradle script, "task clean(type: Delete) {
    delete rootProject.buildDir
}"

**Comment by KazuCocoa** [comment]
What about getting rid of https://github.com/appium/appium-uiautomator2-server/blob/4d3ac64025296bd314709df98ba8071364a9c210/build.gradle#L42-L44 on your local and run again? @QA2Dev

**Comment by QA2Dev** [comment]
@KazuCocoa This time, I have got another issue as follows "A problem occurred configuring project ':app'.
> The 'java' plugin has been applied, but it is not compatible with the Android plugins."

**Comment by QA2Dev** [comment]
java version "1.8.0_171"

**Comment by KazuCocoa** [comment]
What about adding below lines?

```
android {
    ...
    compileOptions {
        encoding = 'UTF-8'
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```

Below is an example where `compileOptions` is.
https://stackoverflow.com/questions/26861011/android-compile-error-java-plugin-has-been-applied-not-compatible-with-android


If you have no android build environment, https://developer.android.com/studio/install also help building the environment.

**Comment by QA2Dev** [comment]
@KazuCocoa After adding the lines **android** closure as advised, i'm getting the following issue, A problem occurred evaluating root project 'appium-uiautomator2-server'.
> Could not find method android() for arguments [build_86x8jbd7xmzkd3lowmmvcrxvo$_run_closure1@5ffadc25] on root project 'appium-uiautomator2-server' of type org.gradle.api.Project.

**Comment by QA2Dev** [comment]
Android environment is setup in the system as shown below

HW1908:appium-uiautomator2-server ctl-user$ adb version
Android Debug Bridge version 1.0.40
Version 4797878
Installed as /Users/ctl-user/android-sdk-macosx/platform-tools/adb

**Comment by QA2Dev** [comment]
Gradle script looks like follows now

// Top-level build file where you can add configuration options common to all sub-projects/modules.


import groovy.json.JsonSlurper
import org.apache.tools.ant.taskdefs.condition.Os

buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

android {

    compileOptions {
        encoding = 'UTF-8'
        sourceCompatibility  = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
}

allprojects {
    if (Os.isFamily(Os.FAMILY_WINDOWS)) {

        /**
         * In Windows OS, gradle can't build the project
         * if the project path is containing more than 240 characters.
         * As a temporary fix, changing the 'buildDir' to 'windowsBuildDir' property in package.json file
         * if the 'windowsBuildDir' property not available it will build the apks in the default value
         * of 'buildDir' which is current repo.
         * refer: https://code.google.com/p/android/issues/detail?id=187430
         */
        def packagejson = new JsonSlurper().parseText(new File('./package.json').text)
        if (packagejson.windowsBuildDir) {
            buildDir = packagejson.windowsBuildDir + "/${rootProject.name}/${project.name}/build"
        }
    }
    repositories {
        jcenter()
        google()
    }
}

/*
task clean(type: Delete) {
    delete rootProject.buildDir
}*/

**Comment by KazuCocoa** [comment]
What about moving `android` section in https://github.com/appium/appium-uiautomator2-server/blob/master/app/build.gradle ?
You can see the same `android` section in the file.

**Comment by QA2Dev** [comment]
@KazuCocoa Even after moving the android section given in the link to the gradle script , i'm facing the same issueA problem occurred evaluating root project 'appium-uiautomator2-server'.
> Could not find method android() for arguments [build_86x8jbd7xmzkd3lowmmvcrxvo$_run_closure1@1917cea0] on root project 'appium-uiautomator2-server' of type org.gradle.api.Project.

**Comment by KazuCocoa** [comment]
@QA2Dev 
Hm... Sorry, I can't advise any more without diging into your environment. Something happens in your gradle environment, I anticipate.

Below is the link to apks which is current master, 1.16.0. Could you download them and try out following 
https://github.com/appium/python-client/issues/244#issuecomment-414499267 ?

https://www.dropbox.com/sh/k4etx7f9bkissg8/AABOPSaObBacweSIc3_J77vqa?dl=0

I'll delete them a couple of days later.

**Comment by QA2Dev** [comment]
@KazuCocoa Thank you for your help, let me try with the apps you shared with me and confirm you

**Comment by QA2Dev** [comment]
Hi @KazuCocoa , may I know does the the apks you shared with me is the latest with the patches (commited by @mykola-mokhnach )applied as follow i.e. https://github.com/appium/appium-uiautomator2-server/pull/184.
I'm supposed to check those patches and confirm to @mykola-mokhnach

**Comment by KazuCocoa** [comment]
Updated. The version number is 1.15.0. Try download both apks and replace your local's ones with them.
https://www.dropbox.com/sh/k4etx7f9bkissg8/AABOPSaObBacweSIc3_J77vqa?dl=0
@QA2Dev

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-uiautomator2-server/pull/183 has been merged.
The original issue, https://github.com/appium/python-client/issues/244#issuecomment-414616633 ,  was hopefully alleviate.

**Comment by HeEveret** [comment]
> The idea behind this PR is to refresh the accessibility tree each time before performing element lookup,, so you don't have to invent workarounds like backgrounding the app in order to have the tree always up to date.

I am updating Appium to 1.9.1 and I have the same problem that when i used 1.7.1. Could you tell me what is the most stable version of Appium-Python-Client, Appium Server, Appium Desktop, selenium, etc  or some place where i can check it?
