### ISSUE TITLE
Run test in parallel as an example for parallel running

### ISSUE THREAD

**Issue by KazuCocoa** [appium/python-client#247]
Like a Ruby client
https://github.com/appium/ruby_lib/tree/master/ios_tests

**Comment by KazuCocoa** [comment]
An example of a running test in parallel by `pytest`
https://github.com/KazuCocoa/appium/commit/98034eb716d526fc54d7b3fac5acd249cd5fac9d

**Comment by jumois** [comment]
@KazuCocoa is there way to parallelize the deployment of test application and WebDriverAgentRunner when running tests in parallel on multiple real iOS devices? I'm creating new sessions on separate threads but Appium installs my test app and WDA synchronously on each iOS device.

**Comment by KazuCocoa** [comment]
If you launch multiple Appium servers on your machine, you probably can. @jumois 
The current example is launching one Appium server. Don't forget to handle multiple port numbers correctly in Python side to avoid conflicts, then.
