### ISSUE TITLE
Add support for driver.perform(TouchAction)

### ISSUE THREAD

**Issue by jumois** [appium/python-client#253]
## The problem

Appium documentation states that Appium clients have support for executing TouchActions using the driver object. This doesn't seem to apply to python client.

See:
https://appium.io/docs/en/writing-running-appium/touch-actions/

> Appium clients also allow one to directly execute a TouchAction through the driver object, rather than calling the perform event on the TouchAction object.
> 
> In pseudocode, both of the following are equivalent:
> 
> TouchAction().tap(el).perform()
> 
> driver.perform(TouchAction().tap(el))
> 

## Actual result
`AttributeError: 'WebDriver' object has no attribute 'perform'`

**Comment by KazuCocoa** [comment]
Thanks. the part is not Python, I believe...

https://appium.io/docs/en/commands/interactions/touch/touch-perform/ is the `perform` in Python client and other clients. Let me remove the part if we have no such code

**Comment by KazuCocoa** [comment]
I've updated the documentation. Thanks again :)

**Comment by nrvaidya2020** [comment]
Hi,

 Vaidya here from Hyderabad, India.

Appium with Python on Android platform, any way to scroll / flick?
I tried scroll(), flick() but unfortunately not working.

Please resolve it.

Thanks a lot in advance.

Regards,
Vaidya

**Comment by KazuCocoa** [comment]
Please consider to use selenium w3c actions to build actions
https://appium.io/docs/en/commands/interactions/actions/
https://selenium-python.readthedocs.io/api.html#module-selenium.webdriver.common.action_chains
