### ISSUE TITLE
Not working scroll from one element to another as expected in Appium 1.9.1 using python client with the  robotframework-appiumlibrary on the iOS 12 

### ISSUE THREAD

**Issue by WaFeIS7** [appium/python-client#254]
## The problem
Maybe it is not the issue, just improvement which needs to do.

To create automation tests on the mobile devices, I use robotframework and robotframework-appiumlibrary, appium python client. 

Since iOS released 12 version, I set up the latest appium 1.9.1 and tried to run my tests on the real iOS 12 device. My tests were broken because the scroll(from one element to the another) didn`t work as expected. 
In the server appium I see response status of the request 200, but nothing happens on the device. 

I asked advice @mykola-mokhnach and his advice helped, he said that need to add wait after the press in the TouchAction

I take on only appium-python and tried to scroll . 
`action = TouchAction(self.driver)
 action.press(element1).wait(600).move_to(element2).release().perform()`.  It works on the iOS 12.
But in the robotframework-appiumlibrary I can't make this function. In the Library there is no such implementation

The function(scroll - which I use in my tests) in the robotframework-appiumlibrary used scroll function from Appium_Python_Client-0.28-py2.7.egg!/appium/webdriver/webdriver.py

> Function scroll in the robotframework-appiumlibrary: 

def scroll(self, start_locator, end_locator):
el1 = self._element_find(start_locator, True, True)
el2 = self._element_find(end_locator, True, True)
driver = self._current_application()
driver.scroll(el1, el2)

> Function scroll in the Appium_Python_Client: 
    

def scroll(self, origin_el, destination_el):
        :Args:
         - originalEl - the element from which to being scrolling
         - destinationEl - the element to scroll to
        :Usage:
            driver.scroll(el1, el2)
        """
        action = TouchAction(self)
        action.press(origin_el).move_to(destination_el).release().perform()
        return self

In this function there is no wait after function press, I think that here there is the issue which could not allow working function scroll correct in the robotframework-appiumlibrary

## Environment
-  Appium version 1.9.1:
-  Xcode 10
-  Appium-Python-Client==0.28
-  robotframework-appiumlibrary==1.4.6
-  Python 2.7
- Node.js version v9.11.1
- iOS 12
- Real device 

## Details
My Local Solution is: 
I took the Appium-Python-Client, found function scroll in the WebDriver Class and add the third argument duration and wait after press: 

>  def scroll(self, origin_el, destination_el, duration):
        action = TouchAction(self)
        action.press(origin_el).wait(duration).move_to(destination_el).release().perform()
        return self

And Installed it. 
Then I took the robotframework-appiumlibrary and change the scroll function in the _TouchKeywords Class.  In the robotframework-appiumlibrary I saw changes which I made in the Appium-Python-Client.

>   def scroll(self, start_locator, end_locator, duration):
        el1 = self._element_find(start_locator, True, True)
        el2 = self._element_find(end_locator, True, True)
        driver = self._current_application()
        driver.scroll(el1, el2, duration)

And Installed it.  

In this case, scroll works on iOS 12 real device with that Environment which I use.
Maybe it is not the good solution, but it works for me and now I am possible to test iOS 12.  
If Somebody have the better solution, I wiil glad. 

Thanks.

**Comment by KazuCocoa** [comment]
thanks.
Yes, we should insert `wait` to wait arbitrary seconds working with W3C spec...

https://github.com/appium/python-client/blob/07180f7547ffcd13c212de21d027ea0355f9ab96/appium/webdriver/webdriver.py#L428-L440

let me update the method to set default duration for the case.

**Comment by WaFeIS7** [comment]
@KazuCocoa  Hi. 
When this changes will be applied in this Library? 
Also, need to make the change in the robotframework-appiumlibrary.

**Comment by KazuCocoa** [comment]
> when

Maybe it will be today or tomorrow.

> Also, need to make the change in the robotframework-appiumlibrary.

Yes. I'll create a PR to the library after releasing the new version like https://github.com/serhatbolsu/robotframework-appiumlibrary/pull/231

**Comment by WaFeIS7** [comment]
@KazuCocoa Thanks.

**Comment by WaFeIS7** [comment]
Also, When I use the function in the the robotframework-appiumlibrary "def scroll_up(self, locator):" 
I see error in appium server: 

> [debug] [W3C] Calling AppiumDriver.findElements() with args: ["id","Airplane Mode","ca5724a3-f3a1-4f90-9958-b2e40a154e46"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Matched '/elements' to command name 'findElements'
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/1796ACDE-6D18-4ADC-96BB-AFC1A59B943F/elements] with body: {"using":"id","value":"Airplane Mode"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":[{"ELEMENT":"4B000000-0000-0000-A309-000000000000"},{"ELEMENT":"80000000-0000-0000-A309-000000000000"},{"ELEMENT":"81000000-0000-0000-A309-000000000000"}],"sessionId":"1796ACDE-6D18-4ADC-96BB-AFC1A59B943F","status":0}
[debug] [W3C] Responding to client with driver.findElements() result: [{"element-6066-11e4-a52e-4f735466cecf":"4B000000-0000-0000-A309-000000000000"},{"element-6066-11e4-a52e-4f735466cecf":"80000000-0000-0000-A309-000000000000"},{"element-6066-11e4-a52e-4f735466cecf":"81000000-0000-0000-A309-000000000000"}]
[HTTP] <-- POST /wd/hub/session/ca5724a3-f3a1-4f90-9958-b2e40a154e46/elements 200 1900 ms - 248
[HTTP] 
[HTTP] --> POST /wd/hub/session/ca5724a3-f3a1-4f90-9958-b2e40a154e46/execute/sync
[HTTP] {"sessionId":"ca5724a3-f3a1-4f90-9958-b2e40a154e46","args":[{"direction":"up","element":"4B000000-0000-0000-A309-000000000000"}],"script":"mobile: scroll"}
[debug] [W3C] Calling AppiumDriver.execute() with args: ["mobile: scroll",[{"direction":"up","element":"4B000000-0000-0000-A309-000000000000"}],"ca5724a3-f3a1-4f90-9958-b2e40a154e46"]
[debug] [XCUITest] Executing command 'execute'
**[XCUITest] Proxying to WDA with an unknown route: POST /wda/element/4B000000-0000-0000-A309-000000000000/scroll**
[debug] [JSONWP Proxy] Proxying [POST /wda/element/4B000000-0000-0000-A309-000000000000/scroll] to [POST http://localhost:8100/session/1796ACDE-6D18-4ADC-96BB-AFC1A59B943F/wda/element/4B000000-0000-0000-A309-000000000000/scroll] with body: {"direction":"up"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"1796ACDE-6D18-4ADC-96BB-AFC1A59B943F","status":0}
[debug] [W3C] Responding to client with driver.execute() result: {}
[HTTP] <-- POST /wd/hub/session/ca5724a3-f3a1-4f90-9958-b2e40a154e46/execute/sync 200 2091 ms - 12
 
Maybe U know about this problem. 
Thanks

**Comment by EzimetYusup** [comment]
@KazuCocoa  is there a method to scroll the UITableView or UIScrollView all the way down to bottom from Top or from Bottom To Top ? or what's the best way to do it for native apps? 
Thanks!

**Comment by KazuCocoa** [comment]
@imurchie 
Could you release the new version of python-client when you have a time?

**Comment by WaFeIS7** [comment]
@KazuCocoa  Hello. 
Can you help me with this issue? 
`[debug] [W3C] Encountered internal error running command: InvalidSelectorError: Locator Strategy 'css selector' is not supported for this session` 

ENV: 
-  Appium 1.9.1 
-  Appium-Python-Client==0.28 (installed from current master, because i need fix with scroll(.wait), that you did). 
- robotframework-appiumlibrary==1.4.6 
- selenium==3.14.1 
- iOS 12

I run tests thought Robotframework.
 Log the Appium :: 
https://gist.github.com/WaFeIS7/c950aaf767678364eb48277125602785

**Comment by Srihari88** [comment]
Hi Guys,

I'm facing the issue that scrolling not working. Could you please help me out fix the issue.

**Comment by KazuCocoa** [comment]
What "not working" means?
I mean commands issued by the client was wrong or driver side issue.

**Comment by KazuCocoa** [comment]
Closed this issue since ordinally this issue was `wait` method, btw.
Feel free to create another issue
