### ISSUE TITLE
Appium 1.7 - Ten minutes to find an element 

### ISSUE THREAD

**Issue by HeEveret** [appium/python-client#263]
## Appium waits 10 minutes 

Appium sometimes waits for 10 minutes for an item instead of taking 20 seconds. Its happends on Android and iOS when we run it in AWS and in our Local Device Farm.

## Environment

- Appium version (or git revision) that exhibits the issue: 1.7.2 / 1.7.1
- Desktop OS/version used to run Appium: Win10
- Node.js version (unless using Appium.app|exe): 8.10 / 8.12
- Mobile platform/version under test: Android 7.0 / 8.0 & iOS 11.0.3 / 11.0.0
- Real device or emulator/simulator: LG K10; Samsung A5; Motorola G6 & iPhone 8; iPhone 7

## Link to Appium Logs

Here you can see that sometimes logs jumps 10 minutes and we dont know why.

Logs from AWS: (iOS)
https://gist.github.com/HeEveret/8ee3cdaa022f6dc3246829058c935a5a

Appium Logs from Local Device Farm: (Android)
https://gist.github.com/HeEveret/2cbcf4afc500395b88215347daf5dd49

## Code To reproduce issue
This happends when we are trying to wait an element with "find_element".

**Comment by HeEveret** [comment]
@mykola-mokhnach any idea? ;)

**Comment by KazuCocoa** [comment]
The latest Appium server is 1.9.1. We've added many improvements from 1.7.1.

I'm not familiar with how AWS handle Appium in their service. Thus, could you ask AWS support about it? You can request them to support the latest Appium version as well.
@HeEveret

**Comment by KazuCocoa** [comment]
The latest Appium server is 1.9.1. We've added many improvements from 1.7.1.

I'm not familiar with how AWS handle Appium in their service. Thus, could you ask AWS support about it? You can request them to support the latest Appium version as well.
@HeEveret
