### ISSUE TITLE
 Message of checking for updates 1.9.1 is bugged?

### ISSUE THREAD

**Issue by HeEveret** [appium/python-client#264]
## The problem

I was updating Appium Desktop to 1.9.1 and when the installation finished this message appear. I dont know if is a wrong message or I am not understanding something so please clear up me this. Thanks all.

## Details

![image](https://user-images.githubusercontent.com/42469714/47346777-251b4d80-d6ae-11e8-98d0-0b5cc75d4872.png)

**Comment by mykola-mokhnach** [comment]
Please use appium forum to ask questions. Here is not the right place to do it
