### ISSUE TITLE
Screen Recording on iOS and Android does not work

### ISSUE THREAD

**Issue by sasasa42** [appium/python-client#266]
## The problem

**Screen Recording does not work on iOS and Android.**
**iOS:** The screen recorder utility is not able to stop and store recording
**Android:** The recorded file is not found in the saved location

## Environment
- Appium version (or git revision) that exhibits the issue: v1.9.0
- Last Appium version that did not exhibit the issue (if applicable): NA
- Desktop OS/version used to run Appium: macOS High Sierra 10.13.6
- Node.js version (unless using Appium.app|exe): v8.11.1
- Mobile platform/version under test: iOS and Android
- Real device or emulator/simulator: Real Device
- Appium CLI or Appium.app|exe: Appium CLI

## Details

I have been trying to record teh screen from the real device, but finally I dont get to see the screen recording

## Link to Appium Logs

https://gist.github.com/sasasa42/a47139ac37529d29ac183f33c49ba53a

## Code To reproduce issue
def start_screen_recording():
    appiumDriver.start_recording_screen()

def stop_screen_recording():
    appiumDriver.stop_recording_screen()

**Comment by mykola-mokhnach** [comment]
Try appium@beta

**Comment by sasasa42** [comment]
@mykola-mokhnach I tried using the latest beta (Appium v1.9.2-beta.2), but **NO CHANGE**
/var/folders/cf/bbkz_3kd3hd6w61ks3l9t7zm0000gp/T/2018931-89893-gq0gaf.uc01/appium_4b1499.mp4

Actually right now on iOS devices, the folder(2018931-89893-gq0gaf.uc01) to store the recording is generated, but finally while trying to stop leads to an error and hence no recorded .mp4 file is found.

While on Android, the folder(2018931-89893-gq0gaf.uc01) gets created, but finally this gets replaced by another folder with the similar name (2018931-89893-rt8uar.iu75) and hence finally there is no recorded file in the location.

**Comment by mykola-mokhnach** [comment]
Probably you are doing something wrong. In the attached log I see the movie is generated properly on the server side and is passed to the client

**Comment by sasasa42** [comment]
Could be that something is wrong. But, I just call start_recording_screen() and stop_recording_screen() functions. Please just on what could go wrong @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
What is your code on the client side?

**Comment by sasasa42** [comment]
> What is your code on the client side?

The code at client side is nothing different. As I have already shared my code that I am calling the start_recording_screen() and stop_recording_screen(). The problem is that if I just use start_recording_screen(), I can see the recording somehow on the Android device, but there is some issue with uploading it to the default folder on my mac which is /var/folders/cf/bbkz_3kd3hd6w61ks3l9t7zm0000gp/T/2018931-89893-gq0gaf.uc01/1541154979241.mp4. The folder is not present in the system at all. Is there any way I can try to upload it to my local folder? I tried passing the optional arguments (options={'remotePath': '/Users/Downloads'}). But this did not work. There is some problem in uploading. Not able to resolve.

**Comment by gillett-hernandez** [comment]
There's a workaround for this that I have working on my machine. The driver.stop_screen_recording() function called without parameters returns a base64 encoded string that is actually *the* video data. The following snippet is what I use to write the video to a file.
```
# assuming filepath is where you're saving the video
payload = driver.stop_screen_recording()
with open(filepath, "wb") as fd:
    fd.write(base64.b64decode(payload))
```
I have tested this and I am able to view the video.

**Comment by mykola-mokhnach** [comment]
> The driver.stop_screen_recording() function called without parameters returns a base64 encoded string that is actually the video data

Totally correct. And this is also stated in the documentation

**Comment by sasasa42** [comment]
> There's a workaround for this that I have working on my machine. The driver.stop_screen_recording() function called without parameters returns a base64 encoded string that is actually _the_ video data. The following snippet is what I use to write the video to a file.
> 
> ```
> # assuming filepath is where you're saving the video
> payload = driver.stop_screen_recording()
> with open(filepath, "wb") as fd:
>     fd.write(base64.b64decode(payload))
> ```
> I have tested this only on Android, and I am able to view the video.

I tried doing this. But it also leads to the following error "IOError: [Errno 21] Is a directory:" when I am specifying the directory. Also, when I create blank .mp4 file, it again leads to "IOError: [Errno 2] No such file or directory: ".

**Comment by gillett-hernandez** [comment]
@sasasa42 : `filepath` needs to have the actual path of the file that you want to create.
if you have the directory path saved in a variable called `directory` and you want to call the file `screen_recording_110918-205655.mp4` then `filepath` would be `os.path.join(directory, "screen_recording_110918-205655.mp4")`
i.e.
`filepath = os.path.join(directory, "screen_recording_110918-205655.mp4")`
then the rest of the snippet would follow and the whole deal would look like
```python
filepath = os.path.join(directory, "screen_recording_110918-205655.mp4")
payload = driver.stop_screen_recording()
with open(filepath, "wb") as fd:
    fd.write(base64.b64decode(payload))
```
does that help to clarify things?

note: if `directory` contains the home symbol `~`, then you need to convert that to an absolute path by using other functions in the `os.path` module.

**Comment by sasasa42** [comment]
> @sasasa42 : `filepath` needs to have the actual path of the file that you want to create.
> if you have the directory path saved in a variable called `directory` and you want to call the file `screen_recording_110918-205655.mp4` then `filepath` would be `os.path.join(directory, "screen_recording_110918-205655.mp4")`
> i.e.
> `filepath = os.path.join(directory, "screen_recording_110918-205655.mp4")`
> then the rest of the snippet would follow and the whole deal would look like
> 
> ```python
> filepath = os.path.join(directory, "screen_recording_110918-205655.mp4")
> payload = driver.stop_screen_recording()
> with open(filepath, "wb") as fd:
>     fd.write(base64.b64decode(payload))
> ```
> 
> does that help to clarify things?
> 
> note: if `directory` contains the home symbol `~`, then you need to convert that to an absolute path by using other functions in the `os.path` module.

Absolutely correct @gillett-hernandez . Thank you for the resolution. This works on Android. I will try on iOS and confirm soon. But @mykola-mokhnach , I could understand from the documentation that there is this limitation of recording only for a max. of 3 min. for Android and 10 min. for iOS. Is there any way to extend this beyond this limit?

**Comment by mykola-mokhnach** [comment]
It is possible since appium@beta, but requires ffmpeg to be installed on the destination system

**Comment by sasasa42** [comment]
> It is possible since appium@beta, but requires ffmpeg to be installed on the destination system



> > @sasasa42 : `filepath` needs to have the actual path of the file that you want to create.
> > if you have the directory path saved in a variable called `directory` and you want to call the file `screen_recording_110918-205655.mp4` then `filepath` would be `os.path.join(directory, "screen_recording_110918-205655.mp4")`
> > i.e.
> > `filepath = os.path.join(directory, "screen_recording_110918-205655.mp4")`
> > then the rest of the snippet would follow and the whole deal would look like
> > ```python
> > filepath = os.path.join(directory, "screen_recording_110918-205655.mp4")
> > payload = driver.stop_screen_recording()
> > with open(filepath, "wb") as fd:
> >     fd.write(base64.b64decode(payload))
> > ```
> > 
> > 
> > does that help to clarify things?
> > note: if `directory` contains the home symbol `~`, then you need to convert that to an absolute path by using other functions in the `os.path` module.
> 
> Absolutely correct @gillett-hernandez . Thank you for the resolution. This works on Android. I will try on iOS and confirm soon. But @mykola-mokhnach , I could understand from the documentation that there is this limitation of recording only for a max. of 3 min. for Android and 10 min. for iOS. Is there any way to extend this beyond this limit?

I have tested it on iOS 11.4 and it works! But, on iOS 10.1.1, it does not work. It throws the below error:
The screen recorder utility has failed to store the actual screen recording at '/var/folders/cf/bbkz_3kd3hd6w61ks3l9t7zm0000gp/T/20181012-53748-vu3ine.sx37e/appium_c53477.mp4'

**Comment by sasasa42** [comment]
> It is possible since appium@beta, but requires ffmpeg to be installed on the destination system

@mykola-mokhnach Can you show an example for extending beyond the max. allowed limit?

**Comment by anirbandan** [comment]
Hello @mykola-mokhnach 
Did you get any solution for this issue? I am getting the same error on ios 14.4 on executing "stop recording screen" method.



```
Selenium::WebDriver::Error::UnknownError:
       An unknown server-side error occurred while processing the command. Original error: The screen recorder utility has failed to store the actual screen recording at '/var/folders/7t/nmh45xm50fg4c1zcr5ktcp040000gp/T/2021628-470-19pv5xw.huvsj/appium_39b3bc.mp4'
```
