### ISSUE TITLE
push a zip file to my Android device in Appium

### ISSUE THREAD

**Issue by Ucoon** [appium/python-client#268]
## The problem

is there any way that pushing a zip file to my Android device? When using push_file() I found that it can push file such as text, but except zip file. I use python to write my scripts.
## Environment

* Appium version (or git revision) that exhibits the issue: 1.9.0
* Desktop OS/version used to run Appium: Ubuntu 18.04
* Node.js version (unless using Appium.app|exe): v8.12.0
* Mobile platform/version under test: Android 5.0

## This is my code:
```
try:
driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)
except Exception as e:
print(("WebDriverException Error : ", e))

with open('E:\\myupdate_318.zip', 'rb') as zip_file:
    data = zip_file.read()
driver.push_file('/storage/sdcard1/myupdate.zip', data.encode('base64'))
zip_file.close()  
```
## This is server log:
```
Traceback (most recent call last): File "/home/user/Project/Appium/AutoInstallSoftWare/AutoInstallSoftWare.py", line 30, in test_unintall_old_package self.driver.push_file('/storage/sdcard1/myupdate.zip', data.encode('base64')) AttributeError: 'bytes' object has no attribute 'encode'
```
What should I do?

**Comment by KazuCocoa** [comment]
I'd like to re-open if it happens with the above way. feel free to comment here

**Comment by Ucoon** [comment]
It seems worked. But there is another problem.
This is server log:
```
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/home/hezj/Software/AndroidStudio/SDK/platform-tools/adb -P 5037 -s SA17607795 push /tmp/appium118102-4690-1oojik2.xo1kh.tmp /storage/sdcard1/myupdate.zip' timed out after 20000ms'; Stderr: ''; Code: 'null'
```
I have set 'newcommandtimeout' : '2000', But it still does not work

**Comment by shivakrishnach31** [comment]
Hi @KazuCocoa - I need to push an audio track(.wav or .aac) to a folder created by my app. When pushing the file it is creating appium.tmp file. Can you help me with how to push the audio file? Below is my code:

Code #1:
```
sPath=bytes("C:\\Users\\myPC\\Downloads\\file_example_WAV_1MG.wav", "utf-8")
driver.push_file(destination_path="./sdcard/My Recordings", base64data=base64.b16encode(sPath).decode('utf-8'))
```

Code #2
```
drive.push_file(destination_path="./sdcard/My Recordings", 
                        source_path="C:\\Users\\myPC\\Downloads\\file_example_WAV_1MG.wav")
```

**Comment by KazuCocoa** [comment]
https://github.com/appium/python-client/blob/9c597a3afe76ff1283c45259ed6e1c4aadac530d/test/functional/android/remote_fs_tests.py#L24 this test case may help.
Probably you should change `b16encode` with `b64encode` in code 1. code 2 needs more your explanation like appium log

**Comment by shivakrishnach31** [comment]
Hi @KazuCocoa - I changed it to b64encode in code 1. I am still seeing the appium.tmp file in the folder in android device.

Please find the below log for code 2:
[HTTP] {"path":"./sdcard/Motiv Recordings","data":"QzpcVXNlcnNcY2hpcHBhc1xEb3dubG9hZHNcZmlsZV9leGFtcGxlX1dBVl8xTUcud2F2"}
[W3C (91420b6a)] Calling AppiumDriver.pushFile() with args: ["./sdcard/MyRecordings","QzpcVXNlcnNcY2hpcHBhc1xEb3dubG9hZHNcZmlsZV9leGFtcGxlX1dBVl8xTUcud2F2","91420b6a-b2bb-400c-9172-b4898ae71c7f"]
[ADB] Running 'C:\Users\chippas\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZY2252Z6LD shell mkdir -p ./sdcard'
[ADB] Running 'C:\Users\chippas\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZY2252Z6LD push C\:\\Users\\chippas\\AppData\\Local\\Temp\\appium2020818-7368-141kvkr.mhwz.tmp './sdcard/My Recordings''
[AndroidDriver] After pushing media file, broadcasting media scan intent
[ADB] Running 'C:\Users\chippas\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZY2252Z6LD shell am broadcast -a android.intent.action.MEDIA_SCANNER_SCAN_FILE -d 'file://./sdcard/My Recordings''
[W3C (91420b6a)] Responding to client with driver.pushFile() result: null

**Comment by shivakrishnach31** [comment]
Hi @KazuCocoa @mykola-mokhnach Any inputs after looking at my previous comment.

**Comment by KazuCocoa** [comment]
Probably you should fix destination_path. Not sure the relative path works. How about to setting the path as absolute path?

**Comment by shivakrishnach31** [comment]
Hi @KazuCocoa - I have tried with the absolute path but still facing the same issue. Is there any other way to try it?

**Comment by KazuCocoa** [comment]
Appium only calls below commands, so you can tweak paths with below adb commands directly.
If below commands did not work for you, you should find a correct way to be able to push a file to the path.

```
'C:\Users\chippas\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZY2252Z6LD shell mkdir -p ./sdcard'
'C:\Users\chippas\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s ZY2252Z6LD push C\:\\Users\\chippas\\AppData\\Local\\Temp\\appium2020818-7368-141kvkr.mhwz.tmp './sdcard/My Recordings''
```

As https://github.com/appium/python-client/blob/9c597a3afe76ff1283c45259ed6e1c4aadac530d/test/functional/android/remote_fs_tests.py#L24 , maybe the path to `/data/local/tmp/test_push_file.txt` work on your env, too.
