### ISSUE TITLE
Feature Request: driver.push_file(destination_path, source_path)

### ISSUE THREAD

**Issue by Jonahss** [appium/python-client#269]
### The problem

Right now, in order to put files on a device, the `driver.push_file(path, base64)` function is used.
It can be a little confusing or complex for people to always read a file from their filesystem, encode as base64, then pass it into this function.

### The Solution

How about creating another way to use this function: `driver.push_file(destination_path, source_path)`? This would be simpler for most users.

This work would be a perfect candidate for a Pull Request from someone who wants to make their first contribution to the Appium Python community :D

(suggested by @jlipps)

**Comment by Jonahss** [comment]
Thanks for taking this on @JavonDavis !

**Comment by JavonDavis** [comment]
No problem! @Jonahss

**Comment by KazuCocoa** [comment]
Published https://pypi.org/project/Appium-Python-Client/0.31/
Thanks @JavonDavis !

**Comment by JavonDavis** [comment]
Awesome! Glad I could contribute 😬
