### ISSUE TITLE
Appium iOS(python 2.7) Touch action from element to element works partially (scrolling only once)

### ISSUE THREAD

**Issue by sumanthvakacharla** [appium/python-client#279]
## The problem

Tried to scroll down using Touch and release action from element to element in order to click on sign out button at the bottom. It scrolls only once, after that it throws the WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "The element '"SettingsSignOutButton" StaticText' is not visible on the screen and thus is not interactable" UserInfo={NSLocalizedDescription=The element '"SettingsSignOutButton" StaticText' is not visible on the screen and thus is not interactable}

BUT if we do not use touch action and just simply click on the sign out button object it successfully clicks but without scrolling down. It used to work for the previous appium and xcode, OS versions.

## Environment
- Current appium version : Appium desktop 1.8.2, Appium server 1.9.1 (Xcode 10.1, OS Mojave 10.14.1)
- Last working Appium version  : 1.6.5
- Desktop OS/version used to run Appium:(Xcode 9.4, OS High sierra 10.13.1)
- Node.js version (unless using Appium.app|exe):11.1.0
- Mobile platform/version under test:iPhone 7 plus - 11.3
- Real device or emulator/simulator:Simulator
- Appium CLI or Appium.app|exe: Appium.app

## Details

Also tried using duration in the scroll method parameters. But still seeing the same exception

## Link to Appium Logs
https://gist.github.com/sumanthvakacharla/bc6be2e29344490a011e772ea2c03e6b

## Code To reproduce issue

        top_element = self.find_element_by_id(accessibilityStatic.Settings.SyncNow)
        signOutButton = self.find_element_by_id(accessibilityStatic.Settings.SignOutButton)
        # self.scroll_to(signOutButton, top_element)
        # self.scroll_to(signOutButton)
        try:
            self.driver.scroll(top_element, signOutButton)
        except Exception as e:
#######
Below code is the webdriver provided code in the python client-0.31-> appium->webdriver
#######
# convenience method added to Appium (NOT Selenium 3)
    def scroll(self, origin_el, destination_el, duration=None):
        """Scrolls from one element to another

        :Args:
         - originalEl - the element from which to being scrolling
         - destinationEl - the element to scroll to
         - duration - a duration after pressing originalEl and move the element to destinationEl. Default is 600 ms for W3C spec. Zero for MJSONWP.

        :Usage:
            driver.scroll(el1, el2)
        """

        # XCUITest x W3C spec has no duration by default in server side
        if self.w3c and duration is None:
            duration = 600

        action = TouchAction(self)
        if duration is None:
            action.press(origin_el).move_to(destination_el).release().perform()
        else:
            action.press(origin_el).wait(duration).move_to(destination_el).release().perform()
        return self

**Comment by KazuCocoa** [comment]
> BUT if we do not use touch action and just simply click on the sign out button object it successfully clicks but without scrolling down. It used to work for the previous appium and xcode, OS versions.

Did you do the way with `xcuitest` automation name? _without scrolling down_ was probably old behaviour...
(It depended on Apple's internal logic in accessibility framework layer)


In python, the behaviour (scroll once and tap) looks expected behaviour. We need to mention it in the documentation.

btw, you can try http://appium.io/docs/en/writing-running-appium/ios/ios-xctest-mobile-gestures/index.html#mobile-scroll as well for xcuitest

**Comment by sumanthvakacharla** [comment]
Yes I have used xcuitest as automation name in the capabilities.json

It is not even scroll once and tap behavior.

It just scrolls once and throwing the mentioned Exception.

_**checkpoint**_:As described in the issue, If we don't even use touchAction, it does not scroll at all (not even once) and just clicks the element successfully.

It does not scroll but clicks the element even if I use
 driver.execute_script('mobile: scroll', {'direction': 'down'});

**Comment by ki4070ma** [comment]
If this error still occurs with the latest appium server and client, please reopen.
