### ISSUE TITLE
 ImportError: No module named script.helper on version 0.32

### ISSUE THREAD

**Issue by topikettunen** [appium/python-client#293]
## The problem
Unable to install latest version of `Appium-Python-Client` with `pip install Appium-Python-Client`

## Environment
- Appium version (or git revision) that exhibits the issue: 0.32
- Last Appium version that did not exhibit the issue (if applicable): 0.31
- Desktop OS/version used to run Appium: Alpine Linux 

## Details

```
Collecting Appium-Python-Client
  Using cached https://files.pythonhosted.org/packages/d7/96/21fe7892d937b27e7b89c65693cb3ce715d56cb614503cc09838784643c8/Appium-Python-Client-0.32.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-9C9pll/Appium-Python-Client/setup.py", line 20, in <module>
        from script.helper import read_version
    ImportError: No module named script.helper

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-9C9pll/Appium-Python-Client/
```

## Workaround

`pip install Appium-Python-Client==0.31`

**Comment by KazuCocoa** [comment]
thanks. let me check..

**Comment by KazuCocoa** [comment]
@topikettunen 0.33 is available. I ensured I was able to install it via `pip install` Thanks
