### ISSUE TITLE
Protocol Converter converts to `{"type":"sessionId","ms":"5432a4f3-cd89-4781-8905-ea9d3150840c"}` not only timeout

### ISSUE THREAD

**Issue by MacGuffinLife** [appium/python-client#305]
## The problem

I get the Error which say "unknown error: 'ms' must be a double".And I google it ,Found that maybe caused by W3C and MJSONWP.I found the issue In java-client,But Force_MJSONWP is not work in Python-client.What should I do for solving this Error?

## Environment
- Appium version (or git revision) that exhibits the issue:appium Desktop v1.10.0
- Last Appium version that did not exhibit the issue (if applicable):appium Desktop v1.10.0
- Desktop OS/version used to run Appium:MacOS Mojave
- Node.js version (unless using Appium.app|exe):use Appium app
- Mobile platform/version under test: MI-4C Android 7.10,Samsung Note9 Android 8.1.0
- Real device or emulator/simulator:Real Device
- Appium CLI or Appium.app|exe:Appium Desktop for Mac

## Details
Testing Web in Chrome for Android 71.0.3578.99
Don't get Error everytime.But always.
When I use the `driver.implicitly_wait()`,I get this
The Exception in Python-client:
```
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: unknown error: 'ms' must be a double
  (Session info: chrome=71.0.3578.99)
  (Driver info: chromedriver=2.44.609545 (c2f88692e98ce7233d2df7c724465ecacfe74df5),platform=Mac OS X 10.14.2 x86_64)
```

## Link to Appium Logs
The Log in Appium:
```
[JSONWP Proxy] Matched '/wd/hub/session/5432a4f3-cd89-4781-8905-ea9d3150840c/timeouts' to command name 'timeouts'
[Protocol Converter] Will send the following request bodies to /timeouts: [{"type":"implicit","ms":2000},{"type":"sessionId","ms":"5432a4f3-cd89-4781-8905-ea9d3150840c"}]
[JSONWP Proxy] Proxying [POST /wd/hub/session/5432a4f3-cd89-4781-8905-ea9d3150840c/timeouts] to [POST http://127.0.0.1:8006/wd/hub/session/215a4a41f37dcf0962f039a731094119/timeouts] with body: {"type":"implicit","ms":2000}
[JSONWP Proxy] Got response with status 200: {"sessionId":"215a4a41f37dcf0962f039a731094119","status":0,"value":null}
[JSONWP Proxy] Proxying [POST /wd/hub/session/5432a4f3-cd89-4781-8905-ea9d3150840c/timeouts] to [POST http://127.0.0.1:8006/wd/hub/session/215a4a41f37dcf0962f039a731094119/timeouts] with body: {"type":"sessionId","ms":"5432a4f3-cd89-4781-8905-ea9d3150840c"}
[JSONWP Proxy] Got response with status 200: {"sessionId":"215a4a41f37dcf0962f039a731094119","status":13,"value":{"message":"unknown error: 'ms' must be a double\n  (Session info: chrome=71.0.3578.99)\n  (Driver info: chromedriver=2.44.609545 (c2f88692e98ce7233d2df7c724465ecacfe74df5),platform=Mac OS X 10.14.2 x86_64)"}}
[JSONWP Proxy] Got an unexpected response: {"sessionId":"215a4a41f37dcf0962f039a731094119","status":13,"value":{"message":"unknown error: 'ms' must be a double\n  (Session info: chrome=71.0.3578.99)\n  (Driver info: chromedriver=2.44.609545 (c2f88692e98ce7233d2df7c724465ecacfe74df5),platform=Mac OS X 10.14.2 x86_64)"}}
[W3C (5432a4f3)] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: The request to /wd/hub/session/5432a4f3-cd89-4781-8905-ea9d3150840c/timeouts has failed
[W3C (5432a4f3)]     at JWProxy.proxy (/Applications/Appium.app/Contents/Resources/app/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:180:13)
[MJSONWP] Matched JSONWP error code 13 to UnknownError
[HTTP] <-- POST /wd/hub/session/5432a4f3-cd89-4781-8905-ea9d3150840c/timeouts 500 14 ms - 1069
```
### All appium Logs
[appium Logs](https://gist.github.com/MacGuffinLife/3ab9639831b5828bd3755cb5d9bdc7a3)

#

## Code To reproduce issue
`driver.implicitly_wait(2)`

**Comment by KazuCocoa** [comment]
Sometimes, this happens according to your log...

I can see below two kind of lines in your log. The former is expected, but the later is unexpected. Maybe, sometimes `Protocol Converter]` failed to convert... (This is not Python client issue.)

- https://gist.github.com/MacGuffinLife/3ab9639831b5828bd3755cb5d9bdc7a3#file-ms-must-be-double-L592
```
[debug] [35m[Protocol Converter][39m Will send the following request bodies to /timeouts: [{"type":"implicit","ms":2000}]
```

- https://gist.github.com/MacGuffinLife/3ab9639831b5828bd3755cb5d9bdc7a3#file-ms-must-be-double-L424
```
[debug] [35m[Protocol Converter][39m Will send the following request bodies to /timeouts: [{"type":"implicit","ms":2000},{"type":"sessionId","ms":"5432a4f3-cd89-4781-8905-ea9d3150840c"}]
```

**Comment by KazuCocoa** [comment]
link: https://github.com/search?q=org%3Aappium+Protocol+Converter&type=Code

**Comment by MacGuffinLife** [comment]
@KazuCocoa I found the [familiar issue](https://github.com/appium/appium/issues/11016) with mine,And it seems that there is a solution could fix it.setting the force MJSONWP,But I don't know how to set this in python client.
Or,maybe this familiar issue is resulted in a different reason??

**Comment by KazuCocoa** [comment]
In Python client, you can set `forceMjsonwp` like https://github.com/appium/python-client/blob/d5b8a1e9183571a5a6380cf8d9faf7c862dfd572/test/unit/webdriver/webdriver_test.py#L67 . It should work fine.


I should take a look the cause further since almost time `Protocol Converter` works expected. But sometimes it includes `{"type":"sessionId","ms":"5432a4f3-cd89-4781-8905-ea9d3150840c"}`...

**Comment by MacGuffinLife** [comment]
@MacGuffinLife Thanks,work fine now. I have try `'force_mjsonwp':'true'`,but it can't work.`forceMjsonwp`is the right.The problem should be caused by appium,and found it in Augest.But it remain here.

**Comment by KazuCocoa** [comment]
@MacGuffinLife What about the latest `appium@beta` which will be 1.11.0 soon?
