### ISSUE TITLE
Send appWaitActivity to device farm was 

### ISSUE THREAD

**Issue by Mohammed-Alhaj** [appium/python-client#316]
Hi

To run my android app locally i have to start 'appWaitActivity' to run the login activity.
I'm trying to run my code now on Device Farm but my issue that this capability didn't start.

How can let the device farm to read my capability

i'm using Java-Junit-Jbehave

**Comment by KazuCocoa** [comment]
We cannot say anything without logs, since we cannot assume what happens there.
But, the best way is asking the device farm's support.
