### ISSUE TITLE
How start Appium server programmatically is there any server object as in Java client? 

### ISSUE THREAD

**Issue by EitanBe** [appium/python-client#323]
## The problem

How start Appium server programmatically is there any server object as in Java client? 

## Environment
- Latest python client 

## Details

Running on real devices

**Comment by KazuCocoa** [comment]
Do you mean like https://github.com/appium/java-client/blob/80c1425868b9959ecbd80fbad2e7ba32f9da8b09/src/main/java/io/appium/java_client/service/local/AppiumServiceBuilder.java#L527 ?
No, only Java client wraps node command, I think.

You can ask questions in appium forum.

**Comment by KazuCocoa** [comment]
https://github.com/appium/python-client/pull/324#pullrequestreview-199443026
