### ISSUE TITLE
Move commands in webdriver.py into other mixin's classes

### ISSUE THREAD

**Issue by KazuCocoa** [appium/python-client#325]
We'd like to reduce a number commands in webdriver.py, since the file has a bunch of commands in one file 

example: https://github.com/appium/python-client/pull/307

----

https://github.com/appium/python-client/blob/master/appium/webdriver/webdriver.py#L741

- LAUNCH_APP, CLOSE_APP
    - => https://github.com/appium/python-client/blob/master/appium/webdriver/extensions/applications.py
- GET_CURRENT_PACKAGE, END_TEST_COVERAGE, OPEN_NOTIFICATIONS
    - https://github.com/appium/python-client/blob/master/appium/webdriver/extensions/android/common.py (new file)
- SET_IMMEDIATE_VALUE, REPLACE_KEYS, CLEAR
    - https://github.com/appium/python-client/blob/master/appium/webdriver/extensions/keyboard.py
    - Maybe keyboard is enough since the three also type text

**Comment by KazuCocoa** [comment]
updated

**Comment by SGA-atsushi-mori** [comment]
I think it's done.
If no, please re-open.

**Comment by ki4070ma** [comment]
I think it's done.
If no, please reopen.
