### ISSUE TITLE
remotePath and other options for start_screen_recording and stop_screen_recording are not interpreted properly

### ISSUE THREAD

**Issue by gillett-hernandez** [appium/python-client#329]
## The problem

the docs seem to indicate that the following should work (when real values are used):

```driver.stop_recording_screen(remotePath="https://example.com", user="example", pass="pass", method="POST"})```

but instead, the following needs to be used for it to actually work:

```driver.stop_recording_screen(options={"remotePath":"https://example.com", "user":"example", "pass":"pass", "method":"POST"})```

## Environment
- Appium version (or git revision) that exhibits the issue: v1.10.0
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: 
- Node.js version (unless using Appium.app|exe): v10.15.0
- Mobile platform/version under test: Android P
- Real device or emulator/simulator: real device
- Appium CLI or Appium.app|exe: Appium cli

## Link to snippet of Appium Logs

https://gist.github.com/gillett-hernandez/7f7e82f2f1ab90cddb113d8f5b96f523

**Comment by gillett-hernandez** [comment]
possibly related to this?
https://github.com/appium/python-client/blob/master/appium/webdriver/extensions/screen_record.py

**Comment by KazuCocoa** [comment]
Fixed in 0.38
