### ISSUE TITLE
Move/define search context in appium/webdriver/extensions/search_context.py

### ISSUE THREAD

**Issue by KazuCocoa** [appium/python-client#336]
## The problem

https://github.com/appium/python-client/pull/335/commits/6f23f89aaee0acc811f535144ea22c5790b0cb52#diff-9f2b90ea43eed700426cb52a45812bfdL90 is a good example. It removed some lines tho.

We define many commands in webdriver.py and webelement.py.
We're working to reduce the number of lines in them to make them simple.

For search context, we would like to move search context-related command from webdriver and webelement to extensions/search_context.

https://github.com/appium/python-client/pull/335/files also be an example. The PR was for data matcher.

_Move commands in webdriver.py into other mixin's classes #325_ is another issue about the mixin thing

**Comment by jlipps** [comment]
Yes please!

**Comment by ki4070ma** [comment]
Done by https://github.com/appium/python-client/pull/461
