### ISSUE TITLE
Problem with order tests unittest 

### ISSUE THREAD

**Issue by dron4ik86** [appium/python-client#337]
## The problem

After upgrading the python-client to version 0.38, I have the problem with my tests.
The problem is that all my tests work with the unittest library. All my test with test number, for example:

```
class SimpleTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.driver = webdriver.Remote('http://0.0.0.0:4723/wd/hub', desired_caps_android)
        cls.driver.implicitly_wait(10)
        cls.actions = TouchAction(cls.driver)
        cls.wait = WebDriverWait(cls.driver, 10)

    @classmethod
    def tearDownClass(cls):
        cls.driver.quit()

    def test_01_test_name(self):
        """step_1"""

    def test_02_test_name(self):
        """step_2"""

    def test_03_test_name(self):
        """step_3"""

if __name__ == '__main__':
    suite = unittest.TestLoader().loadTestsFromTestCase(SimpleTest)
    unittest.TextTestRunner(verbosity=2).run(suite)
```
The problem is that somehow after test_01 test_02 will be skipped to test_03. I don't have this problem with version 0.36

## Environment
- Appium version 1.10.1
- Last Appium version that did not exhibit the issue (if applicable) - 0.36
- Desktop OS/version used to run Appium - MACOS
- Node.js version - 8.14.0
- Mobile platform/version under test -  Android
- Real device or emulator/simulator - emulator

**Comment by KazuCocoa** [comment]
Mm... Let me consider.

We do not inject outside modules such as the unittest..

**Comment by ki4070ma** [comment]
This issue still occurs with the latest version?
If so, I'll look into this issue.

At least, I couldn't reproduce with below source codes and environments.

```
#!/usr/bin/python
# -*- coding: utf-8 -*-
import os
import unittest

from appium import webdriver

caps = {
    'platformName': "Android",
    'platformVersion': "8.0",
    'deviceName': "Android",
    'appPackage': "package",
    'appActivity': "package/activity",
    'app': /path/to/apk
    'automationName': "uiautomator2",
}


class SimpleTest(unittest.TestCase):

    def setUp(self):
        self.driver = webdriver.Remote('http://0.0.0.0:4723/wd/hub', caps)

    def tearDown(self):
        self.driver.quit()

    def test_01_test_name(self):
        print("step_1")

    def test_02_test_name(self):
        print("step_2")

    def test_03_test_name(self):
        print("step_3")


if __name__ == '__main__':
    suite = unittest.TestLoader().loadTestsFromTestCase(SimpleTest)
    unittest.TextTestRunner(verbosity=2).run(suite)
```

## Environment
- Appium version (or git revision) that exhibits the issue: 1.11.0
- Last Appium version that did not exhibit the issue (if applicable): -
- Desktop OS/version used to run Appium: MacOS 10.14.3
- Node.js version (unless using Appium.app|exe): v10.14.2
- Mobile platform/version under test: Android 8.0
- Real device or emulator/simulator: Real device
- Appium CLI or Appium.app|exe: Appium.app (Appium Desktop)
- Python client: 0.40.0

**Comment by ki4070ma** [comment]
Not active for a while.

Please freely re-open if reproduced or additional info.
