### ISSUE TITLE
Unable to scroll in Appium using Python with touchaction and UiAutomator 

### ISSUE THREAD

**Issue by JhansiGalma** [appium/python-client#341]
## The problem

Unable to scroll in Appium using Python with touchaction and UiAutomator 

## Environment
- Appium version - 1.10.0 and 1.11.0
- Desktop OS/version used to run Appium: Windows 10
- Node.js version (unless using Appium.app|exe): 10.15.1
- Mobile platform/version under test: 7.0
- Real device or emulator/simulator: Real Device
- Appium Python Client - 0.39

## Details

Got below error while trying to scroll using touch action
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Appium_Scripts\Appium_Training\Jabong\testCases\jabongLogin.py", line 42, in test_jabongLogin
    actions.press(x=21,y=1681).move_to(x=803, y=782).release().perform()
  File "C:\Python27\lib\site-packages\appium\webdriver\common\touch_action.py", line 94, in perform
    self._driver.execute(Command.TOUCH_ACTION, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 367, in execute
    command_info = self._commands[command]
KeyError: 'touchAction'

----------------------------------------------------------------------
Ran 1 test in 17.724s

FAILED (errors=1)

## Link to Appium Logs

https://gist.github.com/JhansiGalma/31bb1d33b70c69581a13e6c3f381f289

## Code To reproduce issue

actions = TouchAction(self.driver)
actions.press(x=21,y=1681).move_to(x=803, y=782).release().perform()

**Comment by KazuCocoa** [comment]
> [warn] [35m[Appium][39m Consider setting 'automationName' capability to 'UiAutomator2' on Android >= 6, since UIAutomator1 framework is not maintained anymore by the OS vendor.


What about using UIA2 as the above warning?

**Comment by JhansiGalma** [comment]
Thank you, it did work using UIA2.
