### ISSUE TITLE
AndroidDriver is not performing click() or even Touch actions (tap/press).

### ISSUE THREAD

**Issue by javydreamercsw** [appium/python-client#349]
## The problem

AndroidDriver is not performing click() or even Touch actions (tap/press).

## Environment
- Appium version (or git revision) that exhibits the issue: 1.9.1
- Last Appium version that did not exhibit the issue (if applicable): N/A
- Desktop OS/version used to run Appium: macOS Mojave (10.14.4)
- Node.js version (unless using Appium.app|exe): 11.13.0
- Mobile platform/version under test: Android Emulator 8.0
- Real device or emulator/simulator: Emulator
- Appium CLI or Appium.app|exe: CLI

## Details

When using click on the web element it responds with a 200 but nothing is clicked. Tried with touch actions tap/press and on that case it just doesn't call the action at all.

This seems related to #189

## Link to Appium Logs

https://gist.github.com/javydreamercsw/0352add5cf16ab456c5a683092c43b84

## Code To reproduce issue

 N/A

**Comment by KazuCocoa** [comment]
What about something like below?

```
self.execute_script("document.getElementById('user-list').click();")
```

**Comment by javydreamercsw** [comment]
Just realized this might be in the wrong project. Opened on the right project https://github.com/appium/appium/issues/12512
