### ISSUE TITLE
Issue on scroll script

### ISSUE THREAD

**Issue by nithinmohan114** [appium/python-client#356]
## Scrolling isn't working as expected on Android devices

I was trying to scroll down to test android application and it wasn't working as expected. Tried TouchAction

## Environment
- Appium version (or git revision) that exhibits the issue: 1.11.1
- Last Appium version that did not exhibit the issue (if applicable): 1.11.1
- Desktop OS/version used to run Appium: Ubuntu 16.04
- Node.js version (unless using Appium.app|exe): v10.15.3
- Mobile platform/version under test: Android
- Real device or emulator/simulator: Emulator

## Details
While checked there seems to be an issue already
https://discuss.appium.io/t/how-to-use-scroll-swipe-in-python-except-from-coordinates/20944/10

**Comment by KazuCocoa** [comment]
Could you attach your log?
It's appreciated to understand situations.

**Comment by nithinmohan114** [comment]
sorry, it is working now, closing issue
