### ISSUE TITLE
Always got no module named Appium error

### ISSUE THREAD

**Issue by vrtestinglab** [appium/python-client#361]
Always got no module named Appium error as below:
Traceback (most recent call last):
  File "C:/Users/Gamma/PycharmProjects/IPD/Notepad.py", line 4, in <module>
    from appium import webdriver
ImportError: No module named Appium

While I tried to launch the app from Appium, and I can launch successfully. And I have installed Appium-Python-Client-0.41, I have installed Windows App Driver.
{
  "deviceName": "Gamma",
  "platformName": "Windows",
  "platformVersion": "1809",
  "app": "C:\\Users\\Gamma\\Desktop\\Test.txt"
}
![Appium](https://user-images.githubusercontent.com/48261104/57046332-fd8cdb00-6c24-11e9-8c5f-51a7e96fdae2.PNG)
![Script](https://user-images.githubusercontent.com/48261104/57046333-fd8cdb00-6c24-11e9-8d0e-24fc3d908cdd.PNG)

**Comment by KazuCocoa** [comment]
How do you manage the code?
If you install it in your global environment, what about below?

```
$ python # launch console

> from appium import webdriver  # What happens in the output??
```

I'm not familiar with the pycharm environment

**Comment by mykola-mokhnach** [comment]
> from appiun import webdriver

of course it won't work

**Comment by KazuCocoa** [comment]
I assume this is python running environment.
Could you make sure you can import module installed by `pip`? https://github.com/appium/python-client#getting-the-appium-python-client
(Or from source code?)

It depends on the pycharm tho
