### ISSUE TITLE
Move to Pipfile for dependencies management

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/python-client#365]
Currently the module dependencies are managed by `requirements.txt`. This is not good, since such format does not provide good compatibility with multiple python versions and also does not allow to properly use dependencies lock approach. We need to switch deps management to use [Pipfile](https://github.com/pypa/pipfile), which is actively developed and has much more possibilities for fine-tuning

**Comment by KazuCocoa** [comment]
nice 👍

**Comment by ki4070ma** [comment]
Just introduced pipfile by https://github.com/appium/python-client/pull/376.

We need to utilize pipfile function on demands in the future.
e.g. https://github.com/pypa/pipfile/blob/master/examples/Pipfile
