### ISSUE TITLE
'send_keys()' does not work 

### ISSUE THREAD

**Issue by Raj17940** [appium/python-client#380]
## The problem

send_keys() doesn't work for numeric element (For Example: mobile number Field) in web application for safari mobile browsers on iOS Simulator 
          
    i.e Mobile number field allow only numbers

**Comment by KazuCocoa** [comment]
Could you attach the full server log as the issue template https://github.com/appium/python-client/issues/new ?
It helps us to understand the situation.

**Comment by Raj17940** [comment]
## The problem

send_keys() doesn't work for numeric element (For Example: mobile number Field and postal code Field) in web application for safari mobile browsers on iOS Simulator

i.e Mobile number field allow only numbers and postal code 

## Environment
- Appium version (or git revision) that exhibits the issue: 1.13
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: MAC 
- Node.js version (unless using Appium.app|exe):
- Mobile platform/version under test: Mobile
- Real device or emulator/simulator: Simulator
- Appium CLI or Appium.app|exe:

## Link to Appium Logs

https://gist.github.com/Raj17940/f7ec054564557d93b14e24342a758708

## Code To reproduce issue

element = context.driver.find_element_by_xpath("//input[contains(@placeholder,'Postal Code')]").send_keys(postalCode)

**Comment by KazuCocoa** [comment]
It is probably similar to https://stackoverflow.com/questions/23412912/selenium-send-keys-doesnt-work-if-input-type-number .

The sending values from the client is expected.
Maybe, executing JS on safari can be the solution
https://www.eviltester.com/blog/seleniumsimplified/2016-08-17-how-to-debug-webdriver-javascriptexecutor-in-java/

**Comment by Raj17940** [comment]
@KazuCocoa I tried use execute_script() to update the value for the element (postal code), value are entering but it travers to another element in the html form its disappear. 

sample code:

context.driver.execute_script("arguments[0].value=arguments[1]", element, postalCode)
context.driver.execute_script("document.getElementsByName('postcode')[0].value={0}".format(postalCode))

**Comment by KazuCocoa** [comment]
I have no exact idea, unfortunately.
Asking in Appium forum https://discuss.appium.io might help it.

**Comment by ki4070ma** [comment]
Please use Appium forum https://discuss.appium.io for further questions.

**Comment by tranquangvu0651** [comment]
It's work for me when I used like this.
`el = self.mobileDriver.find_element_by_xpath(selector)
el.click()
ActionChains(self.mobileDriver).send_keys(text).perform()`

need to import library `from selenium.webdriver.common.action_chains import ActionChains`

**Comment by farazalikhan33** [comment]
.

**Comment by farazalikhan33** [comment]
Thanks a lot @tranquangvu0651 !!
