### ISSUE TITLE
"Bad parameters: BadParametersError: Parameters were incorrect." when send_keys called

### ISSUE THREAD

**Issue by Stml89** [appium/python-client#392]
I'm running Appium + real device + python appium client + pytest, but am getting this error when I try to use 'send_key' method I got an error:
Appium:
[debug] [MJSONWP] **Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":["value"]} and you sent ["text","value","id","sessionId"]**
Pycharm:
**selenium.common.exceptions.WebDriverException: Message: Parameters were incorrect. We wanted {"required":["value"]} and you sent ["text","value","id","sessionId"]**

Environment
- Appium - 1.6.5
- Python - 3.6.4
- Selenium - 3.141.0
- Appium-Python-Client - 0.43
- Windows 10
- pytest - 4.5.0

I could not downgrade to selenium 3.3.1, because I see an error: "appium-python-client 0.43 has requirement selenium>=3.14.1, but you'll have selenium 3.3.1 which is incompatible."
Also, I've tried to upgrade to selenium 4.0.0a1 - got the same error: "Parameters were incorrect. We wanted {"required":["value"]} and you sent ["text","value","id","sessionId"]"

Appium Logs:
https://gist.github.com/Stml89/51b273cd869434ef85237a66f15de718

The issue persists:
username_field = driver.find_element_by_accessibility_id("input_username")
username_field.send_keys("rami777")

Could you please help me?

**Comment by mykola-mokhnach** [comment]
Please update Appium to the recent version

**Comment by Stml89** [comment]
> Please update Appium to the recent version

Thank you, it works!
