### ISSUE TITLE
keycode, keyevent to search not working

### ISSUE THREAD

**Issue by i-am-sanguine** [appium/python-client#393]
I am trying to automate an e-commerce app with appium and Python. the issue I have is with "Search". Nothing I have tried worked. I have tried the following:
```
self.driver.find_element_by_id(<search_button_id>).click
self.driver.press_keycode(84)
self.driver.press_keycode(66)
self.driver.keyevent(84)
self.driver.keyevent(66)
```

All of the above returned nothing. and here is the log: 
https://gist.github.com/i-am-sanguine/bd639467c49fd1d7b07107447c17b142
However, when I tried this:
`self.driver.execute_script('mobile:performEditorAction', {'action:' 'search'})`
it returned this error below:

```
Traceback (most recent call last):
  File "/Users/sanguine/PycharmProjects/KongaApp/check.py", line 30, in <module>
    driver.execute('mobile:performEditorAction', {'action:' 'search'})
  File "/Users/sanguine/.pyenv/versions/3.7.3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 307, in execute
    params['sessionId'] = self.session_id
TypeError: 'set' object does not support item assignment
```
And the Log from this error is:
https://gist.github.com/i-am-sanguine/e57702b2ca2212e8e2491d68c8847e4e

## Environment

* Appium version: v1.13.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac OS Mojave (10.14.5)
* Node.js version : v 10.15.3
* Mobile platform/version under test: 7.1.1
* Real device or emulator/simulator: Android Studio Emulator

**Comment by i-am-sanguine** [comment]
> The first approach is not going to work anyway. The second one is correct, howeverit looks like there is a problem in the python client. Moving the issue to the appropriate tracker.

Why did the first approach fail please? Make me understand so I won't repeat such a mistake again. Thank you

**Comment by i-am-sanguine** [comment]
I tried each of the first approach separately actually and none of it worked.

**Comment by KazuCocoa** [comment]
```
self.driver.execute_script('mobile:performEditorAction', {'action:' 'search'})
```

=>

what about below? (`:` in your command combined with `action` like `action:`)

```
self.driver.execute_script('mobile:performEditorAction', {'action': 'search'})
```

**Comment by i-am-sanguine** [comment]
> ```
> self.driver.execute_script('mobile:performEditorAction', {'action:' 'search'})
> ```
> 
> =>
> 
> what about below? (`:` in your command combined with `action` like `action:`)
> 
> ```
> self.driver.execute_script('mobile:performEditorAction', {'action': 'search'})
> ```

Thank you. I have corrected the typo now I am no longer getting an error but it still will not search

**Comment by KazuCocoa** [comment]
Can you attach your appium logs and logcat if you can get?
The behaviour depends on Android environments such as IME etc.

**Comment by i-am-sanguine** [comment]
> Can you attach your appium logs and logcat if you can get?
> The behaviour depends on Android environments such as IME etc.

Here is the [log](https://gist.github.com/i-am-sanguine/e29cfd21ed0a2209641d66e0f459a2df)

**Comment by mykola-mokhnach** [comment]
Perhaps, your control reacts to some other action. Try `go` or other available options. It would be the best to check it with the application developer

**Comment by i-am-sanguine** [comment]
> Perhaps, your control reacts to some other action. Try `go` or other available options. It would be the best to check it with the application developer

I have tried 'go', 'next' and 'done' nothing worked. I don't know the developer, it is an e-commerce app, I am automating it to improve my skills. Perhaps if you would explain to me why driver.keyevent would work, maybe that might help.

**Comment by ki4070ma** [comment]
@i-am-sanguine 
At least, below codes works on my environment.
https://github.com/ki4070ma/python-client/commit/aa3d401ae54ec53ee3541558f589ef0f418d5147
 - `self.driver.execute_script('mobile:performEditorAction', {'action': 'go'})`

```
(get above codes)
$cd /path/to/python-client/test/functional/android
$python keyboard_tests.py
```

## Environment

* Appium version: v1.13.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac OS Mojave (10.14.5)
* Node.js version : v 12.3.0
* Mobile platform/version under test: 9 (API 28)
* Real device or emulator/simulator: Emulator

Can you try this codes on your env?
(if my misunderstanding, please correct me.)

**Comment by KazuCocoa** [comment]
The reason why mykola said so, developers can customise available keyevent to their products.
search/go/done are common, but they are customisable by developers in Android world.

This is the reason why mykolad suggested you asking your developers about available keys.
https://github.com/appium/python-client/issues/393#issuecomment-498613598

----

Close this issue once since this is not pythin client issue ( https://github.com/appium/python-client/issues/393#issuecomment-498638834 )

**Comment by i-am-sanguine** [comment]
> @i-am-sanguine
> At least, below codes works on my environment.
> [ki4070ma@aa3d401](https://github.com/ki4070ma/python-client/commit/aa3d401ae54ec53ee3541558f589ef0f418d5147)
> 
> * `self.driver.execute_script('mobile:performEditorAction', {'action': 'go'})`
> 
> ```
> (get above codes)
> $cd /path/to/python-client/test/functional/android
> $python keyboard_tests.py
> ```
> 
> ## Environment
> * Appium version: v1.13.0
> * Last Appium version that did not exhibit the issue (if applicable): N/A
> * Desktop OS/version used to run Appium: Mac OS Mojave (10.14.5)
> * Node.js version : v 12.3.0
> * Mobile platform/version under test: 9 (API 28)
> * Real device or emulator/simulator: Emulator
> 
> Can you try this codes on your env?
> (if my misunderstanding, please correct me.)

Can I get a private chat with you so I can understand your code please?
