### ISSUE TITLE
Cannot import name 'webdriver' from Appium on Python

### ISSUE THREAD

**Issue by hke14** [appium/python-client#401]
## The problem
The issue I am encountering is that despite having downloaded appium and installing the appium-python-client, when I run the code you have on your documentation(specifically the code snippet found here: https://github.com/appium/python-client#usage ), I get the error : "cannot import name 'webdriver' from 'appium'"

## Environment
I installed the appium python client using pip install appium-python-client, I have appium-python-client-0.44.
I am using Windows 10 and Python 3.7.2
I am using nodeJS v10.15.3 and appium v1.13.0
I am using the Android platform on a real device.

## Details

My problem is that I can't import WebDriver from Appium despite a Webdriver folder existing inside the Appium package in Lib/site-packages

## Code To reproduce issue
```
import unittest
from appium import webdriver

desired_caps = {}
desired_caps['platformName'] = 'Android'
desired_caps['platformVersion'] = '9'
desired_caps['automationName'] = 'uiautomator2'
desired_caps['deviceName'] = 'OnePlox'
desired_caps['app'] = 'C:/Users/hadin/Desktop/ApiDemos-debug.apk'

driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)


```

**Comment by mykola-mokhnach** [comment]
Are you sure you used the correct package manager? Perhaps one should use pip3 to install python3 packages (but I would prefer to create a virtual env first and install packages there instead)

**Comment by hke14** [comment]
I uninstalled and reinstalled using pip3. I was already using a virtual env. It still did not work.

**Comment by KazuCocoa** [comment]
Could you share the output of your Python script like...: `python3 -m your-python-script`? and what the result of `pip show Appium-Python-Client`?

**Comment by hke14** [comment]
Here's the result for `python -m appium.py`:

C:\Users\hadin\AppData\Local\Programs\Python\Python37\python.exe: Error while finding module specification for 'appium.py' (ImportError: cannot import name 'webdriver' from 'appium' (C:\Users\hadin\Desktop\Appium_Python\appython\appium.py))

and here's the result for `pip show Appium-Python-Client`:
Name: Appium-Python-Client
Version: 0.44
Summary: Python client for Appium
Home-page: http://appium.io/
Author: Isaac Murchie
Author-email: isaac@saucelabs.com
License: Apache 2.0
Location: c:\users\hadin\appdata\local\programs\python\python37\lib\site-packages
Requires: selenium
Required-by:

Sorry for bothering you guys on the weekend. Much appreciated.
P.S.: I wasn't able to use python3 and had to use python, but as you can see from the output of the first command, I am using python3,

**Comment by hke14** [comment]
Ok I found what was causing the issue, the reason was that I named my python script `appium.py`, I changed it and now I'm getting new results. Thanks for your help

**Comment by sankara-popuri** [comment]
Hi hkel14 can you tell me how did you fix the issue 

Getting the same kind of issue and was struggling for the fix can you share the fix.
![image](https://user-images.githubusercontent.com/31643705/77163535-44e9b780-6ad4-11ea-9da9-e99fed262674.png)

**Comment by hke14** [comment]
@sankara-popuri Yes all I did was that my python file I trying to run was named Appium and I was trying to import Appium in the same file. This is what caused the issue. I changed the file's name to something different and it worked out

**Comment by bwomsm1** [comment]
I can confirm that al I created a folder named `appium`, and the script was trying to import webdriver from there.
Problem solved by renaming the folder name

**Comment by hitesh02sharma** [comment]
Even my file name is different but getting same issue. 
Any other pointer pls?

**Comment by hitesh02sharma** [comment]
fixed by updating the Appium python client
