### ISSUE TITLE
PyCharm does not suggest methods for Appium Python client

### ISSUE THREAD

**Issue by KazuCocoa** [appium/python-client#402]
Selenium WebDriver can.

e.g.

```
self.driver. find_element_by_accessibility_id('xxxx') # When `.` is inputted, PyCharm should suggest `click` etc
self.driver. find_element_by_xpath('xxxx') # When `.` is inputted, PyCharm suggests `click` etc. selenium webdriver has it
```

I'm not sure the logic of PyCharm yet

**Comment by mykola-mokhnach** [comment]
This probably happens because of the mixin structure. In Python 3 it might work better as it gives a possibility to provide type hints

**Comment by ki4070ma** [comment]
Seems working well on my environment, so it's not due to Appium Python client at least. (maybe PyCharm settings?)

![screenshot](https://user-images.githubusercontent.com/1549855/59545216-a7aa9300-8f45-11e9-9af9-0e59192a4f65.png)

**Comment by ki4070ma** [comment]
Appium-Python-Client should be here.

![screenshot](https://user-images.githubusercontent.com/1549855/59545374-6e732280-8f47-11e9-9db5-c030547ccff9.png)

**Comment by KazuCocoa** [comment]
What about `find_element_by_accessibility_id`? Not `by_id` @ki4070ma

**Comment by ki4070ma** [comment]
@KazuCocoa 
Sorry for my missing check description for details, it doesn't work.

![スクリーンショット 2019-06-15 10 24 36](https://user-images.githubusercontent.com/1549855/59546461-0ed14300-8f58-11e9-9698-71c5ea35bd5c.png)

**Comment by ki4070ma** [comment]
Fixed by https://github.com/appium/python-client/pull/404

**Comment by AmanVerma1110** [comment]
i'm also facing same issue how to sortout pls help
