### ISSUE TITLE
Android python support for driver.toggleAirplaneMode()

### ISSUE THREAD

**Issue by blairroebuck** [appium/python-client#405]
## The problem

As discussed at AppiumConf, could support be added to support 'driver.toggleAirplaneMode()' for python for iOS / XCUITest. Currently there is no python support and it would be super useful to be able to use it. 

## Environment

* Feature doesn't exist in 1.13.0
* Desktop OS/version used to run Appium: Mostly Desktop
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager: 10.16.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator

**Comment by mykola-mokhnach** [comment]
I personally don't know a way to toggle Airplane Mode on iOS. Also, in Android this only works for API below 24

**Comment by blairroebuck** [comment]
> I personally don't know a way to toggle Airplane Mode on iOS (except of doing that inn the UI). Also, in Android this only works for API below 24

Thanks for the quick reply, i raised it initially referencing iOS in error, i wasn't aware  it was only for below API24. 

I guess if thats the case then someone can close as 'Cant Fix'

**Comment by ki4070ma** [comment]
As @mykola-mokhnach said.

Not support toggle Airplane Mode in API 25 and later.
https://github.com/appium/appium/issues/7716
https://github.com/appium/python-client/issues/353
