### ISSUE TITLE
The android

### ISSUE THREAD

**Issue by ZhaoMoMo** [appium/python-client#421]
## The problem

This is not an issue, but a question on my side. I need to execute a large number of test scripts on serial android phones. 
1.Firstly, one or two phone match with an appium server (more than 3 phones send requests to an appium server will get the result of losing message) will cost too much CPU resources. An windows PC with i3 processor can only drive 4 android devices at most.

2.I try to use the independent client-server mode, and using the appium-python-client. And I found that the android devices should only be connected on the appium server PC, but not the client PC. Is there any method to support me to connect android phone with a client PC, and just use the appium server PC to send and receive message?

3. If the answer of above question is NO, could you please give me some suggestion of how to deal with the large CPU cost problem of appium server?

Waitting for your reply.
## Environment
- Appium version (or git revision) that exhibits the issue: 1.9.0
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: 1.9.0
- Node.js version (unless using Appium.app|exe): V10.15.3
- Mobile platform/version under test: android 9.0
- Real device or emulator/simulator: Real device.
- Appium CLI or Appium.app|exe: Appium.exe

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium Logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.

**Comment by KazuCocoa** [comment]
Appium 1.9.0 is outdated. You can try later one like 1.14.0 or the beta which has many improvements.

You can connect devices via tcp like https://developer.android.com/studio/command-line/adb#wireless . Your servers can connect to devices connect to your client PC via it.

But maybe this way is more unstable than direct connection via usb on my experience.

**Comment by ZhaoMoMo** [comment]
1.Is  android devices can only be connected with server PC, if via USB connection?
2.what is the performance of "unstable connection via wireless", can strengthened network will solve the problem?

**Comment by KazuCocoa** [comment]
1. Yes.
Currently, Android platform has no way to detect devices which are not connected as USB or Wireless (tcp) since Appium uses `adb` command

2. I hope so.
It depends on _Connect to a device over Wi-Fi_ feature by `adb` I shared the link with you. A good network condition is one factor to make it stable.

**Comment by ZhaoMoMo** [comment]
OK, many thanks for your reply.
A more question, how many android devices can be drive by a server PC on your side?And what about the performance of the PC?

**Comment by KazuCocoa** [comment]
I haven't connected Android devices to Windows PC.
On mac mini or Ubuntu server, I connected over 10 devices using USB hubs before.
They worked well without anything bad.

I am not sure, the windows pc performance case. https://discuss.appium.io may help for such a general question, I hope.

**Comment by ZhaoMoMo** [comment]
OK many thanks
