### ISSUE TITLE
Add GET session/session_id command

### ISSUE THREAD

**Issue by KazuCocoa** [appium/python-client#425]
Python client does not have the command.
Some clients have them such as Ruby and JS clients.

We'd like to add it

**Comment by KazuCocoa** [comment]
@vrunoa
Will you work for this?
(Sorry for mentioning you since I was not sure which account was Sadaf.)

**Comment by vrunoa** [comment]
@KazuCocoa yes, I think that should be enough since event timings are stored on the session. Do you have a PR we can use as an example for adding a new method? 
cc @sadafyadegari

**Comment by KazuCocoa** [comment]
Yes.
https://github.com/appium/python-client/pull/368/files is an example to add new commands

**Comment by ki4070ma** [comment]
Link to https://github.com/appium/python-client/pull/427

**Comment by KazuCocoa** [comment]
https://github.com/appium/python-client/pull/429
