### ISSUE TITLE
Open deeplink on mobile devices

### ISSUE THREAD

**Issue by Stml89** [appium/python-client#430]
I'm using python and I am trying to automate open a deeplink on mobile devices.

I got the following error:
../../venv/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py:319: in execute
    response = self.command_executor.execute(driver_command, params)

self = <appium.webdriver.appium_connection.AppiumConnection object at 0x11174fb38>
command = 'mobile: deepLink'
params = {'package': 'com.android.chrome', 'sessionId': '9e6176a3-7254-4e4b-bfa0-29dddba459f3', 'url': 'deeplink here'}

    def execute(self, command, params):
        """
        Send a command to the remote server.
        Any path subtitutions required for the URL mapped to the command should be
        included in the command parameters.
        :Args:
         - command - A string specifying the command to execute.
         - params - A dictionary of named parameters to send with the command as
           its JSON payload.
        """
>       command_info = self._commands[command]
E       KeyError: 'mobile: deepLink'

../../venv/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py:367: KeyError

My code:
self.driver.execute("mobile: deepLink", {'url': 'deeplink here', 'package': 'com.android.chrome'})

Do you have any ides on how to fix it?

**Comment by mykola-mokhnach** [comment]
moved the python client

**Comment by Stml89** [comment]
Sorry, it was my mistake
I used **execute** instead of **execute_script** for python
It work's fine for me:
`self.driver.execute_script("mobile: deepLink", {'url': 'https://deeplink/gNQHDAOXkZ', 'package': 'com.android.chrome'})`

**Comment by LiJiaHeer** [comment]
> Sorry, it was my mistake
> I used **execute** instead of **execute_script** for python
> It work's fine for me:
> `self.driver.execute_script("mobile: deepLink", {'url': 'https://deeplink/gNQHDAOXkZ', 'package': 'com.android.chrome'})`

thanks, Your answer is resolve i get error.
