### ISSUE TITLE
can't use TouchActions

### ISSUE THREAD

**Issue by chenhuipeng1** [appium/python-client#434]
## The problem
I want to run selenium tests on Android device and I'm using Appium, using chomedriver 76 version and chrome version 76. 
I switch context from native to webview and i use selenium TouchActions, then it have an error "selenium.common.exceptions.WebDriverException: Message: unknown command: Cannot call non W3C standard command while in W3C mode"
After searching, i try add "appium: chromeOptions": {"w3c": False} in my webdriver capabilities, but it doesn't work

## Environment
- Appium version (or git revision) that exhibits the issue: 1.14.2
- Node.js version (unless using Appium.app|exe): 10.16.2
- Mobile platform/version under test: Android
- Real device or emulator/simulator: vivoY85A

## Link to Appium Logs

https://gist.github.com/chenhuipeng1/faa06b1f80b4802bba1e1de27654caaa

**Comment by KazuCocoa** [comment]
It is because Chromedriver communicates with W3C WebDriver protocol instead of MJSONWP.

Please try out ActionChain in Selenium Python client term
http://appium.io/docs/en/commands/interactions/actions/

**Comment by chenhuipeng1** [comment]
> It is because Chromedriver communicates with W3C WebDriver protocol instead of MJSONWP.
> 
> Please try out ActionChain in Selenium Python client term
> http://appium.io/docs/en/commands/interactions/actions/

I have tried ActionChain before, it doesn't have any error, but when i click the element, it has no response, how can i make it working?
here is my code:
from selenium.webdriver.common.touch_actions import TouchActions
el = driver.find_element_by_xpath('//*[@class="m-playable-close"]')
actions = ActionChains(driver)
actions.click(el)
actions.perform()

Is there anything wrong？

**Comment by KazuCocoa** [comment]
I cannot anything without logs, unfortunately.
It depends on chromedriver side.
As Appium, we should make sure the command transferred to chromedriver properly.
If the transfer worked fine, but nothing happened, maybe chromedriver has an issue. Or JSON generated by chained action is wrong..

Could you share your log?


btw, what about adding `actions.move_to_element(el)` before `actions.click(el)`

**Comment by chenhuipeng1** [comment]
> I cannot anything without logs, unfortunately.
> It depends on chromedriver side.
> As Appium, we should make sure the command transferred to chromedriver properly.
> If the transfer worked fine, but nothing happened, maybe chromedriver has an issue. Or JSON generated by chained action is wrong..
> 
> Could you share your log?
> 
> btw, what about adding `actions.move_to_element(el)` before `actions.click(el)`

I change my code into:
el = driver.find_element_by_xpath('//*[@class="m-playable-close"]')
actions = ActionChains(driver)
actions.move_to_element(el)
actions.click(el)
actions.perform()

but it still has no response
here is the log
https://gist.github.com/chenhuipeng1/4012802dbdd84698d7c1c514bbd5a22e

or how can i change chromeOption so chromedriver could communicates with MJSONWP?

**Comment by KazuCocoa** [comment]
Thanks. it seems how to coordinate actions on chromedriver.
Functionality as appium and its client commands passed to the driver properly.

Maybe, below works.

```
goog:chromeOptions: {
    w3c: false
}
```

https://discuss.appium.io may help to post questions

**Comment by chenhuipeng1** [comment]
> Thanks. it seems how to coordinate actions on chromedriver.
> Functionality as appium and its client commands passed to the driver properly.
> 
> Maybe, below works.
> 
> ```
> goog:chromeOptions: {
>     w3c: false
> }
> ```
> 
> https://discuss.appium.io may help to post questions

I try goog:chromeOptions, appium:chromeOptions, chromeOptions, all they failed

desired_caps = {
    "platformName": "Android",
    "platformVersion": "8.1",
    "deviceName": "vivoY85A",
    "appPackage": "xxx",
    "appActivity": "xxx",
    "noReset": "true",
    "automationName": "uiautomator2",
    "goog:chromeOptions": {"w3c": False}
}

**Comment by KazuCocoa** [comment]
Could you share full your log?
In https://gist.github.com/chenhuipeng1/faa06b1f80b4802bba1e1de27654caaa#file-appium_log-L16 , you probably inserted a space before the material so appium handled it as no valid capability.
If it appeared https://gist.github.com/chenhuipeng1/faa06b1f80b4802bba1e1de27654caaa#file-appium_log-L333-L346 , appium succeeds to pass it to chromedriver. Then, the bahaviour depends on chromedriver side.

I referred below code and guessed `w3c: false` worked. but if it does not. I have no idea. (Asking discuss.appiu.io is better than appium repositories)
https://github.com/bayandin/chromedriver/blob/c16855442e341d01bc0067e1aeefea212e2d152f/capabilities.cc#L542

**Comment by chenhuipeng1** [comment]
> Could you share full your log?
> In https://gist.github.com/chenhuipeng1/faa06b1f80b4802bba1e1de27654caaa#file-appium_log-L16 , you probably inserted a space before the material so appium handled it as no valid capability.
> If it appeared https://gist.github.com/chenhuipeng1/faa06b1f80b4802bba1e1de27654caaa#file-appium_log-L333-L346 , appium succeeds to pass it to chromedriver. Then, the bahaviour depends on chromedriver side.
> 
> I referred below code and guessed `w3c: false` worked. but if it does not. I have no idea. (Asking discuss.appiu.io is better than appium repositories)
> https://github.com/bayandin/chromedriver/blob/c16855442e341d01bc0067e1aeefea212e2d152f/capabilities.cc#L542

I am sorry for i alwaly forget to share my log

it seems to succeeds to pass it to chromedriver
`
[Chromedriver] Starting W3C Chromedriver session with capabilities: {
[Chromedriver]   "capabilities": {
[Chromedriver]     "alwaysMatch": {
[Chromedriver]       "goog:chromeOptions": {
[Chromedriver]         "androidPackage": "com.mintegral.sdk.demo",
[Chromedriver]         "androidUseRunningApp": true,
[Chromedriver]         "w3c": false,
[Chromedriver]         "androidDeviceSerial": "72852a23"
[Chromedriver]       },
[Chromedriver]       "goog:loggingPrefs": {
[Chromedriver]         "browser": "ALL"
[Chromedriver]       }
[Chromedriver]     }
[Chromedriver]   }
[Chromedriver] }
`
but it comes out another error "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: A new session could not be created. Details: session not created: Missing or invalid capabilities
  (Driver info: chromedriver=76.0.3809.68 (420c9498db8ce8fcd190a954d51297672c1515d5-refs/branch-heads/3809@{#864}),platform=Windows NT 10.0.17763 x86_64)"
