### ISSUE TITLE
A problem "css selector" is not supported for this session When I use the latest version 1.13.0

### ISSUE THREAD

**Issue by jasminebb** [appium/python-client#435]
I use the function **find_element_by_id()**, but it didn't work, the error message is : **Locator Strategy 'css selector' is not supported for this session**. 
I've read the solutions whose problem is similar with me, they said upgrading codes to the latest version. Then I did.
Now, my tools are 
### Appium-Desktop 1.13.0, selenium 3.141.0, appium-python-client v0.47, urllib3 1.25.3
they are all latest, but did't work.
Could someone help me pls?  i really have no idea how to do solve ....

**Comment by mykola-mokhnach** [comment]
How do you create the driver instance in the client code?

**Comment by manoj9788** [comment]
@jasminebb does this issue still occur, can you please respond to the above question?

**Comment by YanxiFeng** [comment]
I'm facing the same problem. My tools are **Appium-Desktop 1.15.1, selenium 3.141.0, Appium-Python-Client 0.48, urllib3 1.23.**
I create driver instance like this:
`import time
import os.path

from appium import webdriver
from selenium.webdriver.support.wait import WebDriverWait

app = os.path.abspath('/Users/***/***.app')

desired_caps = dict()
desired_caps['app'] = app
desired_caps['platformName'] = 'ios'
desired_caps['platformVersion'] = '12.4'
desired_caps['deviceName'] = 'iPad (5th generation)'
desired_caps['app'] = 'com.***.ipad'
desired_caps['udid'] = '4bcf75036a0*****2ea6960c3d850b857e'

driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)`
