### ISSUE TITLE
Need a interface to judge element exist or not 

### ISSUE THREAD

**Issue by huangrui127** [appium/python-client#44]
Can supply a  api interface to support judge a element exist or not .

such as :  driver.check_element_by_name('')  if the element exist return true,else return false.

**Comment by tylersnavely-wf** [comment]
If you prefer not to implicitly wait for an element to exist in the above example, you could do:
```
return len(driver.find_elements(By.STRATEGY, query_string)) > 0
```

I would follow that up by saying that a direct API for getting the existence of an element isn't available in the base selenium API, so for parity sake, I would say it doesn't belong here either.

**Comment by KazuCocoa** [comment]
mentioned in the above
