### ISSUE TITLE
How can I order tests?

### ISSUE THREAD

**Issue by dron4ik86** [appium/python-client#447]
## The problem

When I create my tests via appium the order of my tests is not work correctly.
I saw the example of your code:
[your code](https://github.com/appium-boneyard/sample-code/blob/master/sample-code/examples/python/ios_complex.py)
I saw that your tests are sorted by the alphabet. 
In my example:

```
import unittest


class TestSum(unittest.TestCase):

    def test_remove(self):
        print("1")

    def test_add(self):
        print("2")


if __name__ == '__main__':
    loader = unittest.TestLoader()
    loader.sortTestMethodsUsing = None
    unittest.main(testLoader=loader)
```
Test `test_remove` need to be the first test and not a second.
I try to cancel the alphabet sort of unittest (use sortTestMethodsUsing  ) but I still have the problem to order my test.
Do you have some idea how can I solve this problem?

**Comment by KazuCocoa** [comment]
https://stackoverflow.com/questions/30286268/order-of-tests-in-python-unittest
According to the page, maybe the `sortTestMethodsUsing = None` does not work?

You could try https://pytest-ordering.readthedocs.io/en/develop/  with pytest.
Asking it in https://discuss.appium.io also probably helps it
