### ISSUE TITLE
path is not defined, able to escape it but get 'self' is not defined error

### ISSUE THREAD

**Issue by ryanrestivo** [appium/python-client#451]
## The problem

Working in python3 using appium for an Android app on emulator using a Mac (Mojave 10.14.6) 
I have reached all the steps but I reach PATH is not defined... 

>>> import unittest
>>> from appium import webdriver
>>> 
>>> desired_caps = {}
>>> desired_caps['platformName'] = 'Android'
>>> desired_caps['platformVersion'] = '8.1'
>>> desired_caps['automationName'] = 'uiautomator2'
>>> desired_caps['deviceName'] = 'Test2'
>>> desired_caps['app'] = PATH('test.apk')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'PATH' is not defined

My Bash profile has everything I need and appium-doctor says I'm set

export ANDROID_HOME=/Users/rrestivo/Library/Android/sdk
export ANDROID_SDK=$ANDROID_HOME

export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
export PATH=$ANDROID_HOME/tools:$PATH
export JAVA_HOME=$(/usr/libexec/java_home)
export PATH=${JAVA_HOME}/bin:$PATH

--- 
I try to bypass the PATH  in the script by import os and os.path.abspath('test.apk') but 

>>> import os
>>> desired_caps['app'] = os.path.abspath('test.apk')

but whenever I run the app I get 

>>> self.driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'self' is not defined

is this because I"m using os.path.abspath to get to into the app or a different reason? how can I resolve this? 

## Environment
➜  ~ appium-doctor
info AppiumDoctor Appium Doctor v.1.12.1
info AppiumDoctor ### Diagnostic for necessary dependencies starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  ✔ Node version is 11.10.0
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ Xcode Command Line Tools are installed in: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ DevToolsSecurity is enabled.
info AppiumDoctor  ✔ The Authorization DB is set up properly.
info AppiumDoctor  ✔ Carthage was found at: /usr/local/bin/carthage. Installed version is: 0.33.0
info AppiumDoctor  ✔ HOME is set to: /Users/rrestivo
info AppiumDoctor  ✔ ANDROID_HOME is set to: /Users/rrestivo/Library/Android/sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: /Library/Java/JavaVirtualMachines/jdk-13.0.1.jdk/Contents/Home
info AppiumDoctor  ✔ adb exists at: /Users/rrestivo/Library/Android/sdk/platform-tools/adb
info AppiumDoctor  ✔ android exists at: /Users/rrestivo/Library/Android/sdk/tools/android
info AppiumDoctor  ✔ emulator exists at: /Users/rrestivo/Library/Android/sdk/tools/emulator
info AppiumDoctor  ✔ Bin directory of $JAVA_HOME is set
info AppiumDoctor ### Diagnostic for necessary dependencies completed, no fix needed. ###
info AppiumDoctor 
info AppiumDoctor ### Diagnostic for optional dependencies starting ###
WARN AppiumDoctor  ✖ opencv4nodejs cannot be found.
WARN AppiumDoctor  ✖ ffmpeg cannot be found
WARN AppiumDoctor  ✖ mjpeg-consumer cannot be found.
info AppiumDoctor  ✔ idb and idb_companion are installed
WARN AppiumDoctor  ✖ applesimutils cannot be found
WARN AppiumDoctor  ✖ bundletool.jar cannot be found
info AppiumDoctor ### Diagnostic for optional dependencies completed, 5 fixes possible. ###
info AppiumDoctor 
info AppiumDoctor ### Optional Manual Fixes ###
info AppiumDoctor The configuration can install optionally. Please do the following manually:
WARN AppiumDoctor  ➜ Why opencv4nodejs is needed and how to install it: https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/image-comparison.md
WARN AppiumDoctor  ➜ ffmpeg is needed to record screen features. Please read https://www.ffmpeg.org/ to install it
WARN AppiumDoctor  ➜ mjpeg-consumer module is required to use MJPEG-over-HTTP features. Please install it with 'npm i -g mjpeg-consumer'.
WARN AppiumDoctor  ➜ Why applesimutils is needed and how to install it: http://appium.io/docs/en/drivers/ios-xcuitest/
WARN AppiumDoctor  ➜ bundletool.jar is used to handle Android App Bundle. Please read http://appium.io/docs/en/writing-running-appium/android/android-appbundle/ to install it
info AppiumDoctor 
info AppiumDoctor ###
info AppiumDoctor 
info AppiumDoctor Bye! Run appium-doctor again when all manual fixes have been applied!
info AppiumDoctor 

## Details

Last login: Wed Oct 16 17:24:07 on ttys000
➜  ~ source .bash_profile 
➜  ~ python3
Python 3.7.2 (default, Feb 12 2019, 08:15:36) 
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import unittest
>>> from appium import webdriver
>>> 
>>> desired_caps = {}
>>> desired_caps['platformName'] = 'Android'
>>> desired_caps['platformVersion'] = '9.0'
>>> desired_caps['automationName'] = 'uiautomator2'
>>> desired_caps['deviceName'] = 'Test'
>>> import os
>>> desired_caps['app'] = os.path.abspath('selendroid-test-app.apk')
>>> self.driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/appium/webdriver/webdriver.py", line 144, in __init__
    proxy
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/site-packages/appium/webdriver/webdriver.py", line 219, in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device.

>>> self.driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'self' is not defined
>>> el = self.driver.find_element_by_android_uiautomator('new UiSelector().description("Animation")')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'self' is not defined
>>> 
 
➜  ~ open .bash_profile 
export ANDROID_HOME=/Users/rrestivo/Library/Android/sdk
export ANDROID_SDK=$ANDROID_HOME

export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
export PATH=$ANDROID_HOME/tools:$PATH
JAVA_HOME=$(/usr/libexec/java_home)
export PATH=${JAVA_HOME}/bin:$PATH

## Link to Appium Logs

https://gist.github.com/ryanrestivo/329797283e55837c920bd8fd83009828

**Comment by ki4070ma** [comment]
Hi @ryanrestivo 

@ "The problem"
> NameError: name 'PATH' is not defined 

`PATH` is defined here. Please have a check that your script can reach to defined `PATH`.
https://github.com/appium/python-client/blob/9e18dfce1ccbe34a5bba3684b054e7f5e22bd229/test/functional/android/helper/desired_capabilities.py#L19

@ "Details"
> self.driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
`self` is unnecessary in your case. 
Please see https://stackoverflow.com/questions/2709821/what-is-the-purpose-of-the-word-self-in-python.

**Comment by ki4070ma** [comment]
If you have any further questions, please visit https://discuss.appium.io.
