### ISSUE TITLE
Unable to perform Swipe from left to right

### ISSUE THREAD

**Issue by Nagesh1504** [appium/python-client#456]
## The problem

I am trying to automate one of the test-case i.e Swipe "Park assistance" from left to right and viva-versa. 
i tried couple of build in functions like swipe, Touch function () but i am unable to perform swipe for the particular icon.

i have used appium python client for this automation.

## Environment
- Appium version - 1.15.0
- Last Appium version that did not exhibit the issue (if applicable): NA
- Desktop OS/version used to run Appium:  windows 8.1 pro
- Node.js version (unless using Appium.app|exe): -
- Mobile platform/version under test: Android 8.1.0
- Real device or emulator/simulator: Real Device
- Appium CLI or Appium.app|exe: -

I have attached the image for more details on which icon to be swipe from left to right direction.

![image](https://user-images.githubusercontent.com/48903263/67206680-c2c76b00-f42f-11e9-8471-a03c4af59f40.png)

@brad , @hugs , @aluedeke  Could please help me on this one.

**Comment by KazuCocoa** [comment]
Please attach the full log. It is necessary to dig your case more.

BTW, did you try http://appium.io/docs/en/commands/interactions/actions/ out?

**Comment by Nagesh1504** [comment]
Hi @KazuCocoa,
i have tried above mentioned link but still it not worked for me.

Could please help me How i can swipe that element by calling it.

**Comment by KazuCocoa** [comment]
This repository has test code about swipe.
https://github.com/appium/python-client/search?q=swipe&unscoped_q=swipe

Could you attach the full Appium server log?
We cannot say something wrong or the cause is Android framework side without any Appium logs.

**Comment by Nagesh1504** [comment]
Sure i  will add the appium logs and the code as well.

**Comment by KazuCocoa** [comment]
Your script failed to find the element of `com.ather.gen2.dashboard.hmi:id/inverseSlider`.
Then, `actions.press(FW_slider).move_to(RV_slider).release().perform()` cannot handle the positon in `press`.

```
[HTTP] --> POST /wd/hub/session/0e682d63-e9f2-4ea0-9f1d-9d17c7f9c53f/element
[HTTP] {"using":"id","value":"com.ather.gen2.dashboard.hmi:id/inverseSlider"}
[W3C (0e682d63)] Calling AppiumDriver.findElement() with args: ["id","com.ather.gen2.dashboard.hmi:id/inverseSlider","0e682d63-e9f2-4ea0-9f1d-9d17c7f9c53f"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 0 ms for condition
[WD Proxy] Matched '/element' to command name 'findElement'
[WD Proxy] Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/6dd37bff-b83f-406c-bfa7-b69d30ce4beb/element] with body: {"strategy":"id","selector":"com.ather.gen2.dashboard.hmi:id/inverseSlider","context":"","multiple":false}
[WD Proxy] Got an unexpected response with status 404: {"sessionId":"6dd37bff-b83f-406c-bfa7-b69d30ce4beb","value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters","stacktrace":"io.appium.uiautomator2.common.exceptions.ElementNotFoundException: An element could not be located on the page using the given search parameters\n\tat io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:78)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:38)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:252)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:242)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.chann...
[W3C] Matched W3C error code 'no such element' to NoSuchElementError
[W3C (0e682d63)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[W3C (0e682d63)]     at AndroidUiautomator2Driver.findElOrEls (C:\Users\emb-nagegna\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-android-driver\lib\commands\find.js:75:11)
[HTTP] <-- POST /wd/hub/session/0e682d63-e9f2-4ea0-9f1d-9d17c7f9c53f/element 404 820 ms - 452
[HTTP] 
```

**Comment by Nagesh1504** [comment]
Hi @KazuCocoa 

Thanks for the help and i have resolved my issue with above mentioned comment. Now Swipe function is working fine by using X and Y coordinates.

Thank you once again for the support.

Thanks & Regards,
Nagesh G
