### ISSUE TITLE
start_activity intent argument missing

### ISSUE THREAD

**Issue by JoahTheron** [appium/python-client#457]
## The problem

If you compare the node js startActivity with the python startActivity method. You will see that you can put more than 2 arguments in the node js method but not in the python method.

The issue with this is, that you can't run any intent with python but you can run it with node js.

## Environment
- Appium version (or git revision) that exhibits the issue: appium@1.15.1
- Last Appium version that did not exhibit the issue (if applicable): - 
- Desktop OS/version used to run Appium: Windows 10 and Mac OsX
- Node.js version (unless using Appium.app|exe): using appium.cmd
- Mobile platform/version under test: Android 10 and 9
- Real device or emulator/simulator: Both
- Appium CLI or Appium.app|exe: Python script?

## Details

My current workaround is by pushing the am start with adb instead of using the appium functions, which is so dirty that i can't sleep well. 

## Code To reproduce issue

Nodejs:

`client.startActivity("xxx.xxx.xxx", ".MainActivity", "", "", "", "", "", "", "");`

Python:
`mDriver.start_activity('xxx.xxx.xxx', '.MainActivity')`

**Comment by KazuCocoa** [comment]
https://github.com/appium/python-client/blob/d679ed8aba7feeb27eede3886ee493595c615c67/appium/webdriver/extensions/android/activities.py#L23-L59

You can add arguments as keyword-arguments.

e.g.

`mDriver.start_activity('xxx.xxx.xxx', '.MainActivity', app_wait_package='your package name')`

**Comment by JoahTheron** [comment]
Thanks a lot. Would appriciate an update on the official documentation about that

**Comment by manoj9788** [comment]
Thanks added https://github.com/appium/python-client/commit/2c305c42badf2c7b43fec716a25b7577559b2fcf
