### ISSUE TITLE
current_activity throws exception with no error

### ISSUE THREAD

**Issue by JoahTheron** [appium/python-client#458]
## The problem

If you try to aquire the current_activity after a sleep in python you get an exception with no error message.

This issue is completly independed of the app itself.

## Environment
- Appium version (or git revision) that exhibits the issue: appium@1.15.1
- Last Appium version that did not exhibit the issue (if applicable): -
- Desktop OS/version used to run Appium: Windows 10 and Mac OsX
- Node.js version (unless using Appium.app|exe): using appium.cmd
- Mobile platform/version under test: Android 10 and 9
- Real device or emulator/simulator: Both
- Appium CLI or Appium.app|exe: Python script?

## Details

After some testing i found out that a sleep of 4 seconds is the limit to keep it working. If you sleep 5 seconds or more you get this weird error.

`Traceback (most recent call last):
  File "C:\Hornify-Projects\hornifya\test.py", line 25, in <module>
    print mDriver.current_activity
  File "C:\Python27\lib\site-packages\appium\webdriver\extensions\android\activities.py", line 68, in current_activity
    return self.execute(Command.GET_CURRENT_ACTIVITY)['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in check_response
    raise wde
selenium.common.exceptions.WebDriverException: Message: 

[Finished in 20.5s with exit code 1]`

## Link to Appium Logs

4 second sleep: https://gist.github.com/JoahTheron/37951c5c47382a9c77cb2861c32b07fe
5 second sleep: https://gist.github.com/JoahTheron/59097aa1fc9d33889b81c1b3dbbd367d

## Code To reproduce issue

`from time import sleep

from appium import webdriver
from selenium.common.exceptions import WebDriverException, NoSuchElementException, StaleElementReferenceException

desired_caps = desired_caps = {
	'platformName': "Android",
	'platformVersion': "10",
	'deviceName': "my New Phone",
	'automationName': "UiAutomator2",
	'appPackage': "xxx.xxx.xxx",
	'appActivity': ".MainActivity",
	'avd': 'device1',
	'systemPort': "4723",
	'dontStopAppOnReset': 'true',
	'noReset': 'false'
}
global mDriver
mDriver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)

print mDriver.current_activity

sleep(10)

print mDriver.current_activity
`

**Comment by JoahTheron** [comment]
I also tried to run python 3.8 instead of 2.7

on both versions you get the same error

**Comment by KazuCocoa** [comment]
Thanks.

note:

- https://github.com/appium/appium-adb/blob/9ee393bc385f138bad48307993dd626be69970d3/lib/tools/apk-utils.js#L185
- https://github.com/appium/appium-android-driver/blob/c0b6fb64483601c710f7afbfbb8e0230e7b19f52/lib/commands/general.js#L105

**Comment by JoahTheron** [comment]
To be honest i don't think the issue is within the method itself. I think that the appium server refuses connections after a 5 sleep. 

Because you dont even get any log messages on the appium server log after it. It just excepts in the python code itself and ignores the request.

Will try to replicate with other functions now.

**Comment by KazuCocoa** [comment]
Thanks.

> [BaseDriver] Shutting down because we waited 60 seconds for a command
[debug] [UiAutomator2] Deleting UiAutomator2 session
[Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[Appium] Removing session 5b4ea934-aaf3-4ce3-8f15-bab205dcd1dc from our master session list
[debug] [UiAutomator2] Deleting UiAutomator2 server session

You can add `newCommandTimeout` to increase the command timeout.

`--log-timestamp`  ( http://appium.io/docs/en/writing-running-appium/server-args/ ) helps to show how long each command took.

**Comment by JoahTheron** [comment]
Thanks for the help you are giving me. I really appriciate it.

Here is another gist: https://gist.github.com/JoahTheron/91e2b69ce270b4b222a5fd224268c430

As you can see the second call of current_activity is not even logged.

**Comment by KazuCocoa** [comment]
Appium parses the response of dumpsys command to detect current activity.
Potentially, the command does not respond on Windows env.

```
C:\Users\Marku\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys window windows
```

What happen when you call the above command a couple of times after 4 sec, 5 sec etc?

**Comment by JoahTheron** [comment]
I have run this command as a subprocess and printing the result afterwards.

```
print(mDriver.current_activity)

subprocess.Popen('C:\\Users\\Marku\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell dumpsys window windows')
print (subprocess)

sleep(10)

subprocess.Popen('C:\\Users\\Marku\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell dumpsys window windows')
print (subprocess)

print(mDriver.current_activity)
```

the adb calls worked great and also showed me the current_activity. In the gist is the python stdout and the appium server logs. 

https://gist.github.com/JoahTheron/e5f715ec1e2c2dc5bfc6f063d2fa098d


Note: I tried to call mDriver.current_activity in a for loop for over 1 trillion times yesterday. It ran flawless. I have also implemented a workaround into this issue. It is so dirty that I kinda have to puke when I see it. 

```
def sleepSheet(time):
	for x in range(time):
		placeholder = mDriver.current_activity
		sleep(1)
```

I just create artificial workload every second if i need to sleep for longer than 4 seconds. 

2nd Note: If you just close the python programm and the emulator is still running the same error appears when you try to relaunch your python script. You have to close the whole appium server with the emulator to make it work again.

**Comment by KazuCocoa** [comment]
I could not reproduce this...
mm.

I picked like the below scenario in this repository's test code.
Capabilities were same as you addressed such as `dontStopAppOnReset` in this description. 

```
    def test_current_activity(self):
        activity = self.driver.current_activity
        self.assertEqual('.ApiDemos', activity)
        time.sleep(10)
        print(self.driver.current_activity)
```

**Comment by JoahTheron** [comment]
This is super weird because my mate copied the exact same code, which I posted you and he got the same error like i am getting.

But I will close this issue since i migrated to node js a week ago anyways. There i have other issues xD
