### ISSUE TITLE
Method has not yet been implemented

### ISSUE THREAD

**Issue by kscp123** [appium/python-client#464]
I use python3.6，version appnium desktop 1.7.1. When I use the method screenshot or screenshot_as_base64 error occurs:
selenium.common.exceptions.WebDriverException: Message: Method has not yet been implemented What's wrong is it?

**Comment by kscp123** [comment]
the platform is windows10

**Comment by KazuCocoa** [comment]
> the platform is windows10

Do you mean https://github.com/microsoft/WinAppDriver ?

It is appreciated if you could attach the Appium server side log to check where the message came from. I assume you should update Appium server side.

**Comment by kscp123** [comment]
@KazuCocoa I mean I use Appium-Python-Client package and python code on windows try to control Android APP.  But the python reports this error when I use screenshot or screenshot_as_base64 method.
I will try to update my Appnium server as well.

**Comment by KazuCocoa** [comment]
Okay.
I forgot the exact version, but newer Appium support taking an element screenshot.
Let us know if such not implementation error happened in the newer version.

**Comment by kscp123** [comment]
> Okay.
> I forgot the exact version, but newer Appium support taking an element screenshot.
> Let us know if such not implementation error happened in the newer version.

Yes, after I update the server, problem solved. Thanks.
