### ISSUE TITLE
Python 2 deprecation

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/python-client#468]
January 1st of 2020 is the EOL for Python2. I would say it makes sense to start working on python client version 2 (for us this is going to be `1.0.0`), which only supports python 3 (preferably Python 3.7+)

List of things I would like to see in the new major release (suggestion are highly welcome):
- Explicit types declarations (use `typing` module) -> High priority
- asyncio and async/await usage (for both network and file system i/o operations) -> Medium to Low priority, this might be a serious change and might require the users to update a lot of their code
- Proper exceptions inheritance  (use `raise from`) -> High priority
- Ordered dictionaries usage -> High priority
- Proper strings/bytearrays usage -> High priority
- Proper `super` usage -> High priority
- pytest usage -> Medium priority

**Comment by ki4070ma** [comment]
As internal tasks

- [ ] Remove py2 from travis ci and run py38
   - https://github.com/appium/python-client/blob/master/.travis.yml
- [ ] Upgrade dependencies
   - https://github.com/appium/python-client/blob/master/Pipfile

**Comment by manoj9788** [comment]
Thanks @mykola-mokhnach  Absolutely makes sense to start this work now!

**Comment by ki4070ma** [comment]
Action sequence

https://github.com/appium/python-client/pull/478#issuecomment-570939200

**Comment by mykola-mokhnach** [comment]
One more useful things which is present since Python 3.7 and which we could use: 

- [Data classes](https://realpython.com/python-data-classes/)

**Comment by ki4070ma** [comment]
Might need to add `py.typed` file to repository. Will check later.

https://www.python.org/dev/peps/pep-0561/

**Comment by KazuCocoa** [comment]
Python 2.7.18 came out

**Comment by ki4070ma** [comment]
Done
