### ISSUE TITLE
webdriver.Remote is missing

### ISSUE THREAD

**Issue by tyaff** [appium/python-client#476]
According to Appium API doc:
http://appium.io/docs/en/commands/session/create/index.html

I am supposed to use webdriver.Remote etc:

desired_caps = desired_caps = {
  'platformName': 'Android',
  'platformVersion': '7.0',
  'deviceName': 'Android Emulator',
  'automationName': 'UiAutomator2',
  'app': PATH('/path/to/app')
}
self.driver = webdriver.Remote('http://127.0.0.1:4723', desired_caps)

However, its missing from appium.webdriver is webdriver.RemoteCommand the replacement?

**Comment by KazuCocoa** [comment]
How did you import the module?

It should be like this https://github.com/appium/python-client#usage

```
from appium import webdriver
...
self.driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
```

**Comment by tyaff** [comment]
I made a mistake I acciently put 

`from appium.webdriver import webdriver`

Thanks,
