### ISSUE TITLE
How to handle scrollView in ios 7 app.

### ISSUE THREAD

**Issue by luisxiaomai** [appium/python-client#50]
Hi All,

I have an ios app with welcome sliders when you first launch. It contains 5 UIAImages in UIAscrollView.

I want to swipe it one by one, I see solution in appium doc like:

"An unfortunate bug exists in the iOS 7.x Simulator where ScrollViews don’t recognize gestures initiated by UIAutomation (which Appium uses under the hood for iOS). To work around this, we have provided access to a different function, scroll, which in many cases allows you to do what you wanted to do with a ScrollView, namely, scroll it!".

I used python-client libarary API---Scroll to handle this, but it doesn't work. Element can't scroll by offset. I see java sample code in appium document, can anyone help this and give python sample code.

Thanks

**Comment by KazuCocoa** [comment]
close because of:

> Apple's XCUITest library is only available on iOS simulators and devices that are running iOS 9.3 or higher.

https://github.com/appium/appium/blob/master/docs/en/drivers/ios-xcuitest.md
