### ISSUE TITLE
Failed to locate opened application window with appId

### ISSUE THREAD

**Issue by reinaldo-gomes** [appium/python-client#504]
## The problem

I'm trying to test an XBAP application, but I get this error:
selenium.common.exceptions.WebDriverException: Message: Failed to locate opened application window with appId: C:/path.xbap, and processId: 31604

## Environment
- Appium version (or git revision) that exhibits the issue: 0.50
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: Windows 10 - 1903
- Node.js version (unless using Appium.app|exe): using WinAppDriver 1.1
- Mobile platform/version under test:
- Real device or emulator/simulator:
- Appium CLI or Appium.app|exe:

## Details

This problem has been solved [here](https://github.com/microsoft/WinAppDriver/issues/213#issuecomment-322960439) but it's in C# and I can't figure out how to port it to Python. Can anybody help me on this?

## Link to Appium Logs

https://gist.github.com/reinaldo-gomes/8d9e3d3d68084d522ed3b19187d034eb

## Code To reproduce issue
from appium import webdriver

desired_caps = {}
desired_caps["app"] = "C:/path.xbap"
driver = webdriver.Remote(command_executor='http://127.0.0.1:4723', desired_capabilities=desired_caps)

**Comment by KazuCocoa** [comment]
Does the log mean failed to create a session?

Windows handler is `driver.window_handles`, but the log seems failed to create a session. Then, asking in https://github.com/microsoft/WinAppDriver is more proper than here, I think.

**Comment by reinaldo-gomes** [comment]
Well, yes, it does, and that's what puzzles me the most about applying their suggested C# solution, since I don't even have the chance to relaunch/switch to anything.

Could you please take a look at their answer in my previous post's link and ser If you have any clue on how to port that solution to python??

**Comment by KazuCocoa** [comment]
```
windows_handles = driver.window_handles
driver.switch_to.window(windows_handles[0])
```

is an alternative of

```
var allWindowHandles = session.WindowHandles;
session.SwitchTo().Window(allWindowHandles[0]);
```

in C#.
