### ISSUE TITLE
Is there an intersphinx mapping for appium

### ISSUE THREAD

**Issue by PhilippSelenium** [appium/python-client#507]
## The problem

Is/will an intersphinx mapping https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html be available for the appium python client?

## Examples
https://www.selenium.dev/selenium/docs/api/py/objects.inv

**Comment by ki4070ma** [comment]
Hi @PhilippSelenium 

Thanks for your report, it's unavailable now.

[Notes] will take a look details after https://github.com/appium/python-client/issues/439

**Comment by ki4070ma** [comment]
Hi @PhilippSelenium 

Here is what you expected?
https://github.com/appium/python-client-sphinx/blob/master/docs/objects.inv

**Comment by PhilippSelenium** [comment]
@ki4070ma Yes, thanks. But I will be using that link: https://appium.github.io/python-client-sphinx/objects.inv
