### ISSUE TITLE
'TouchAction' object has no attribute 'flick_element'

### ISSUE THREAD

**Issue by KageyamaRuka** [appium/python-client#512]
## The problem

'TouchAction' object has no attribute 'flick_element'

## Environment
- Appium version (or git revision) that exhibits the issue: 1.17.0
- Desktop OS/version used to run Appium: MacOS 10.15.3
- Node.js version (unless using Appium.app|exe): v13.11.0
- Mobile platform/version under test: iOS 13.3.1
- Real device or emulator/simulator: Real device
- Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium Logs

[log.txt](https://github.com/appium/python-client/files/4455646/log.txt)

## Code To reproduce issue

![image](https://user-images.githubusercontent.com/24635872/78886353-a1674380-7a90-11ea-9076-41549b2f7972.png)

**Comment by ki4070ma** [comment]
Hi

You can use `flick` from `ActionHelpers`.

https://github.com/appium/python-client/blob/master/appium/webdriver/extensions/action_helpers.py#L130

Need to update docs.

http://appium.io/docs/en/commands/interactions/touch/flick/

**Comment by KazuCocoa** [comment]
TouchAction is deprecated. Please use W3C actions instead.
