### ISSUE TITLE
Why pyinstaller breaks appium code when making executable?

### ISSUE THREAD

**Issue by Karraya** [appium/python-client#513]
So when I run my code from the commandline everything work as expected. It when I try to make the .exe file using:

Pyinstaller -w -F mypythoncode.py

The GUI shows up as expected but the code breaks on this line.

Service = AppiumService ()

Service.start() # The code breaks here. Any idea???

Code ...

Service.stop()

**Comment by ki4070ma** [comment]
Hi @Karraya 

Could you fill out bellow template?
Thanks.

https://github.com/appium/python-client/blob/master/.github/issue_template.md

**Comment by Karraya** [comment]
@ki4070ma I created on as you requested and posted my code as well. Please see link below. 

https://gist.github.com/Karraya/2c28907ff832263a5364fff894c1d46b 

@brad @hugs @filmaj

**Comment by Karraya** [comment]
@ki4070ma This is the error I am getting. 

Error: Cannot find module 'appium/build/lib/main.js'
 Any idea how to fix it on Linux? I added the path to the .bashrc file but doesn't help.

**Comment by ki4070ma** [comment]
Could you update this PR's description like as https://github.com/appium/python-client/issues/483?

https://github.com/appium/python-client/issues/513#issuecomment-612520672

**Comment by ki4070ma** [comment]
Closed for inactive.

**Comment by lpwlee** [comment]
I've experienced the same issue after 4 years. running the script with python filename.py working ok but got error when filename.exe is called.

Traceback (most recent call last):
  File "filename.py", line 2, in <module>
    from appium import webdriver
ModuleNotFoundError: No module named 'appium'
