### ISSUE TITLE
Not getting code completion autosuggestions outside driver declaration

### ISSUE THREAD

**Issue by hadrianjmnz90** [appium/python-client#520]
## The problem

I do not get code completion suggestions outside the driver declaration, i am using pycharm 2019.1.3, this is very annoying because i have to go where the driver is declared and write the code there and then copy it to another methods. 

## Environment
- Appium version (or git revision) that exhibits the issue: 1.15.1
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: Mac OS 10.14.5
- Node.js version (unless using Appium.app|exe): 12.11.1
- pycharm version: 2019.1.3 
## Code To reproduce issue
```
from appium import webdriver
import pytest
```

```
driver = None
@pytest.fixture()
def driver(request):
    global  driver
    url = 'https://medium.com/'
    platform_name = "android"
```

    if platform_name == "android":
        desired_caps = {
            'platformName': 'Android',
            'platformVersion': '7.1.1',
            'automationName': 'uiautomator2',
            'deviceName': '4b64d0f3',
            "app": "/Users/hectorjimenez/Documents/apps/myapp.apk",
            'FullReset': False,
            'NoReset': True,
            'newCommandTimeout': 300

            }

    elif platform_name == "ios":
        desired_caps = {
            'platformName': 'iOS',
            'platformVersion': '12.2',
            'deviceName': 'iPhone 8',
            "app": "/Users/hectorjimenez/Documents/apps/myapp.app",
            'automationName': 'XCUITest',
            'FullReset': False,
            'NoReset': True,
            'newCommandTimeout': 300
            }

    driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
    driver.implicitly_wait(10)
    request.cls.driver = driver
    yield

```
def test():
    driver.
```
![Screen Shot 2020-04-16 at 10 58 51 AM](https://user-images.githubusercontent.com/52982608/79478705-5938ab80-7fd1-11ea-9c99-06907962208e.png)
`

**Comment by ki4070ma** [comment]
[Notes]

As fixture usage, it should be like below.
But it still doesn't work.

```
def test(driver):
    driver.
```

Since the appium python client for python3 ver has type hint, I hope auto completion works for it. Need to check.

**Comment by ki4070ma** [comment]
By checking with the appium python client for python3 ver, it still doesn't work.

@hadrianjmnz90 
As the solution for what you want to do, please use type hint like below.

```
@pytest.fixture()
def driver(request) -> webdriver.webdriver.WebDriver:
```


![image](https://user-images.githubusercontent.com/1549855/81027397-98fc0000-8eb8-11ea-9eb1-044509ea447c.png)

**Comment by hadrianjmnz90** [comment]
@ki4070ma could you share your project interpreter settings? and the complete code you are using? , i implemented what you suggested in comment above and i still do not get the suggestions.
