### ISSUE TITLE
Problem trying to setup start_screen_recording in python

### ISSUE THREAD

**Issue by munchkin09** [appium/python-client#528]
## The problem

I can not change the params of start_screen_recording in iOS. Im faced a problem when triying to start a video record in a iOS phone, i try to pass some parameters to the method, but i dont see any changes in output of the method

## Environment
- Appium version (or git revision) that exhibits the issue: Appium v1.15.1
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: MacOS Catalina
- Node.js version (unless using Appium.app|exe): v13.7.0
- Mobile platform/version under test: iOS 11.4
- Real device or emulator/simulator: Real Device
- Appium CLI or Appium.app|exe: CLI

## Link to Appium Logs

[GIST](https://gist.github.com/munchkin09/6b10759ed39e7e0f9802764f9d6dd3ac)
Line 857 and so on
## Code To reproduce issue

options = {}
options['timeLimit']="600"
options['videoQuality']="low"
options['videoType']="libx264"
options['remotePath']='ftp'
self.driver.start_recording_screen(options=options)

**Comment by mykola-mokhnach** [comment]
Please use the most recent server version

**Comment by munchkin09** [comment]
I already bump version of appium to 1.17.0 Added to the gist the new log output, but the same result its returned.
[LOG APPIUM 1.17.0](https://gist.github.com/munchkin09/6b10759ed39e7e0f9802764f9d6dd3ac#file-log-appium-1-17-0-L596)

**Comment by mykola-mokhnach** [comment]
> self.driver.start_recording_screen(options=options)

This won't work. `options` is of type `kwargs`. See https://github.com/appium/python-client/blob/eb6a659f12e82a8ef9dfbe6a7b26fb8c7809319b/test/unit/webdriver/screen_record_test.py#L28

**Comment by munchkin09** [comment]
Now i see that the videoType is changed thats good news, but i dont understand the remotePath option, i try to change the destination port to capture the stream with my own process of ffmpeg, but the streaming is still in 127.0.0.1:9100, but i want to use, for example, the http://127.0.0.1:9111 ip:port, am i misunderstanding something about the remotePath option? 
Im trying to capture video from several devices at the same time thats why i need to change the default stream output, but i dont know if remotePath its the correct way to do that.
Thanks in advance, and sorry for bother you.

**Comment by KazuCocoa** [comment]
The remotePath is below.

> The remotePath upload option is the path to the remote location

https://github.com/appium/python-client/blob/9c597a3afe76ff1283c45259ed6e1c4aadac530d/appium/webdriver/extensions/screen_record.py

`mjpegServerPort` is the port maybe you adressed.

**Comment by ki4070ma** [comment]
If you have further questions, please ask here https://discuss.appium.io/ .
