### ISSUE TITLE
Editable field methods of webelement work not stable on Android

### ISSUE THREAD

**Issue by ianxiaohanxu** [appium/python-client#53]
The involved methods include: send_keys(), clear(), set_text()

First, let's talk about: clear() and set_text()
![555](https://cloud.githubusercontent.com/assets/8499658/4197773/f3492c94-37ee-11e4-9aba-b5cb36830937.png)

I select the input field element with find_element_by_android_uiautomator('text("%s")' %text), find it by text info 'Rtyy'. And then if i use element.clear() or element.set_text('xxxx'), an exception raised, NoSuchElementException. Actually, these two methods did something, they deleted the text 'Rtyy' at least. But after they finished delete action, they tried to find the input field element with the original text 'Rtyy' which was deleted, so they cannot find it, and raise the exception.

And the let's talk about send_keys()
![666](https://cloud.githubusercontent.com/assets/8499658/4197792/36469a2c-37ef-11e4-9dd5-605d0a1783ab.png)

Look, it is an empty input field. The 'Type message' is nothing. If i use element.send_keys('hello'), guess what happened. 'Type messagehello' input.

Did anybody else find this issue?

**Comment by ki4070ma** [comment]
If this error still occurs, please reopen.
