### ISSUE TITLE
Package as PEP 561 compatible

### ISSUE THREAD

**Issue by juandg** [appium/python-client#537]
## The problem

Even though the Appium python-client now supports [PEP 484](https://www.python.org/dev/peps/pep-0484/) and is typed, for client code using mypy or any other type checker the type information is not accessible since the library is not being packaged as [PEP 561](https://www.python.org/dev/peps/pep-0561/) compatible

There's more info on the PEP and here:
https://mypy.readthedocs.io/en/latest/installed_packages.html#installed-packages

## Environment
- Appium python-client 0.52

**Comment by KazuCocoa** [comment]
Thanks :)
The new version which includes the type stuff hasn't pushed yet.
Will take a look at the link.

**Comment by juandg** [comment]
I was looking at master thinking this was the code for 0.52 😞

I guess I just too excited to see these changes to check which branch I was on 😄Looking forward to the new version 🎉

**Comment by KazuCocoa** [comment]
I've added `py.typed` in the package.
Next release (will be 1.0.0) has it :)
