### ISSUE TITLE
module 'appium.webdriver' has no attribute 'Remote'

### ISSUE THREAD

**Issue by refaelsh** [appium/python-client#542]
## The problem

I have the same issue as this: https://github.com/appium/python-client/issues/476.
His solution is not applicable to my case.

Here is the shortest possible code that reproduces the issue:

```
from appium import webdriver

driver = webdriver.Remote('http://localhost:4723/wd/hub', [])
```

The result is like this:

```
C:\Python36\python.exe C:/Users/rsheink/PycharmProjects/untitled/bla.py
Traceback (most recent call last):
  File "C:/Users/rsheink/PycharmProjects/untitled/bla.py", line 3, in <module>
    driver = webdriver.Remote('http://localhost:4723/wd/hub', [])
AttributeError: module 'appium.webdriver' has no attribute 'Remote'

Process finished with exit code 1
```

Please help :-)

**Comment by GlennJC** [comment]
@refaelsh Can you confirm what version of the Appium Python client you are using? 

Did a new install this morning and got v1.0.0. From what I can see so far, there is something broken in this release. Code that has been working for months completely stopped. There is no webdriver.Remote (same issue you are having), and the common namespace has completely disappeared (I stopped looking at that point). Went back to v0.52 and everything is working again.

I'm using Python 3.8.2

**Comment by Aderlx** [comment]
what's wrong with v1.00?

**Comment by GlennJC** [comment]
> 
> 
> what's wrong with v1.00?

Its in my message, however consider the following code that passes validation under 0.52:

``` python
from appium import webdriver
from appium.webdriver.common.mobileby import MobileBy

desired_caps = {"app": "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App"}
driver = webdriver.Remote(
    command_executor='http://127.0.0.1:4723',
    desired_capabilities=desired_caps)

control = (MobileBy.ACCESSIBILITY_ID, 'MenuItemsHost')
```

When run under 0.52, works fine.  Under v1.0.0..

```
C:\Testing>python appium_test.py
Traceback (most recent call last):
  File "appium_test.py", line 2, in <module>
    from appium.webdriver.common.mobileby import MobileBy
ModuleNotFoundError: No module named 'appium.webdriver.common'

Traceback (most recent call last):
  File "appium_test.py", line 5, in <module>
    driver = webdriver.Remote(
AttributeError: module 'appium.webdriver' has no attribute 'Remote'
```

This is on a brand new (as in the machine is freshly built) installation of Python 3.8.2 and Appium 1.0.0

**Comment by ki4070ma** [comment]
@GlennJC 

Could you try to run some functional tests in python-client?

https://github.com/appium/python-client/tree/master/test/functional

### FYI

I could run functional test as below with Appium-Python-Client 1.0.0.

```
➜  test git:(master) pip install Appium-Python-Client    
Collecting Appium-Python-Client
  Using cached Appium-Python-Client-1.0.0.tar.gz (51 kB)
Requirement already satisfied: selenium<4,>=3.14.1 in /Users/atsushimori/.pyenv/versions/3.8.1/lib/python3.8/site-packages (from Appium-Python-Client) (3.141.0)
Requirement already satisfied: urllib3 in /Users/atsushimori/.pyenv/versions/3.8.1/lib/python3.8/site-packages (from selenium<4,>=3.14.1->Appium-Python-Client) (1.25.9)
Building wheels for collected packages: Appium-Python-Client
  Building wheel for Appium-Python-Client (setup.py) ... done
  Created wheel for Appium-Python-Client: filename=Appium_Python_Client-1.0.0-py3-none-any.whl size=8803 sha256=35ea5b77bc25bccca8b03d5e2130323139b6a0d1091b404f48733be8f3f7c974
  Stored in directory: /Users/atsushimori/Library/Caches/pip/wheels/9f/04/d8/8e500f1885940074c5f40f8be1ef17386789790999f252b238
Successfully built Appium-Python-Client
Installing collected packages: Appium-Python-Client
Successfully installed Appium-Python-Client-1.0.0
➜  test git:(master) pip show Appium-Python-Client
Name: Appium-Python-Client
Version: 1.0.0
Summary: Python client for Appium
Home-page: http://appium.io/
Author: Isaac Murchie
Author-email: isaac@saucelabs.com
License: Apache 2.0
Location: /Users/atsushimori/.pyenv/versions/3.8.1/lib/python3.8/site-packages
Requires: selenium
Required-by: 
➜  test git:(master) pwd                                   
/Users/atsushimori/github/ki4070ma/python-client/test
➜  test git:(master) pytest functional/android/ime_tests.py
.....                                                                                                                                           [100%]

---------- coverage: platform darwin, python 3.8.1-final-0 -----------
Name                                                                                                                 Stmts   Miss  Cover
----------------------------------------------------------------------------------------------------------------------------------------
/Users/atsushimori/github/ki4070ma/python-client/appium/__init__.py                                                      1      0   100%
(--snip--)
/Users/atsushimori/github/ki4070ma/python-client/appium/webdriver/webelement.py                                         45     27    40%
----------------------------------------------------------------------------------------------------------------------------------------
TOTAL                                                                                                                 1678    913    46%

5 passed in 39.68s
```

**Comment by mykola-mokhnach** [comment]
> C:\Python36\python.exe

@refaelsh Only Python 3.7+ is supported


@GlennJC 

>   File "appium_test.py", line 2, in <module>
>     from appium.webdriver.common.mobileby import MobileBy
> ModuleNotFoundError: No module named 'appium.webdriver.common'

Are you sure your PYTHONPATH is correct and there are no modules there or in the current dir, that might override the original python client imports?

**Comment by Git-ZRJ** [comment]
uninstall v1.00 and install v0.52 is workable,thx @GlennJC

**Comment by refaelsh** [comment]
> @refaelsh Can you confirm what version of the Appium Python client you are using?

Version 1.0.0

**Comment by refaelsh** [comment]
> > C:\Python36\python.exe
> 
> @refaelsh Only Python 3.7+ is supported

I cant use Python 3.7. Its a corporate laptop, the only allowed Python version 3.6.x.

**Comment by GlennJC** [comment]
> 
> 
> @GlennJC
> 
> Could you try to run some functional tests in python-client?
> 
> https://github.com/appium/python-client/tree/master/test/functional
> ### FYI
> 

I presume  you require some sort of Android emulator running for those tests? I only use Appium for Windows-based application tests so don't have any iOS or Android emulators installed.

```
C:\Test2>pip install Appium-Python-Client
Requirement already satisfied: Appium-Python-Client in c:\program files (x86)\python38-32\lib\site-packages (1.0.0)
Requirement already satisfied: selenium<4,>=3.14.1 in c:\program files (x86)\python38-32\lib\site-packages (from Appium-Python-Client) (3.141.0)
Requirement already satisfied: urllib3 in c:\program files (x86)\python38-32\lib\site-packages (from selenium<4,>=3.14.1->Appium-Python-Client) (1.25.9)

C:\Test2>pip show Appium-Python-Client
Name: Appium-Python-Client
Version: 1.0.0
Summary: Python client for Appium
Home-page: http://appium.io/
Author: Isaac Murchie
Author-email: isaac@saucelabs.com
License: Apache 2.0
Location: c:\program files (x86)\python38-32\lib\site-packages
Requires: selenium
Required-by:
```

**Comment by GlennJC** [comment]
> Are you sure your PYTHONPATH is correct and there are no modules there or in the current dir, that might override the original python client imports?

100% positive, how would I confirm this though?

The machine is literally a fresh install of Windows 10, and then the following commands executed:

```
python-3.8.2.exe /quiet InstallAllUsers=1 PrependPath=1
python -m pip install --upgrade pip
pip.exe install Appium-Python-Client
pip.exe install numpy
pip.exe install -U pylint
pip.exe install pytest
pip.exe install pytest-html
pip.exe install pywin32
pip.exe install wmi
pip.exe install urllib3
```

The test example I provided earlier was in a brand new empty directory with only that file located in it.

Path is

```
Path=C:\Program Files (x86)\Python38-32\Scripts\;C:\Program Files (x86)\Python38-32\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Users\Install\AppData\Local\Microsoft\WindowsApps;
```

there is no PYTHONPATH variable

Not sure where else to look.

**Comment by PhilippSelenium** [comment]
Having same issue  using python 3.7
 ```from appium.webdriver import Remote```
Throws import error

**Comment by mykola-mokhnach** [comment]
I assume the import should look like `from appium.webdriver.webdriver import WebDriver`

**Comment by mykola-mokhnach** [comment]
The above import works because of 

> from .webdriver import WebDriver as Remote

declaration in

`python-client/appium/webdriver/__init__.py`

Make sure it's there. The path to the actual used module could be checked by printing the internal `__file__` property of a module

**Comment by PhilippSelenium** [comment]
Should the usage information in the README https://github.com/appium/python-client#usage be updated then?

**Comment by PhilippSelenium** [comment]
```from appium.webdriver.webdriver import WebDriver```
Doesn't work for me either.

**Comment by mykola-mokhnach** [comment]
@PhilippSelenium Have you checked the actual location of the modules according to what was mentioned above?

**Comment by mykola-mokhnach** [comment]
In general it is highly recommended to always wrap your project into a virtual environment. This helps to avoid the most of dependency issues (if not all). We use https://github.com/pypa/pipenv for the current client.

**Comment by PhilippSelenium** [comment]
@mykola-mokhnach Yes, I'm of course working in a python 3.7 virtualenv where I only install Appium-Python-Client
```
pip show

Name: Appium-Python-Client
Version: 1.0.0
Summary: Python client for Appium
Home-page: http://appium.io/
Author: Isaac Murchie
Author-email: isaac@saucelabs.com
License: Apache 2.0
Location: ~/.virtualenvs/test-python3.7/lib/python3.7/site-packages
Requires: selenium
Required-by: 
```

```
ls ~/.virtualenvs/test-python3.7/lib/python3.7/site-packages/appium
__init__.py  __pycache__  version.py  webdriver

ls ~/.virtualenvs/test-python3.7/lib/python3.7/site-packages/appium/webdriver/
py.typed
```

**Comment by mykola-mokhnach** [comment]
^ 
This look bad. Very bad.
It looks like package files were not uploaded to pip repository upon releasing.

@KazuCocoa @ki4070ma Could you please verify the release was successful and reupload it as a patch if necessary?

**Comment by mykola-mokhnach** [comment]
I've double checked the archive at https://files.pythonhosted.org/packages/43/8b/2cb171b3254cb4febe03b3b44a2869d7c41db4293f45564ab59b12193718/Appium-Python-Client-1.0.0.tar.gz and it does contain all the necessary stuff...

**Comment by KazuCocoa** [comment]
Okay. Will check it later, but https://pypi.org/project/Appium-Python-Client/1.0.0/#files looks good as a quick check.

**Comment by mykola-mokhnach** [comment]
This looks like a packaging issue. We'll republish the patched package soon

**Comment by ki4070ma** [comment]
As I commented as below, it worked.

https://github.com/appium/python-client/issues/542#issuecomment-629936125

And I've checked in my local environment, but it's same to below situation.

https://github.com/appium/python-client/issues/542#issuecomment-630095670

I'll check it for details.

**Comment by KazuCocoa** [comment]
Thanks for the report. 1.0.1 should fix this.
`py.typed` for type hint is also in `appium/webdrive`

**Comment by chethank1990** [comment]
Use this
driver =webdriver.WebDriver( 'http://localhost:4723/wd/hub', desired_cap )

**Comment by vakennu** [comment]
Sorry, but 5 years later I'm running into this issue. 

> Use this driver =webdriver.WebDriver( 'http://localhost:4723/wd/hub', desired_cap )

Was this the solution?
