### ISSUE TITLE
Can't find library. Case sensitive 'appium-python-client' 

### ISSUE THREAD

**Issue by aydorovs** [appium/python-client#546]
## The problem

Hello.  I run my tests, but the appium library is not found by 'Appium-Python-Client'

## Environment
Linux alpinelinux
Appium-Python-Client 1.0.1
pip version 19.2.3

## Details
command
- pip3 install -r requirements.txt

## requirements.txt:
Appium-Python-Client

## Error:

>  ImportError while loading conftest '/builds/autotests/conftest.py'.
>  conftest.py:4: in <module>
>      from utils.application import Application
>  utils/application.py:5: in <module>
>      from model.Screen import Screen
>  model/Screen.py:5: in <module>
>      from appium.webdriver.common.mobileby import MobileBy
>  E   ModuleNotFoundError: No module named 'appium.webdriver.common'

I change it  to 'appium-python-client' in  requirements.txt and my tests bild successfully. Why?

**Comment by KazuCocoa** [comment]
Did it happen with Python 1.0.1?
I fixed a package issue in 1.0.0 a bit before. https://github.com/appium/python-client/pull/545
So, I wondered the error was 1.0.0

**Comment by aydorovs** [comment]
from my pipeline
![image](https://user-images.githubusercontent.com/47498749/82229735-7eec0400-9933-11ea-867c-b142e7b7bf28.png)

**Comment by KazuCocoa** [comment]
Can you specify Appium-Python-Client==1.0.1?
If it could work, maybe pypi has cache. Need to wait for a bit, I think.

I tested both `appium-python-client==1.0.1` and `Appium-Python-Client==1.0.1` in requirements.txt after the push and ensured it succeeded.

**Comment by aydorovs** [comment]
maybe. okay, thanks)
