### ISSUE TITLE
TouchAction.tap can't perform tap with same time interval .  it takes about 8s for 20 times of taps with default time interval

### ISSUE THREAD

**Issue by 201905270246** [appium/python-client#548]
## The problem

i performed 20 times of tap within 100ms time interval continuously. But it took about  8s total, which meant 400ms time interval in average. This is not touching but clicking.

## Environment
- Appium version (or git revision) that exhibits the issue: 1.17.1
- Last Appium version that did not exhibit the issue (if applicable): 1.15.+
- Desktop OS/version used to run Appium: Both MAC and Ubuntu
- Node.js version (unless using Appium.app|exe): v12.16.3
- Mobile platform/version under test: Android/8.0.0
- Real device or emulator/simulator: Real device/MI 6 
- Appium CLI or Appium.app|exe: Appium.exe

## Details

python script as below:

```
from appium.webdriver.common.touch_action import TouchAction
import datetime
start_time = datetime.datetime.now()
TouchAction(driver).tap(x='540', y='122', count=20).release().perform()
end_time = datetime.datetime.now()
print(end_time-start_time)
```
Total duration is 0:00:08.351997

## Link to Appium Logs

 [appium.log](https://gist.github.com/201905270246/2098cdde90c4805cda63825bcda089b0)

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/java-client/issues/1322

**Comment by ki4070ma** [comment]
I've checked with below environments and your sample codes, but performances are same on each.

Performance: around `4sec.`.

## Environment
- Appium version (or git revision) that exhibits the issue: 1.15.1, 1.17.1, 1.18.0-beta.1
- Desktop OS/version used to run Appium: macOS10.15.6
- Node.js version (unless using Appium.app|exe): v14.2
- Mobile platform/version under test: Android10
- Real device or emulator/simulator: Real device/MI 10 
- Appium CLI or Appium.app|exe: CLI

@201905270246 
Could you check performance again with 1.15.1, 1.17.1, 1.18.0-beta.1?

**Comment by mykola-mokhnach** [comment]
I suppose it won't be much better in later versions because of multiple reasons. Consider switching to W3C actions instead.

**Comment by KazuCocoa** [comment]
Please consider to build actions with W3C actions.
TouchActions is deprecated for now.
