### ISSUE TITLE
Python Android Double Click

### ISSUE THREAD

**Issue by Alex-Xcl** [appium/python-client#550]
## The problem

Python Appium-Python-Client==1.0.1   no method   double_tap

## Environment

* Appium version (or git revision) that exhibits the issue :1.7.1  
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Windows 10
* Node.js version (unless using Appium.app|exe):1.4.2
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 7,9
* Real device or emulator/simulator:Real devices
* Appium CLI or Appium.app|exe:

## Details

![image](https://user-images.githubusercontent.com/50492028/85424348-64e4b780-b5aa-11ea-9309-095c69d04687.png)

no  double_tap 
I try  like this  "TouchAction(driver).tap(x=300,y =400,counts =2).release().perform()"  ,in videoplayer ---ijkplayer  ,the action only one click()

**Comment by Akulavenkatesh** [comment]
Hi, can you replace counts=2 with count=2 and give it a try? Also I don't think release() is required in double tab since its a quick action. Try the below two variations:
```
TouchAction(driver).tap(x=300, y =400, count=2).perform()
TouchAction(driver).tap(x=300, y =400, count=2).release().perform()
```

**Comment by KazuCocoa** [comment]
Perhaps when the document was updated, a person referred below selenium's touch actions.
https://www.selenium.dev/selenium/docs/api/py/webdriver/selenium.webdriver.common.touch_actions.html

**Comment by Alex-Xcl** [comment]
Thinks
