### ISSUE TITLE
Updating server settings through capabilities

### ISSUE THREAD

**Issue by arthuRHD** [appium/python-client#553]
## The problem

As mentionned [here](https://appium.io/docs/en/writing-running-appium/caps/#update-settings), we should be able to update server settings with client capabilities. However, i've encountered a value error from appium. Some of the server settings for the BaseDriver were updated. But not `shutdownOnPowerDisconnect` which is for UiAutomator2.

## Environment
- Appium version (or git revision) that exhibits the issue: 1.17.0
- Desktop OS/version used to run Appium: Ubuntu 20.04
- Node.js version (unless using Appium.app|exe): 10.19.0
- Mobile platform/version under test: 5.1.1
- Real device or emulator/simulator: both
- Appium CLI or Appium.app|exe: Appium CLI 

## Details

Declared in my script :
```py
caps = {
    ...
    "settings[shutdownOnPowerDisconnect]": False,
    "settings[fixImageTemplateSize]": 0,
    "settings[getMatchedImageResult]": 1,
    "settings[imageMatchThreshold]" : OPENCV_MATCH_THRESHOLD
}
```
Parsed by appium : 
```log
[debug] [WD Proxy] Proxying [POST /appium/settings] to [POST http://127.0.0.1:8200/wd/hub/session/[session_id]/appium/settings] with body: {"settings":{"shutdownOnPowerDisconnect":[false]}}
```

## Link to Appium Logs

[GIST](https://gist.github.com/arthuRHD/59c0478b9fa4233e339a7f1719920722)

**Comment by arthuRHD** [comment]
This will work but it isn't updating server settings with client capabilities
```py
driver.update_settings({
        "shutdownOnPowerDisconnect]": 0,
        "fixImageTemplateSize]": 0,
        "getMatchedImageResult]": 1,
        "imageMatchThreshold]" : OPENCV_MATCH_THRESHOLD
    })
```

**Comment by mykola-mokhnach** [comment]
> "shutdownOnPowerDisconnect":[false]

Please attach the whole server log. For now it looks like the value received from the client has an invalid value (array instead of boolean)

**Comment by arthuRHD** [comment]
[GIST](https://gist.github.com/arthuRHD/978c0f434cad6fd154d08461f329f4da)

**Comment by arthuRHD** [comment]
Not sure if this will help, but appium is running inside a docker container. I've tested with multiple version of the appium image and the error is the same.

Do you think it's only https://github.com/appium/appium-docker-android which is concerned by this issue, or it might have something to do with the client ?

**Comment by mykola-mokhnach** [comment]
> [HTTP] {"capabilities":{"firstMatch":[{"appium:app":"scanmobile_e2e/e2e/utils/apps/tested.apk","appium:fullReset":true,"appium:clearSystemFiles":true,"platformName":"Android","appium:automationName":"UiAutomator2","appium:deviceName":"MC18N0","appium:allowTestPackage":true,"appium:udid":"17117523021209","appium:platformVersion":"5.1.1","appium:appWaitPackage":"com.budgetbox.appmetromc","appium:appWaitActivity":"com.budgetbox.mcspecific.diagnostic.ui.DiagnosticActivity","appium:settings[shutdownOnPowerDisconnect]":[false]}]},"desiredCapabilities":{"app":"scanmobile_e2e/e2e/utils/apps/tested.apk","fullReset":true,"clearSystemFiles":true,"platformName":"Android","automationName":"UiAutomator2","deviceName":"MC18N0","allowTestPackage":true,"udid":"17117523021209","platformVersion":"5.1.1","appWaitPackage":"com.budgetbox.appmetromc","appWaitActivity":"com.budgetbox.mcspecific.diagnostic.ui.DiagnosticActivity","settings[shutdownOnPowerDisconnect]":[false]}}

The value in capabilities is also wrong. Consider fixing the code of your automation framework.

**Comment by arthuRHD** [comment]
I was wrong, implementing settings this way don't work. Thanks for the helping me figuring out.
```py
self.capabilities = {
    "app": app_path,
    "fullReset": True,
    "clearSystemFiles": True,
    "uiautomator2ServerInstallTimeout": 30000
}
self.capabilities["settings[shutdownOnPowerDisconnect]"] = False,
```
