### ISSUE TITLE
unable to login to the web application during automation in Browserstack iOS device using selenium python

### ISSUE THREAD

**Issue by Md-Zabiuddin** [appium/python-client#554]
## The problem

I am trying to automate a web application in iOS device in browserstack. Application able to launch and login page is displayed and even able to enter username and password in respective fields. But after clicking login button unable login. Sometime even after entering username and password after clicking login button error messages displayed ' username and password required. I tried with sending data to both the fields using javascript executer but unable to login. I am perfectly able to login using android device but not happening with iOS.
DESIRED_CAPABILITY = {
        "build": "R360-browserstack",
        "os_version": "12",
        "device": "iPhone XS",
        "real_mobile": "true",
        "browserName": "iPhone",
        "browserstack.local": "true",
        "name": "BrowserStack-[Python] Demo",
        "browserstack.appium_version": "1.17.0"
    } 

## Environment
- Desktop OS/version used to run Appium:Windows 7 Enterprise
- Node.js version (unless using Appium.app|exe):N/A
- Mobile platform/version under test: Mentioned in capability above
- Real device or emulator/simulator: browserstack 
- Appium CLI or Appium.app|exe:N/A

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium Logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.

**Comment by KazuCocoa** [comment]
Was the app, _BrowserStack-[Python] Demo_, provided by BrowserStack?
Then, you can get a correct hint by asking it for them, I think.

Or https://discuss.appium.io/ also may help such questions.
(This repository is mainly for this binding issues)

**Comment by Md-Zabiuddin** [comment]
Thanks for comment Kazu!. BrowserStack-[Python] Demo, this app not provided by BrowserStack. that is just a name. I am using our internal application. and url (https://discuss.appium.io/) its difficult to find blog for our issue. Could you please find any blog for me?

**Comment by KazuCocoa** [comment]
Personally, it looks iOS side issue.
How about using `nativeWebTap` to click the element? If it did not work in WebView context, the native tap may help
http://appium.io/docs/en/advanced-concepts/settings/

**Comment by Md-Zabiuddin** [comment]
Hi Kazu,

I kept the capability as   "nativeWebTap": "true" and tried with
touch_actions = TouchActions(browser.driver)
touch_actions.tap(element1).perform()

even though showing error: ' this field is required ' for the entered text field.

Thought to try with tapping the keys on iPhone keypad using below javascript command.

 browser.driver.execute_script('var vKeyboard = target.frontMostApp().keyboard(); vKeyboard.setInterKeyDelay(0.1);vKeyboard.typeString("cherukupalli.sai@spglobal.com");')

throwing error: Appium error: An unknown server-side error occurred while processing the command. Original error: Can't find variable: target

please let me know any other workaround

**Comment by KazuCocoa** [comment]
I don't think keyboard by JS can detect the keyboard in a native layer.
how about doing the action with coordinate base

**Comment by Md-Zabiuddin** [comment]
Action with coordinate base ?

Can you give reference url please.

**Comment by KazuCocoa** [comment]
https://appium.github.io/python-client-sphinx/webdriver.common.html#webdriver.common.touch_action.TouchAction.press
https://appium.io/docs/en/commands/interactions/actions/ ( https://selenium-python.readthedocs.io/api.html#module-selenium.webdriver.common.action_chains )

**Comment by Md-Zabiuddin** [comment]
Thanks Kazu! able to login using actions

actions = ActionChains(browser.driver)
actions.send_keys('Dummy data')
