### ISSUE TITLE
Incorrect Get Session Capabilities implementation

### ISSUE THREAD

**Issue by skhalymon** [appium/python-client#560]
## The problem
As said in the [Get Session Capabilities](http://appium.io/docs/en/commands/session/get/) documentation for Python we need to call `driver.desired_capabilities`. Which internally proxies into the original selenium library. It makes sense in case of web but has some issues for mobile apps. For example, we cannot fetch the actual value of `pixelRatio` witch is returned by appium server.

## Environment
- Appium version (or git revision) that exhibits the issue: all versions
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: No matter which OS

## Code To reproduce issue
```
from appium import webdriver

driver = webdriver.Remote("http://0.0.0.0:4723/wd/hub", {
        "platformName": "Android",
        "app": "http://saucelabs.com/example_files/ContactManager.apk",
        "deviceName": " Samsung Galaxy S9+",
        "platformVersion": "10.0",
        "automationName": "UiAutomator2",
        "appiumVersion": "1.17.1",
    }
)
# should return proper value
print(driver.desired_capabilities['pixelRatio'])
```

This code shows how to fix the issue https://github.com/applitools/eyes.sdk.python/pull/196

**Comment by KazuCocoa** [comment]
https://appium.github.io/python-client-sphinx/webdriver.extensions.html#webdriver.extensions.session.Session.session is the current method
Will update the documentation.

**Comment by skhalymon** [comment]
@KazuCocoa thanks for the info!

in which version `driver.session` was added?

**Comment by KazuCocoa** [comment]
Probably 0.47 or around the version
