### ISSUE TITLE
Syntax Error in helper.py

### ISSUE THREAD

**Issue by maheenusman** [appium/python-client#561]
While trying to install appium-python-client via pip, got syntax error in helper.py on line 20.
Environment
- Appium version (or git revision) that exhibits the issue: v0.31
- Desktop OS/version used to run Appium: Ubuntu
- Node.js version (unless using Appium.app|exe): v14.10.1

This guide is used for installation https://confusedcoders.com/general-programming/mobile/how-to-install-appium-in-ubuntu

![Screenshot from 2020-09-14 16-50-03](https://user-images.githubusercontent.com/43992460/93082512-7c63a600-f6aa-11ea-9064-f3f4db398b64.png)

**Comment by mykola-mokhnach** [comment]
It looks like you are trying to use version 1 of the module with python2, which is unsupported

**Comment by maheenusman** [comment]
Resolved, thank you @mykola-mokhnach
