### ISSUE TITLE
App orientation doesn't change with driver.orientation = "LANDSCAPE"

### ISSUE THREAD

**Issue by shivakrishnach31** [appium/python-client#562]
## The problem
In Android devices, when driver.orientation = "LANDSCAPE" statement executed, the orientation of the app under test is not changed to landscape. But driver.orientation returning 'LANDSCAPE'. I tried 3 apps and observed the same behavior. Also, I used Appium and Selenium's remote, android WebDrivers and observed the same issue.

## Environment
- Appium version (or git revision) that exhibits the issue: 1.13.0
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: Windows 10 Enterprise 
- Node.js version (unless using Appium.app|exe):
- Mobile platform/version under test: Moto Z3 Play/ OS 9
- Real device or emulator/simulator: Real device
- Appium CLI or Appium.app|exe: Appium Desktop

## Details
Find the attached video clip
[orientation_issue.zip](https://github.com/appium/python-client/files/5282716/orientation_issue.zip)

## Link to Appium Logs

https://gist.github.com/shivakrishnach31/c882972bf0736d269400171688d1421a

## Code To reproduce the issue
driver.orientation = "LANDSCAPE"

**Comment by KazuCocoa** [comment]
I could not find the path of `/orientation` in the log. Was the attached Appium log expected?

**Comment by shivakrishnach31** [comment]
@KazuCocoa - Yes, the log is expected and correct one. I too didn't see anything related to orientation in the log. So I am not sure what is happening when driver.orientation = "LANDSCAPE' is executed.

**Comment by KazuCocoa** [comment]
Hm, it seems weird. Below is log in Appium when I called `driver.orientation = 'PORTRAIT'` with the latest Python client. 
Could you share your client code?

```
[HTTP] --> POST /wd/hub/session/1fe374fa-011e-47c3-9650-cb68d9dd58c3/orientation
[HTTP] {"orientation":"PORTRAIT"}
[W3C (1fe374fa)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/1fe374fa-011e-47c3-9650-cb68d9dd58c3/orientation' to command name 'setOrientation'
[debug] [WD Proxy] Proxying [POST /wd/hub/session/1fe374fa-011e-47c3-9650-cb68d9dd58c3/orientation] to [POST http://127.0.0.1:8200/wd/hub/session/829341d2-c69d-4837-bdeb-f092b616cedd/orientation] with body: {"orientation":"PORTRAIT"}
[debug] [WD Proxy] Got response with status 200: {"sessionId":"829341d2-c69d-4837-bdeb-f092b616cedd","value":"PORTRAIT"}
[WD Proxy] Replacing sessionId 829341d2-c69d-4837-bdeb-f092b616cedd with 1fe374fa-011e-47c3-9650-cb68d9dd58c3
[HTTP] <-- POST /wd/hub/session/1fe374fa-011e-47c3-9650-cb68d9dd58c3/orientation 200 46 ms - 82
[HTTP]
[HTTP] --> POST /wd/hub/session/1fe374fa-011e-47c3-9650-cb68d9dd58c3/orientation
```

**Comment by shivakrishnach31** [comment]
@KazuCocoa - You mean orientation code in Python Client? or something else?

```
@property
    def orientation(self):
        """
        Gets the current orientation of the device

        :Usage:
            orientation = driver.orientation
        """
        return self.execute(Command.GET_SCREEN_ORIENTATION)['value']

    @orientation.setter
    def orientation(self, value):
        """
        Sets the current orientation of the device

        :Args:
         - value: orientation to set it to.

        :Usage:
            driver.orientation = 'landscape'
        """
        allowed_values = ['LANDSCAPE', 'PORTRAIT']
        if value.upper() in allowed_values:
            self.execute(Command.SET_SCREEN_ORIENTATION, {'orientation': value})
        else:
            raise WebDriverException("You can only set the orientation to 'LANDSCAPE' and 'PORTRAIT'")
```

This is the code for orientation in Selenium remote webdriver.
Let me know if need further details.

**Comment by KazuCocoa** [comment]
I meant your test code.

I don't know why, but your Python test code did not send `/orientation` request to Appium.
I could not reproduce it using this repository's test code, so, I need to track your code with your attached Appium log first.

**Comment by shivakrishnach31** [comment]
Hi @KazuCocoa - I am using my company test framework for Appium and Selenium application automation which actually causing the problem. When I write simple desired caps and orientation code, the app gets launched and the orientation changed to Landscape. So there is no issue with Python Appium Client I can say. 
In my framework, we have overridden the __getattr__() method to get access to the non-existent(but exist in the appium.webdriver.webdriver module) method. But this driver instance is not working orientation but working with all other web driver methods. *Note:* This web driver creation class is not inheriting WebDriver class. Do you think is this the root cause? When I inherit the WebDriver, it started working with the framework also. Without inhering I can access all the methods of web driver and orientation property, but couldn't set the orientation. Can't we use the setter method in this way?
Anyhow, I am going to report this defect to the framework development team and ask for reliable support. Thank you!

**Comment by KazuCocoa** [comment]
Okay, i see.

Could be.
Or you also can define this orientation method by your own like `self.execute(Command.SET_SCREEN_ORIENTATION, {'orientation': value})` in https://github.com/appium/python-client/issues/562#issuecomment-699547625

**Comment by shivakrishnach31** [comment]
Yes, I am able to set orientation with the execute method. Thank you @KazuCocoa
