### ISSUE TITLE
selenium webdriver send keys pycharm

### ISSUE THREAD

**Issue by mssh1987** [appium/python-client#569]
## The problem

I have data in excel sheet , first Column have number , and second Column have test . the if run with text work program , but if run with number not work the program
   

## Environment
 import xlrd
        from selenium import webdriver
        from selenium.webdriver.common.keys import Keys
        import time
        
        
        PATH = "C:/Program Files (x86)/chromedriver.exe"
        driver = webdriver.Chrome(PATH)
        driver.get("https://www.youtube.com")
        
        print(driver.title)
        search = driver.find_element_by_name("search_query")
        
        workbook = xlrd.open_workbook("mohammed2.xls")
        sheet = workbook.sheet_by_name("sheet3")
        
        rowCount = sheet.nrows
        colCount = sheet.ncols
        print(rowCount)
        print(colCount)
        for curr_row in range(1, rowCount):
            numpValue = sheet.cell_value(curr_row, 0)
            #name = sheet.cell_value(curr_row, 1)
        
        
            search.send_keys(numpValue)
            time.sleep(3)
            search.send_keys(Keys.RETURN)
            search.clear()
            time.sleep(3)
            search.clear()

**Comment by mssh1987** [comment]
error the problem

Traceback (most recent call last):
  File "C:\Users\Mohammed\OneDrive\Desktop\file\Python Selenium\search.py", line 27, in <module>
    search.send_keys(numpValue)
  File "C:\Users\Mohammed\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 478, in send_keys
    {'text': "".join(keys_to_typing(value)),
  File "C:\Users\Mohammed\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\utils.py", line 150, in keys_to_typing
    for i in range(len(val)):
TypeError: object of type 'float' has no len()

Process finished with exit code 1

**Comment by ki4070ma** [comment]
Please check `numpValue` type at below line.

```
search.send_keys(numpValue)
```

`numpValue` should be `str`, but it seems `float`.
https://appium.github.io/python-client-sphinx/webdriver.html?highlight=send_keys#webdriver.webelement.WebElement.send_keys

**Comment by ki4070ma** [comment]
If you have further comment, please reopen.
