### ISSUE TITLE
Is there a way to find a child element in another element?

### ISSUE THREAD

**Issue by alexsczhong** [appium/python-client#57]
Our team use the webdriver to develop the Android UI automation. We found it is hard to find the child element in another element.
For example, the following picture is from a list. The button at the right shows the status of this item.
![default](https://cloud.githubusercontent.com/assets/8777603/4591030/faac2b4a-5066-11e4-8256-247dee9d47cd.PNG)

 In our test case, we want to find the item first then check the status of the right button. We can find this list item by the text. But we don't know how to find the button in the item. Is there a way to search the child element in another element? Could any one kindly help me out?

**Comment by abvijay** [comment]
Is it possble to find Preceding Sibling element from the current WebElement? If yes,Code Plz. 
 I tried like below but it is throwing WebDriver Exception: Cannot use xpath locator strategy from an element. It can only be used from the root element.

List<WebElement> listOfProfiles=driver.findElements(By.id("srch_res_mem_nam_txt_id")); //get ProfileDetails.		
		
		for (WebElement eachProfile : listOfProfiles) {
			String currentProfileId=eachProfile.findElement(By.xpath("..")).getText();
			System.out.println("currentProfileId:"+currentProfileId);

**Comment by Rayson-Lai** [comment]
```
/*
input:
return:  
*/
def getDomTree(elements):
    root = DomTreeNode(elements[0])
    stack = [(elements[0], root)]

    for e in elements[1:]:
        try:
            top, parentNode = stack.pop()
            for top != e.parent and len(stack) != 0: 
                top, parentNode = stack.pop()
            
            if top == e.parent:
                curNode = DomTreeNode(e)
                root.children.append(curNode)
                stack.append((top, parentNode))
                stack.append((e, curNode))
            else:
                raise Exception
        except Exception e:
            print(e)
    return root
```

```
/*
input:
return:  
*/
def filterDomTreeByLevel(root, level=3):
    threshold = root.rect['width']/(2^level)
    queue = root.children
    path = [root]

    // do bfs search
    for len(queue) != 0:
        curNode = queue.popLeft()
        parentNode = path.pop()
        for not parentNode.children.contains(curNode):
            parentNode = path.pop()
        
        if isSigRegion(curNode, threshold):
            if parentNode.rect == curNode.rect:
                parent.children.remove(curNode)
                parent.children.expend(curNode.children)
            queue.expend(curNode.children)
            path.append(parentNode)
            path.append(curNode)
        else:
            parent.children.remove(curNode)
            path.append(parentNode)
    return root
```
