### ISSUE TITLE
driver.execute_script("window.print();")

### ISSUE THREAD

**Issue by mssh1987** [appium/python-client#572]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment
- Appium version (or git revision) that exhibits the issue:
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium:
- Node.js version (unless using Appium.app|exe):
- Mobile platform/version under test:
- Real device or emulator/simulator:
- Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium Logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.

**Comment by mssh1987** [comment]
from selenium import webdriver
import time



PATH = "C:/Program Files (x86)/chromedriver.exe"
driver = webdriver.Chrome(PATH)
driver.get("https://en.wikipedia.org/wiki/Book")
print(driver.title)



driver.execute_script("window.print();")
time.sleep(3)



--how complete the print the page--

**Comment by mssh1987** [comment]
--how complete the print the page--

**Comment by KazuCocoa** [comment]
Sorry, probably i don't understand well.
Do you mean `window.print();` did not work in the app under test's browser?

**Comment by ki4070ma** [comment]
Closed as not active
