### ISSUE TITLE
Error in send_to_background - Appium Android

### ISSUE THREAD

**Issue by chrisjubb** [appium/python-client#58]
I get an error when calling send_to_background. When it runs, it runs the game and suspends it correctly but fails to resume it. I'm using a Nexus 7 running Android 4.3
Here's the stack trace:

```
======================================================================
ERROR: test_webview (test_randomize.SimpleAndroidTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/cjubb/dev/MakieLab/dressup-client/Tests/appium/test_randomize.py", line 19, in test_webview
    self.send_to_background(2)
  File "/Users/cjubb/dev/MakieLab/dressup-client/Tests/appium/tablet_test_base.py", line 26, in send_to_background
    self.driver.background_app(time_in_background)
  File "/Users/cjubb/dev/MakieLab/dressup-client/venv/lib/python2.7/site-packages/appium/webdriver/webdriver.py", line 481, in background_app
    self.execute(Command.BACKGROUND, data)
  File "/Users/cjubb/dev/MakieLab/dressup-client/venv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 173, in execute
    self.error_handler.check_response(response)
  File "/Users/cjubb/dev/MakieLab/dressup-client/venv/lib/python2.7/site-packages/appium/webdriver/errorhandler.py", line 29, in check_response
    raise wde
WebDriverException: Message: u'An unknown server-side error occurred while processing the command. (Original error: com.makielab.DressUpTest/com.unity3d.player.UnityPlayerNativeActivity never started. Current: com.android.launcher/com.android.launcher2.Launcher)' 
```

Here's the test code:

```
self.driver.switch_to.context('WEBVIEW_0')
self.send_to_background(2)
sleep(3)
```

The name of our bundle is com.makielab.DressUpTest.

**Comment by clmathuriya** [comment]
Facing the same issue..

executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.quora.android/com.quora.android.LauncherActivity"
info: [debug] Waiting for pkg "com.quora.android" and activity "com.quora.android.LauncherActivity" to be focused
info: [debug] Getting focused package and activity
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys window windows"
error: com.quora.android/.LauncherActivity never started. Current: com.quora.android/.LoginActivity
info: [debug] Stopping logcat capture
info: [debug] Logcat terminated with code null, signal SIGTERM
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"OK, shutting down","status":0}
info: [debug] [BOOTSTRAP] [debug] Closed client connection
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
info: [debug] [UIAUTOMATOR STDOUT] Time: 21.339
info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
info: [debug] UiAutomator shut down normally
info: [debug] Cleaning up android objects
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: com.quora.android/.LauncherActivity never started. Current: com.quora.android/.LoginActivity
info: [debug] Error: com.quora.android/.LauncherActivity never started. Current: com.quora.android/.LoginActivity
    at null.<anonymous> (/home/chhagan/appium/node-v0.10.33-linux-x64/lib/node_modules/appium/node_modules/appium-adb/lib/adb.js:1298:12)
    at null.<anonymous> (/home/chhagan/appium/node-v0.10.33-linux-x64/lib/node_modules/appium/node_modules/appium-adb/lib/adb.js:1242:7)
    at null.<anonymous> (/home/chhagan/appium/node-v0.10.33-linux-x64/lib/node_modules/appium/node_modules/appium-adb/lib/adb.js:172:9)
    at ChildProcess.exithandler (child_process.js:646:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: com.quora.android/.LauncherActivity never started. Current: com.quora.android/.LoginActivity)","origValue":"com.quora.android/.LauncherActivity never started. Current: com.quora.android/.LoginActivity"},"sessionId":null}
info: <-- POST /wd/hub/session 500 292

**Comment by imurchie** [comment]
As above. Please look for an issue in the Appium repository, and if there isn't one, create one.
