### ISSUE TITLE
Getting following error for webdriver: selenium.common.exceptions.WebDriverException: Message: 'That URL did not map to a valid JSONWP resource' 

### ISSUE THREAD

**Issue by diptichaudhari24** [appium/python-client#60]
I am trying to run appium script to automate Android app. I don't know where it is going wrong.

Script:
desired_caps = {}
desired_caps['appium-version'] = '1.0'
desired_caps['platformName'] = 'Android'
desired_caps['platformVersion'] = '4.4'
desired_caps['deviceName'] = 'abc'
desired_caps['app'] = os.path.abspath('/Users/vikas/Documents/Something/Android/SomethingMobile.apk')
desired_caps['appActivity'] = 'com.something.mobile.SomethingSplash'
desired_caps['appPackage'] = 'com.Something.mobile'
desired_caps['avd'] = 'abc'
self.driver = webdriver.Remote('http://0.0.0.0:4723/wd/hub/', desired_caps)

Server response is:
info: --> POST /wd/hub//session {"desiredCapabilities":{"deviceName":"abc","appium-version":"1.0","app":"/Users/vikas/Documents/something/Android/SomethingMobile.apk","platformVersion":"4.4","avd":"abc","appPackage":"com.something.mobile","platformName":"Android","appActivity":"com.something.mobile.SomethingSplash"}}
info: [debug] Responding to client that we did not find a valid resource
info: <-- POST /wd/hub//session 404 0.709 ms - 47

**Comment by ashishp100194** [comment]
I am facing the same issue. Not getting the workaround for this. I have written a simple code with the desired capabilities of a sample app.

`from appium import webdriver

desired_cap={
    'deviceName':'emulator-5554',
    'platformName':'Android',
    'app':'original.apk'
}

driver = webdriver.Remote("http://127.0.0.1:4723/wb/hub",desired_cap)`

Python logs:
`    driver = webdriver.Remote("http://127.0.0.1:4723/wb/hub",desired_cap)
  File "C:\Users\Ashish\AppData\Local\Programs\Python\Python38-32\lib\site-packages\appium\webdriver\webdriver.py", line 147, in __init__
    super(WebDriver, self).__init__(
  File "C:\Users\Ashish\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Ashish\AppData\Local\Programs\Python\Python38-32\lib\site-packages\appium\webdriver\webdriver.py", line 227, in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, parameters)
  File "C:\Users\Ashish\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Ashish\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 208, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: The URL '/wb/hub/session' did not map to a valid resource`

Appium Server Logs:
`[HTTP] {"capabilities":{"firstMatch":[{"appium:deviceName":"emulator-5554","platformName":"Android","appium:app":"original.apk"}]},"desiredCapabilities":{"deviceName":"emulator-5554","platformName":"Android","app":"original.apk"}}
[HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- POST /wb/hub/session 404 1 ms - 57
[HTTP]`
