### ISSUE TITLE
Make a release that works with selenium 4.0.0b3

### ISSUE THREAD

**Issue by PhilippSelenium** [appium/python-client#602]
## The problem

I want to install and test selenium 4.0.0b3 in my project which is also using appium but due to the appium install restrictions on selenium this is not possible

## The fix

release new beta version which accepts selenium 4.0.0b3

**Comment by KazuCocoa** [comment]
Did you try https://pypi.org/project/Appium-Python-Client/2.0.0b2/ out?
It has `selenium == 4.0.0.b3` https://github.com/appium/python-client/compare/selenium-4?expand=1#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R50

**Comment by PhilippSelenium** [comment]
Yes, what i get is:
```
    The user requested selenium==4.0.0b3
    appium-python-client 2.0.0b2 depends on selenium==4.0.0.b2.post1
```

**Comment by KazuCocoa** [comment]
Oh, i see. The package was my dev machine. (Missed the upload script)
https://pypi.org/project/Appium-Python-Client/2.0.0b3/ is the latest one in the working branch.
