### ISSUE TITLE
Pycharm error 'Path is not defined'

### ISSUE THREAD

**Issue by GnubiBORED** [appium/python-client#609]
## The problem

Im using pycharm creating a new venv and installed python appium client, i tried to run simple code 

```
import unittest
from appium import webdriver

desired_caps = dict(
    platformName='Android',
    platformVersion='10',
    automationName='uiautomator2',
    deviceName='Android Emulator',
    app=PATH('../../../apps/selendroid-test-app.apk')
)
driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
el = driver.find_element_by_accessibility_id('item')
el.click()
```
But i get

NameError: name 'PATH' is not defined

I know path is a helper method but i dont know what im missing, do i need to giv access in some way to my script or pycharm to this path method file?

## Environment
- Appium version (or git revision) that exhibits the issue: lastest
- Desktop OS/version used to run Appium: Ubuntu 20.04 LTS
- Mobile platform/version under test:
- Real device or emulator/simulator: Docker-Android
- Appium CLI or Appium.app|exe: Appium app

```
/home/gatopicsa/PycharmProjects/Tribalwars-Appium-Tests/venv/bin/python /home/gatopicsa/PycharmProjects/Tribalwars-Appium-Tests/main.py
Traceback (most recent call last):
  File "/home/gatopicsa/PycharmProjects/Tribalwars-Appium-Tests/main.py", line 14, in <module>
    app=PATH('../../../apps/selendroid-test-app.apk')
NameError: name 'PATH' is not defined

Process finished with exit code 1

```

**Comment by jlipps** [comment]
You're responsible for including the absolute path to your application. You can do that however you want, by using standard Python functions or creating a helper function.
