### ISSUE TITLE
How can I use this client just on iOS

### ISSUE THREAD

**Issue by daokemt** [appium/python-client#610]
I want execute my py file just on my iphone, without mac, without usb, just executing when i click one button on my phone. how can I do it, has any open source solutions?  thanks.

**Comment by KazuCocoa** [comment]
I haven't tried such way.
I think https://discuss.appium.io/ may help to find if someone tried similar thing...

**Comment by daokemt** [comment]
> I haven't tried such way.
> I think https://discuss.appium.io/ may help to find if someone tried similar thing...

thanks so fast reply, I'm not lonely. 

I have an idea, that is integration a python engine on my iOS app code, then use your library. because I think some library like yours just convert script lines to wda http  protocol, also easy writing one javascript library.

I'm looking for a js library like yours python library. then integration an engine to execute that library and user script file.

thanks again!
