### ISSUE TITLE
files date in Appium-Python-Client-1.2.0.tar.gz

### ISSUE THREAD

**Issue by ValeryNov** [appium/python-client#622]
## The problem

why do all the files in the archive [https://files.pythonhosted.org/packages/0e/df/18cfe4ef2e1a4912988071a0327a95cb6f707843a493175a37bb4eb92953/Appium-Python-Client-1.2.0.tar.gz](url)  have the date 1970

**Comment by KazuCocoa** [comment]
Could you explain more? Maybe I missed some context.
I got the below information after downloading the package and open it with `tar -zxvf`, but they were not 1970.
```
% ls -all
total 16
drwxr-xr-x@  6 kazuaki  staff  192 Jun  6 22:35 .
drwxr-xr-x@ 11 kazuaki  staff  352 Jun  6 22:35 ..
-rw-r--r--@  1 kazuaki  staff  597 May 16  2020 __init__.py
drwxr-xr-x@  6 kazuaki  staff  192 Jun  6 22:35 common
-rw-r--r--@  1 kazuaki  staff   18 Jun  6 22:34 version.py
drwxr-xr-x@ 17 kazuaki  staff  544 Jun  6 22:35 webdriver
```

**Comment by ValeryNov** [comment]
Sorry, you're right. This is an internal TC unpacker bug.
