### ISSUE TITLE
How to longpress a point without relase

### ISSUE THREAD

**Issue by focalism** [appium/python-client#626]
## The problem

I want to longpress a point just like:
```python
action1 = TouchAction(self.driver).long_press(
    x=200,
    y=400,
    duration=2000,
).release().perform()

# or like this
action1 = TouchAction(self.driver).press(
    x=200,
    y=400,
).wait(1000).release().perform()
```
but if i run without `release`, this actions become `tap`.I do not know the difference between with release and without.

In addition, I would like to know if there is a way to achieve the following requirements:
Long press and release when the condition is met (not a fixed time)

## Environment
- python version：3.7.1
- macOS：11.4
- ios：14.4
- appium-client：Appium-Python-Client==1.2.0

**Comment by mykola-mokhnach** [comment]
Such feature is not supported by xctest
