### ISSUE TITLE
About, 'connection pool is full'. I want to know why it is occurring.

### ISSUE THREAD

**Issue by jay0129** [appium/python-client#627]
## The problem
I use 3 machines for android appium test
- Test script machine that is using `python-client`.
- Selenium grid hub.
- Appium server with AVD connected

But I get the following warning too much, 4~6 times per 10 seconds.
`WARNING urllib3.connectionpool:connectionpool.py:275 Connection pool is full, discarding connection: <HUB_URL>`

## Environment
- Selenium grid docker image: selenium/hub:3.141.59-20210804
  https://github.com/SeleniumHQ/docker-selenium/tree/selenium-3#version-3
- Appium Desktop version: `1.21.0`
- Electron: `7.2.4`
- Node.js: `12.8.1`
- OS version: `macOS Big sur 11.5.2`
- Mobile platform/version under test: `Android API30 Emulator`
- Real device or emulator/simulator: `Emulator`
- Appium CLI or Appium.app|exe: `Appium.app`

## Details
Client logs
```
WARNING urllib3.connectionpool:connectionpool.py:275 Connection pool is full, discarding connection: <HUB_URL>
WARNING urllib3.connectionpool:connectionpool.py:275 Connection pool is full, discarding connection: <HUB_URL>
WARNING urllib3.connectionpool:connectionpool.py:275 Connection pool is full, discarding connection: <HUB_URL>
WARNING urllib3.connectionpool:connectionpool.py:275 Connection pool is full, discarding connection: <HUB_URL>
```
## Link to Appium Logs
```
...
[info] [35m[HTTP][39m [90m[39m[debug] [35m[Appium][39m Appium successfully registered with the the grid on http://<HUB_URL>:4444[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/status[39m
...
```

**Comment by KazuCocoa** [comment]
How many session did you tried to establish without closing them?

It seems the pool reach the max of its connection pool.
https://stackoverflow.com/questions/53765366/urllib3-connectionpool-connection-pool-is-full-discarding-connection

I don't know well about grid's connection policy, but potentially it keep connections(?)

**Comment by jay0129** [comment]
Thank you for your advice.
By the way, test script is running find even though I got the warning message.

My question here is, does `python-client` request to HUB_URL on every attempts of finding elements or clicking it?
Then, if the previous request was in pending, the warning message could be generated.

**Here is my configuration details.**
Maybe it is because I set the `maxSession` to 1  at the Appium node configuration.
But, It is weird because I close Appium driver after test is done like the following code:
```
@pytest.fixture(scope="module")
def targets(request):
    ...
    driver = webdriver.Remote(SELENIUM_GRID_HUB, caps)
    yield driver
    driver.quit()
```

At the Appium side, I configured `maxSession` to 1.
$cat appium-node.config
```
{
        "capabilities": [{
                "maxInstances": 1,
                "automationName": "UIAutomator2",
                "platformName": "Android",
                ...
        }, {
                "maxInstances": 1,
                "platformName": "iOS",
                "deviceName": "iPhone Simulator",
                "newCommandTimeout": 240,
                ...
        }],
        "configuration": {
                "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
                "url": "http://<APPIUM_URL>:4723/wd/hub",
                "host": "<APPIUM_URL>",
                "port": 4723,
                "maxSession": 1,
                "register": true,
                "registerCycle": 10000,
                "hub": "http://< HUB_URL>:4444/grid/register/",
                "hubPort": 4444,
                "hubHost": "< HUB_URL>",
                "remoteHost": "http://<APPIUM_URL>:4723",
                "role": "node"
        }
}
```

**Comment by KazuCocoa** [comment]
python-client re-uses the connection (managed by https://urllib3.readthedocs.io/en/latest/reference/urllib3.poolmanager.html#urllib3.PoolManager) with keep-alive. The keep-alive is True by default. So, if the grid have kept previous sessions for PoolManager on the python client thread, potentially it reached the maximum connection. (I guess...)
https://github.com/appium/python-client/blob/e48085d27968a93d9cfb5d86964ac84198b52214/appium/webdriver/webdriver.py#L262

What about disabling keep-alive in python client?

**Comment by jay0129** [comment]
@KazuCocoa , After applying keep_alive True like the following code:
`driver = webdriver.Remote(SELENIUM_GRID_HUB, caps, keep_alive=False)`
The warning doesn't occur yet, so I will use this configuration for now.

If some regressions occurs then I will report on this thread.
