### ISSUE TITLE
[python] Cannot install selenium 4.0.0.rc1 with appium 2.0.0b5 

### ISSUE THREAD

**Issue by PhilippSelenium** [appium/python-client#635]
## The problem

See title

## Environment

python: 3.8.5
appium: 2.0.0b5

## Details

```
The conflict is caused by:
    The user requested selenium==4.0.0.rc1
    appium-python-client 2.0.0b5 depends on selenium==4.0.0.b4
```

## Code To Reproduce Issue [ Good To Have ]
```
pip install selenium==4.0.0.rc1 Appium-Python-Client==2.0.0b5
```

**Comment by KazuCocoa** [comment]
https://pypi.org/project/Appium-Python-Client/2.0.0rc1/ has 4.0.0.rc1.

**Comment by KazuCocoa** [comment]
the diff is https://github.com/appium/python-client/pull/636
