### ISSUE TITLE
During the sliding process, loading will cause the data to fall back to the data position that has been swiped

### ISSUE THREAD

**Issue by TjandJamie** [appium/python-client#665]
## During the sliding process, loading will cause the data to fall back to the data position that has been swiped

I have a problem: when I use scrolling, I scroll to the end of the first page of data. When the next page of data is loaded, the data will fall back to the displayed position of the first page of data that has been scrolled. How to solve this problem?

I used the Refresh Source & Screenshot function of appium, which also caused the current page data to be rolled back to the data display position that has been swiped.

## Environment
- Desktop OS/version used to run Appium: 1.12.0
- Node.js version (unless using Appium.app|exe): 12.8.1
- Mobile platform/version under test: iOS
- Real device or emulator/simulator: Real device
- Appium CLI or Appium.app|exe: Appium.app

## Details
{
  "platformName": "iOS",
  "platformVersion": "14.8.1",
  "deviceName": "iPhone 8 Plus",
  "automationName": "xcuitest",
  "udid": "xxxxxx",
  "app": "xxxxx",
  "unicodeKeyboard": true,
  "resetKeyboard": true
}

Rolling method：
One： self.driver.execute_script("mobile:dragFromToForDuration",{'direction': 'right', 'duration': 0.5, "element": None, "fromX": start_x, "fromY": max_y, "toX": start_x, "toY": min_y})
Two：self.driver.execute_script('mobile: scroll', {'direction': 'down'})
Three：self.driver.swipe(x * 0.5, y * start_y, x * 0.5, y * end_y, 500)

**Comment by KazuCocoa** [comment]
> Desktop OS/version used to run Appium: 1.12.0

The version is outdated. Could you try the latest 1.22 once?

**Comment by TjandJamie** [comment]
OK，I will try ，Thanks for your quick reply。

**Comment by TjandJamie** [comment]
@KazuCocoa Hello, I updated appium according to your suggestion, the problem still exists, correct it, my original appium is version 1.21.0, the current version is 1.22.0

**Comment by KazuCocoa** [comment]
Ah, you used 1.21. (The description addressed 1.12, so I thought you used an old version)
Then, could you share the appium log and the system log?

btw,
> One： self.driver.execute_script("mobile:dragFromToForDuration",{'direction': 'right', 'duration': 0.5, "element": None, "fromX": start_x, "fromY": max_y, "toX": start_x, "toY": min_y})

calls https://developer.apple.com/documentation/xctest/xcuielement/1500989-clickforduration?language=objc in the end. Then, I guess the behavior is iOS/XCTest internal-related thing. Appium cannot inject anything if so.
e.g. The behavior happens when the app is running in XCTest session

**Comment by TjandJamie** [comment]
This is the appium log，related udid and app information is blocked, hope it will not affect your inspection。
[appium-server-logs.txt](https://github.com/appium/python-client/files/7708201/appium-server-logs.txt)

**Comment by TjandJamie** [comment]
The reason why I suspect it is a problem with appium is because I found that manually sliding the data to the second page of loading and clicking Refresh Source & Screenshot in the appium inspector has a similar effect.

**Comment by KazuCocoa** [comment]
Thank you. Could you share the device system log?
`appium:showIOSLog` `true` also provides the system log in the appum log, though the size could be huge.

Appium handles the application under test through https://developer.apple.com/documentation/xctest . So how the device/application under test behaves depends on the XCTest framework, basically.

To clarify the cause if Appium or XCTest, you also can write a simple test case to do the interaction via  https://developer.apple.com/documentation/xctest/xcuielement/1500989-clickforduration in XCTest(UI) as well.

**Comment by TjandJamie** [comment]
Sorry, maybe I can’t provide this log, but thank you for another idea, I need to learn it before trying
