### ISSUE TITLE
appium-python 2.10 Android phone swipe does not work

### ISSUE THREAD

**Issue by tewbie** [appium/python-client#667]
## The problem
appium-python-client 2.10  使用driver.swipe() 在安卓手机中，无法拖动元素

## Environment
- Appium version (or git revision) that exhibits the issue: 
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium:
- Node.js version (unless using Appium.app|exe):
- Mobile platform/version under test: Android 10
- Real device or emulator/simulator: Real device
- Appium CLI or Appium.app|exe:

## Details

I have an operation that uses the driver.swipe() method to drag elements, This method doesn't seem to work in appium-python-client 2.10. After switching to version 1.20, the operation can be performed normally
Turn on the Android pointer position. When using version 2.10, the phone screen shows a sliding track, but elements are not dragged.

## Link to Appium Logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.

## Code To reproduce issue

self.driver.swipe(start_x=start_x, start_y=start_y, end_x=end_x, end_y=end_y, duration=duration)

actions = ActionChains(self.driver)
actions.w3c_actions.pointer_action.move_to_location(start_x, start_y)
actions.w3c_actions.pointer_action.click_and_hold()
actions.w3c_actions.pointer_action.pause(3)
actions.w3c_actions.pointer_action.move_to_location(end_x, end_y)
actions.perform()

**Comment by KazuCocoa** [comment]
So, did not w3c actions work in your case even the pointer location shown correct line?

**Comment by tewbie** [comment]
> 



> 那么，w3c操作是否适用于您的情况，即使指针位置显示正确的行？

Yes,In my operation the swipe method works fine in version 1.20, but using version 2.10 does not work for that operation.   
Same code, but switched appium-Python version
![aaa](https://user-images.githubusercontent.com/51439645/146714966-4a25abdd-07f6-40c3-8ecb-59d7cb00aeaf.png)

**Comment by KazuCocoa** [comment]
As https://github.com/appium/python-client#quick-migration-guide-from-v1-to-v2 , it was because probably the backend had changed to W3C actions.

Does like the below click action work against the icon?
I wonder android API used in w3c did not work to click the icon, or the set of swipe action's w3c actions had an issue.
```
            actions.w3c_actions.pointer_action.move_to(element)
            actions.w3c_actions.pointer_action.pause(duration_sec)
            actions.w3c_actions.pointer_action.release()
            actions.perform()
```

**Comment by tewbie** [comment]
> 如https://github.com/appium/python-client#quick-migration-guide-from-v1-to-v2，可能是因为后端已更改为 W3C 操作。
> 
> 喜欢下面的点击动作对图标起作用吗？ 我想知道 w3c 中使用的 android API 无法单击图标，或者滑动操作的 w3c 操作集有问题。
> 
> ```
>             actions.w3c_actions.pointer_action.move_to(element)
>             actions.w3c_actions.pointer_action.pause(duration_sec)
>             actions.w3c_actions.pointer_action.release()
>             actions.perform()
> ```

 The above code works. I have tried to move the app on the mobile phone desktop and it is no problem, but sliding in the app is invalid, and the same operation is no problem in ios.

**Comment by tewbie** [comment]
> > 如[https://github.com/appium/python-client#quick-migration-guide-from-v1-to-v2，可能是因为后端已更改为](https://github.com/appium/python-client#quick-migration-guide-from-v1-to-v2%EF%BC%8C%E5%8F%AF%E8%83%BD%E6%98%AF%E5%9B%A0%E4%B8%BA%E5%90%8E%E7%AB%AF%E5%B7%B2%E6%9B%B4%E6%94%B9%E4%B8%BA) W3C 操作。
> > 喜欢下面的点击动作对图标起作用吗？ 我想知道 w3c 中使用的 android API 无法单击图标，或者滑动操作的 w3c 操作集有问题。
> > ```
> >             actions.w3c_actions.pointer_action.move_to(element)
> >             actions.w3c_actions.pointer_action.pause(duration_sec)
> >             actions.w3c_actions.pointer_action.release()
> >             actions.perform()
> > ```
> 
> The above code works. I have tried to move the app on the mobile phone desktop and it is no problem, but sliding in the app is invalid, and the same operation is no problem in ios.

The above code works. I have tried to move the app on the mobile phone desktop and it is no problem, but sliding in the app is invalid, and the same operation is no problem in ios.

**Comment by tewbie** [comment]
> 如https://github.com/appium/python-client#quick-migration-guide-from-v1-to-v2，可能是因为后端已更改为 W3C 操作。
> 
> 喜欢下面的点击动作对图标起作用吗？ 我想知道 w3c 中使用的 android API 无法单击图标，或者滑动操作的 w3c 操作集有问题。
> 
> ```
>             actions.w3c_actions.pointer_action.move_to(element)
>             actions.w3c_actions.pointer_action.pause(duration_sec)
>             actions.w3c_actions.pointer_action.release()
>             actions.perform()
> ```

The above code works. I have tried to move the app on the mobile phone desktop and it is no problem, but sliding in the app is invalid, and the same operation is no problem in ios.

**Comment by KazuCocoa** [comment]
Mm...interesting...

**Comment by tewbie** [comment]
> 嗯......有趣......



> Mm...interesting...

Many Android phones have this problem. I have tried Huawei Mate 30 Pro, Redmi, Xiaomi,

**Comment by tewbie** [comment]
> Mm...interesting...

Many Android phones have this problem. I have tried Huawei Mate 30 Pro, Redmi, Xiaomi,

**Comment by KazuCocoa** [comment]
I wonder w3c action should send pointer type to make the behavior same as old touch actions.
Let me tweak it tomorrow

https://github.com/appium/appium-uiautomator2-server/blob/master/app/src/main/java/io/appium/uiautomator2/utils/w3c/ActionsExecutor.java#L165

https://android.googlesource.com/platform/frameworks/testing/+/jb-dev/uiautomator/library/src/com/android/uiautomator/core/InteractionController.java#225

**Comment by KazuCocoa** [comment]
Could you try out https://github.com/appium/python-client/pull/670 ?

**Comment by tewbie** [comment]
> Could you try out #670 ?

The problem is solved,thanks.

**Comment by KazuCocoa** [comment]
2.1.1 has the change.
