### ISSUE TITLE
Endpoint changes since appium 1.22.0 [Need info]

### ISSUE THREAD

**Issue by arthuRHD** [appium/python-client#679]
I have a hard time understanding how you guys did the migration from '/getLog' command to '/log'. I'm using appium 1.18.0 and my `driver.get_log('logcat')` isn't recognized.

**Comment by KazuCocoa** [comment]
Did you upgrade python client to v2?
The v2 use python selenium client v4. The v4 issues `se/log` endpoint for logs. So far, you can downgrade the python client to v1 to not use Selenium v4.

Appium accepts the endpoint by https://github.com/appium/appium-base-driver/pull/517, that is in Appium 1.22.0. For UIA2, it needs https://github.com/appium/appium-uiautomator2-driver/pull/481. The version is available via `appium@beta` or appium 2.0 for now.

**Comment by arthuRHD** [comment]
Just downgraded, works perfectly. Thanks !
