### ISSUE TITLE
How to remove DeprecationWarning: desired_capabilities has been deprecated

### ISSUE THREAD

**Issue by jay0129** [appium/python-client#680]
## The problem

Code:
`self.driver = webdriver.Remote(self.hub_url, self.caps, keep_alive=False)`

Error:
`/Users/user/.pyenv/versions/3.7.10/lib/python3.7/site-packages/appium/webdriver/webdriver.py:274: DeprecationWarning: desired_capabilities has been deprecated, please pass in an Options object with options kwarg`

## Environment
- Appium: 1.22.2
- Appium-Python-Client: 2.1.2
- Host machine: OSX

**Comment by KazuCocoa** [comment]
Perhaps https://github.com/appium/python-client/issues/640 is the final fix.

Handling built-in warning as https://docs.python.org/3/library/warnings.html could be a workaround.

**Comment by jay0129** [comment]
@KazuCocoa , I tested on the latest version which is 2.1.2, but it still has the warning problem.

**Comment by KazuCocoa** [comment]
The #640 is an open issue.

Did you try the below before calling a new session request as the above link of warnings?
```
import warnings
warnings.simplefilter("ignore")
```

**Comment by jay0129** [comment]
Ok.
I just suppress the warning as for now. Thank you for your support!
```
 with warnings.catch_warnings():
            warnings.filterwarnings("ignore", category=DeprecationWarning)
            self.driver = webdriver.Remote(self.hub_url, self.caps, keep_alive=False)
```

**Comment by f00dog-x300** [comment]
My solution is to add this in my pytest.ini file. 
pytest.ini
```
[pytest]
filterwarnings = 
    # Appium team is aware of deprecation warning - https://github.com/appium/python-client/issues/680
    ignore::DeprecationWarning
```
