### ISSUE TITLE
Cannot upgrade to 2.1.3 via pip

### ISSUE THREAD

**Issue by jisoo1225** [appium/python-client#689]
Hello,

I'd like to upgrade Appium-Python-Client to 2.1.3 to workaround the "python selenium client 4.1.0" issue.

- https://github.com/appium/python-client/pull/685

However, it failed with "ERROR: No matching distribution found". 
> ERROR: Could not find a version that satisfies the requirement Appium-Python-Client==2.1.3 (from versions: 0.3.macosx-10.9-intel, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.10, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.30, 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.40, 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.50, 0.51, 0.52, 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.2.0, 1.3.0, 2.0.0a0, 2.0.0b1, 2.0.0b2, 2.0.0b3, 2.0.0b4, 2.0.0b5, 2.0.0rc1, 2.0.0rc2, 2.0.0rc4, 2.0.0rc5, 2.0.0rc6, 2.0.0, 2.1.0, 2.1.1, 2.1.2)
> ERROR: No matching distribution found for Appium-Python-Client==2.1.3

I found that there is no tar.gz file for 2.1.3 in https://pypi.org/simple/appium-python-client/. I am not sure, but would it be an issue?
Please let me know if i'm missing anything. Thanks!

**Comment by KazuCocoa** [comment]
mm, i confirmed the issue... I only checked https://pypi.org/project/Appium-Python-Client/2.1.3/  and the package installation in my local... Maybe something wrong occurred in pypi when I've uploaded.
Let me check

**Comment by KazuCocoa** [comment]
Please check https://pypi.org/project/Appium-Python-Client/2.1.4/
I've bump a version without any changes with 2.1.3 to upload the same one to pip as different version.

**Comment by jisoo1225** [comment]
I've successfully upgraded with 2.1.4. Thanks a lot!
