### ISSUE TITLE
DeprecationWarning: desired_capabilities has been deprecated

### ISSUE THREAD

**Issue by mchasaegh** [appium/python-client#691]
## The problem

Hello,

I'm not sure if this is right repo to open this issue in, but if it is, is there a correct way to pass desired caps to stop this warning message?

```py
CAPS = dict(
    platformName='Android',
    deviceName='Android Emulator',
    automationName='UiAutomator2',
    app=APP,
)


driver = webdriver.Remote(
    command_executor=APPIUM,
    desired_capabilities=CAPS,
)
```

```sh
appium/webdriver/webdriver.py:274: DeprecationWarning: desired_capabilities has been deprecated, please pass in an Options object with options kwarg
  super().__init__(
```

## Environment
- Appium version 2.0.0-beta.25
- Desktop OS/version used to run Appium: macOS 12.2.1
- Node.js version 16.13.2
- Mobile platform/version under test: Android 11
- Real device or emulator/simulator: emulator

**Comment by KazuCocoa** [comment]
This is a known task this client should do as https://github.com/appium/python-client/issues/640 .

https://github.com/appium/python-client/issues/680 can prevent the warning as a workaround for now.
