### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Lol437** [appium/python-client#692]
What should I do if I get such an error?

Traceback (most recent call last):
  File "appiumscript.py", line 12, in <module>
    self.driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
  File "/home/lokomanako/Downloads/test/venv/lib/python3.8/site-packages/appium/webdriver/webdriver.py", line 274, in __init__
    super().__init__(
  File "/home/lokomanako/Downloads/test/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 266, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/lokomanako/Downloads/test/venv/lib/python3.8/site-packages/appium/webdriver/webdriver.py", line 369, in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, parameters)
  File "/home/lokomanako/Downloads/test/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "/home/lokomanako/Downloads/test/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The application at '/home/lokomanako/Downloads/botbrawlstars/app/test.apk' does not exist or is not accessible
stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: The application at '/home/lokomanako/Downloads/botbrawlstars/app/test.apk' does not exist or is not accessible
    at getResponseForW3CError(/usr/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/usr/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)

**Comment by Lol437** [comment]
and in appuim

Emulator","appium:app":"/home/lokomanako/Downloads/botbrawlstars/app/test.apk"},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"Android", "platformVersion":"11","automationName":"uiautomator2","deviceName":"Android Emulator","app":"/home/lokomanako/Downloads/botbrawlstars/app/test.apk"}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"platformName":"Android","platformVersion":"11","automationName":"uiautomator2","deviceName":"Android Emulator", "app":"/home/lokomanako/Downloads/botbrawlstars/app/test.apk"},null,{"alwaysMatch":{"platformName":"Android","appium:platformVersion":"11","appium :automationName":"uiautomator2","appium:deviceName":"Android Emulator","appium:app":"/home/lokomanako/Downloads/botbrawlstars/app/test.apk"},"firstMatch":[{} ]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1647095062381 (20:24:22 GMT+0600 (Omsk Standard Time))
[Appium] Appium v1.22.2 creating new AndroidUiautomator2Driver (v1.70.1) session
[debug] [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {
[debug] [BaseDriver] "alwaysMatch": {
[debug] [BaseDriver] "platformName": "Android",
[debug] [BaseDriver] "appium:platformVersion": "11",
[debug] [BaseDriver] "appium:automationName": "uiautomator2",
[debug] [BaseDriver] "appium:deviceName": "Android Emulator",
[debug] [BaseDriver] "appium:app": "/home/lokomanako/Downloads/botbrawlstars/app/test.apk"
[debug] [BaseDriver] },
[debug] [BaseDriver] "firstMatch": [
[debug] [BaseDriver] {}
[debug] [BaseDriver] ]
[debug] [BaseDriver] }
[BaseDriver] Session created with session id: c263cb7a-d143-4b96-98be-624fb94a5104
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1647095062393 (20:24:22 GMT+0600 (Omsk Standard Time))
[debug] [W3C] Encountered internal error running command: Error: The application at '/home/lokomanako/Downloads/botbrawlstars/app/test.apk' does not exist or is not accessible
[debug] [W3C] at /usr/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/helpers.js:234:13
[HTTP] <-- POST /wd/hub/session 500 14 ms - 719
[HTTP]

**Comment by KazuCocoa** [comment]
> [debug] [W3C] Encountered internal error running command: Error: The application at '/home/lokomanako/Downloads/botbrawlstars/app/test.apk' does not exist or is not accessible

Please make sure the file is accessible by your appium server

**Comment by Lol437** [comment]
how to check it?

**Comment by KazuCocoa** [comment]
How to check it mean? You should ensure the apk exists in `/home/lokomanako/Downloads/botbrawlstars/app/test.apk` as you specified. You provided it as `"app":"/home/lokomanako/Downloads/botbrawlstars/app/test.apk"`
