### ISSUE TITLE
Max retries exceeded with url: /wd/hub/session happens when i first run

### ISSUE THREAD

**Issue by gangsailian** [appium/python-client#697]
## The problem
When i try to run the following code:
self.driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
failed by 
HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd2e9175cd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

## Environment
Appium version (or git revision) that exhibits the issue: 1.22.0
Desktop OS/version used to run Appium: MacOS
Node.js version (unless using Appium.app|exe): v12.18.3
Real device or emulator/simulator: Iphone 12 pro max
Python: 3.8

**Comment by KazuCocoa** [comment]
it means the python http library was not able to reach the endpoint.
What about using 127.0.0.1 instead of localhost?

**Comment by gangsailian** [comment]
> it means the python http library was not able to reach the endpoint. What about using 127.0.0.1 instead of localhost?
My appreciate! It solve my problem.

**Comment by gangsailian** [comment]
My appreciate! It solve my problem.
