### ISSUE TITLE
Warnigs after migration to Appium client library to 2nd version

### ISSUE THREAD

**Issue by ihorvoitkiv** [appium/python-client#700]
## The problem

After upgrading to appium client library to the 2nd version, I've received warnings for the passed test. There doesn't seem to be a pytest option to output warnings in detail

This seems to be due to selenium 4 version (W3C changes), as **desired_opportunities** have been changed to **options**
Do we have any implemented changes for the appium client library caps?

P.S. Faced with the same warnings in web test automation using selenium 4, and changing the **desired_possibilities** param to **options** solved the problem

## Details

======================== 1 passed, 8 warnings in 51.59s ========================

Process finished with exit code 0
PASSED [100%]

## Environment
- Appium version 1.22.2
- Appium-Python-Client==2.1.4
- pytest==6.2.5
- selenium==4.0.0

## Caps
caps = {
            'app': build_path,
            'platformName': 'iOS',
            'platformVersion': Configs.ios_platform_version,
            'deviceName': Configs.ios_device_name,
            'noReset': False,
            'fullReset': False,
            'autoAcceptAlerts': True,
            'showIOSLog': True,
            'isHeadless': False,
            'clearDeviceLogsOnStart': True,
        }

@pytest.fixture()
def get_driver(request):
    Configs.get()
    url = Configs.appium_server
    caps = get_capabilities(request)
    driver = webdriver.Remote(command_executor=url, desired_capabilities=caps)
    request.cls.driver = driver
    yield driver
    driver.quit()

**Comment by ihorvoitkiv** [comment]
@KazuCocoa

**Comment by KazuCocoa** [comment]
It is expected for now. https://github.com/appium/python-client/issues/640 is the issue.

**Comment by KazuCocoa** [comment]
https://github.com/appium/python-client/issues/680 is to prevent the warning for now.
