### ISSUE TITLE
Unable to locate element using By.ID on hybrid screens

### ISSUE THREAD

**Issue by Juanap12** [appium/python-client#710]
## The problem

I'm trying to make an automation framework that is capable of run tests for web, mobile and hybrid flows. I have a flow that tests the same web view for the Chrome (web) flow and the Android (mobile) flow. Therefore, what I do for the Android flow is that as soon as I get to that screen, I change to the web context and reuse the steps I'm already using for the web flows.

The issue is that it shows me the following error when I try to interact with web locators that use "By.ID":
`selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: invalid locator
  (Session info: chrome=91.0.4472.114)`

When I use Selenium Driver to test the exact same flow but over Google Chrome, it works without problem. But, for Android WebView, it show the previous error.

## Environment
- Appium version (or git revision) that exhibits the issue: Appium-Python-Client 2.2.0
- Desktop OS/version used to run Appium: macOS Big Sur (11.6.5)
- Mobile platform/version under test: Android 12.0
- Real device or emulator/simulator: Emulator
- Appium CLI or Appium.app|exe: Appium Server GUI (1.22.2)

## Details

I already noticed this problem with selenium versions before 4.1.1, were only the 'CSS Selector' locators were working. The selenium dev told me "w3c decided not to define all of the locators that Selenium has traditionally used" (https://titusfortner.com/2021/11/22/shadow-dom-selenium.html#comment-5663633421) and I guess this can be related to what I'm experiencing on Android Web View executions because I tested what would happen if I changed the locator from By.ID to By.CSS_SELECTOR and it worked.

## Code To reproduce issue

The specific command which make me notice this errors is the following:

`WebDriverWait(parent, timeout,
                                 poll_frequency=poll,
                                 ignored_exceptions=[ElementNotVisibleException,
                                                     ElementNotSelectableException,
                                                     StaleElementReferenceException]) \
                .until(expected_conditions.presence_of_element_located(locator))`

Where 'locator' has the following value:

`(By.ID, 'appGuestInfoStepper')`

**Comment by KazuCocoa** [comment]
Yes, it is correct.

> were only the 'CSS Selector' locators were working. The selenium dev told me "w3c decided not to define all of the locators that Selenium has traditionally used"

So far, the id locator is for Appium, not WebDriver like Web context.
Vanilla selenium client converts them to CSS selector internally, but Appium client does not so since Appium needs them. https://github.com/appium/python-client/blob/master/appium/webdriver/webdriver.py#L402-L412

Maybe we should address it in our find_element documentation.
e.g. https://appium.github.io/python-client-sphinx/webdriver.html?highlight=find_element#webdriver.webdriver.WebDriver.find_element

**Comment by Juanap12** [comment]
So, if I understood correctly, I should manually change every locator that I had with "By.ID" to "By.CSS_SELECTOR"?

**Comment by jlipps** [comment]
> So, if I understood correctly, I should manually change every locator that I had with "By.ID" to "By.CSS_SELECTOR"?

Only for web selectors, but yes.
