### ISSUE TITLE
Switching to Python client 2.3.0 is causing problem with external Appium server - TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by momentumsuite** [appium/python-client#726]
## The problem

It was working awesome with v2.2.0 Appium-Python-Client and desired capabilities. But when I switch to v2.3.0 and apply your documentation, I have got a failure. localhost with 4723 port is working fine as you described.

## Environment
- Appium version: 1.22.2
- Desktop OS/version used to run Appium: MacOS/Monterey 12.4
- Node.js version (unless using Appium.app|exe): v16.15.0
- Mobile platform/version under test: Android v10
- Real device or emulator/simulator: Real device
- Appium CLI or Appium.app|exe: Appium CLI

## Details

Command: python3 -m pytest examples/getting-started/first_test.py

Error Message:
examples/getting-started/first_test.py:22: in <module>
    driver = webdriver.Remote('http://momentumv2.mobven.com:8088/wd/hub', options=options, direct_connection=True)
../../Library/Python/3.8/lib/python/site-packages/appium/webdriver/webdriver.py:229: in __init__
    super().__init__(
../../Library/Python/3.8/lib/python/site-packages/selenium/webdriver/remote/webdriver.py:275: in __init__
    self.start_session(capabilities, browser_profile)
../../Library/Python/3.8/lib/python/site-packages/appium/webdriver/webdriver.py:322: in start_session
    self.session_id = response['sessionId']
E   TypeError: 'NoneType' object is not subscriptable

## Link to Appium Logs

No appium logs on console

## Code To reproduce issue

import pytest
from appium import webdriver
from appium.webdriver.common.appiumby import AppiumBy
from appium.options.android import UiAutomator2Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.remote.remote_connection import RemoteConnection
import time

options = UiAutomator2Options().\
    set_capability('momentum:user', 'xxxx').\
    set_capability('momentum:token', 'xxxxxxx').\
    set_capability('momentum:gw', '4033').\
    set_capability('appium:app', 'https://momentumsuite.com/downloads/My-Bank-Wallet-v1.apk').\
    set_capability('appium:autoGrantPermissions', True).\
    set_capability('appium:language', 'en').\
    set_capability('appium:locale', 'en').\
    set_capability('appium:fullReset', True).\
    set_capability('appium:noReset', False).\
    set_capability('appium:deviceName', '').\
    set_capability('appium:udid', '')
driver = webdriver.Remote('http://momentumv2.mobven.com:8088/wd/hub', options=options)

**Comment by mykola-mokhnach** [comment]
This exception means the remote end did not return sessionId in the session creation response, which is against [W3C](https://w3c.github.io/webdriver/#new-session) protocol. I'd probably add better error message there, but there's not much we could do on the client side if the server response is broken.

**Comment by software-testing-bootcamp** [comment]
Sorry for delay,

selenium.common.exceptions.SessionNotCreatedException: Message: A valid W3C session creation response must contain a non-empty "sessionId" entry. Got "{'Error': True, 'Message': 'Object reference not set to an instance of an object.', 'Result': None, 'StatusCode': 500, 'ErrorCode': 0, 'value': None}" instead


My last CAPS setting like this and still not working, I have to use cloud provider user and token in the CAPS instead of URL.

```
options = UiAutomator2Options().load_capabilities({
'platformName': 'Android',
'appium:automationName': 'uiautomator2',
'appium:app': cloudAndroidApp,
'appium:autoGrantPermissions': True,
'appium:language': 'en',
'appium:locale': 'en',
'appium:fullReset': True,
'appium:noReset': False,
'appium:deviceName': '',
'appium:udid': '',
'momentum:options': {
            'user': cloudUser,
            'token': cloudToken,
            'gw': cloudAndroidDeviceName,
        }
})

driver = webdriver.Remote(cloudHost, options=options)
```

**Comment by mykola-mokhnach** [comment]
Sorry, this is not the server log.
To me it looks like the provider does not support W3C session creation protocol format. Have you tried to contact their customer support?

**Comment by momentumsuite** [comment]
Thanks a lot!
