### ISSUE TITLE
send_keys not accepting float values 

### ISSUE THREAD

**Issue by sukh48** [appium/python-client#74]
I am trying to set value for a slider in iOS environment and appium crashes when I set values in float which is a requirement for sliders. 

Here is what I am getting:

seekBar.send_keys(0.5)

keys = (0.5,), file_path = '', typing = [], val = 0.5

    def is_local_file(self, *keys):
        file_path = ''
        typing = []
        for val in keys:
            if isinstance(val, Keys):
                typing.append(val)
            elif isinstance(val, int):
                val = val.__str__()
                for i in range(len(val)):
                    typing.append(val[i])
            else:
               for i in range(len(val)):
                    typing.append(val[i])
                  TypeError: object of type 'float' has no len()

**Comment by imurchie** [comment]
The `send_keys` method takes a `string`. It is up to you to convert the float to a string before passing it to the method. This is standard Selenium behavior and part of the official client (see [here](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/webelement.py#L277)).

**Comment by sukh48** [comment]
thanks
