### ISSUE TITLE
start_activity AttributeError

### ISSUE THREAD

**Issue by pgs-atanistra** [appium/python-client#75]
File "C:\Python34\lib\site-packages\appium\webdriver\webdriver.py", line 552, in start_activity
    for key in arguments.iterkeys():
AttributeError: 'dict' object has no attribute 'iterkeys'

Should be items() ?

**Comment by imurchie** [comment]
Interesting. Python 3 got rid of `dict.iterkeys()` (or, rather, changed it to `dict.iter()`. Silly.

We need the keys, so `dict.keys()`, which doesn't seem to have been removed.
