### ISSUE TITLE
 start_activity  'dict' object has no attribute 'has_key' - python 3.4

### ISSUE THREAD

**Issue by pgs-atanistra** [appium/python-client#77]
After fix #75:

File "C:\Python34\lib\site-packages\appium_python_client-0.14-py3.4.egg\
appium\webdriver\webdriver.py", line 553, in start_activity
if opts.has_key(key):
AttributeError: 'dict' object has no attribute 'has_key'

dict.has_key() was removed, in should be used:

    for key, value in arguments.items():
        if key in opts:
            data[value] = opts[key]
    self.execute(Command.START_ACTIVITY, data)
    return self

start_activity working properly after that change.

**Comment by imurchie** [comment]
Can you open a pull request with this fix?

**Comment by pgs-atanistra** [comment]
Done.

**Comment by monajalal** [comment]
if opts.has_key(key): should be if key in opts: for Python 3.6.3
