### ISSUE TITLE
Install  astroid~=2.12 Error with  pipenv install Pipfile  for Python 3.7.1

### ISSUE THREAD

**Issue by jxliaocb** [appium/python-client#771]
## The problem

When I use python 3.7.1,  run ` pipenv install Pipfile` , there is a "ERROR: No matching distribution found for astroid~=2.12", see the Details.

The reason is in Pipfile, astroid~=2.12,  Check https://pypi.org/project/astroid/2.12.0/,  Requires: Python >=3.7.2

Solution:
Change Pipfile:
astroid = "~=2.11.7"
pylint = "~=2.13.9"

## Environment
Windows 10 
Python 3.7.1

## Details

(python-client) PS C:\projects\python-client> pipenv install Pipfile  
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Installing Pipfile...
Adding Pipfile to Pipfile's [packages]...
Installation Succeeded
Pipfile.lock (c05d97) out of date, updating to (c39c23)...
Locking [packages] dependencies...
 Locking...Building requirements...
       Locking...Resolving dependencies...
Locking Failed!

CRITICAL:pipenv.patched.pip._internal.resolution.resolvelib.factory:Ignored the following versions that require a different python version: 2.12.0 Requires-Python >=3.7.2; 2.12.1 Requires-Python >=3.7.2; 2.12.10 Requires-Python >=3.7.2; 2.12.2 Requires-Python >=3.7.2; 2.12.3 Requires-Python >=3.7.2; 2.12.4 Requires-Python >=3.7.2; 2.12.5 Requires-Python >=3.7.2; 2.12.6 Requires-Python >=3.7.2; 2.12.7 Requires-Python >=3.7.2; 2.12.8 Requires-Python >=3.7.2; 2.12.9 Requires-Python >=3.7.2
CRITICAL:pipenv.patched.pip._internal.resolution.resolvelib.factory:Could not find a version that satisfies the requirement astroid~=2.12 (from versions: 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 2.0.0.dev0, 2.0.0.dev1, 2.0.0.dev2, 2.0.0.dev3, 2.0.0.dev4, 2.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.1.0.dev0, 2.1.0, 2.2.0.dev0, 2.2.0.dev1, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.4.0, 2.4.1, 2.4.2, 2.5, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.5.6, 2.5.7, 2.5.8, 2.6.0.dev0, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.6.6, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.8.0, 2.8.1, 2.8.2.dev0, 2.8.2, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0, 2.11.0, 2.11.1, 
2.11.2, 2.11.3, 2.11.4, 2.11.5, 2.11.6, 2.11.7)
[ResolutionFailure]:   File "C:/vnstudio/lib/site-packages/pipenv/resolver.py", line 783, in _main
[ResolutionFailure]:       pre, clear, verbose, system, write, requirements_dir, packages, dev
[ResolutionFailure]:   File "C:/vnstudio/lib/site-packages/pipenv/resolver.py", line 738, in resolve_packages
[ResolutionFailure]:       requirements_dir=requirements_dir,
[ResolutionFailure]:   File "C:/vnstudio/lib/site-packages/pipenv/resolver.py", line 718, in resolve
[ResolutionFailure]:       req_dir=requirements_dir,
[ResolutionFailure]:   File "C:/vnstudio/lib/site-packages/pipenv\utils\resolver.py", line 1114, in resolve_deps
[ResolutionFailure]:       req_dir=req_dir,
[ResolutionFailure]:   File "C:/vnstudio/lib/site-packages/pipenv\utils\resolver.py", line 894, in actually_resolve_deps        
[ResolutionFailure]:       resolver.resolve()
[ResolutionFailure]:   File "C:/vnstudio/lib/site-packages/pipenv\utils\resolver.py", line 689, in resolve
[ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: No matching distribution found for astroid~=2.12

**Comment by mykola-mokhnach** [comment]
I assume astroid must be moved to dev packages like many other deps there. It makes no sense to me to include them to release env

**Comment by mykola-mokhnach** [comment]
Removed that package completely from the dist. Also, moved all the dev packages to their appropriate section
