### ISSUE TITLE
appium.webdriver.appium_service.AppiumServiceError: Appium has failed to start on 127.0.0.1:4723 within 60000ms timeout

### ISSUE THREAD

**Issue by sujithreddy-gsr** [appium/python-client#775]
## The problem

Failed to start appium programmatically in windows but it is working in Macbook.
Showing error as 
    raise AppiumServiceError(error_msg)
appium.webdriver.appium_service.AppiumServiceError: Appium has failed to start on 127.0.0.1:4723 within 60000ms timeout

## Environment
Windows 10
Python Version : Python 3.10.0
Node Version : v16.17.1
Appium Version : 1.22.3
Appium python client : 2.7.0

##  logs

"C:\Program Files\Python\python.exe" C:/Users/dell/PycharmProjects/pythonProject/TestFile.py
Traceback (most recent call last):
  File "C:\Users\dell\PycharmProjects\pythonProject\TestFile.py", line 12, in <module>
    appium_service.start()
  File "C:\Program Files\Python\lib\site-packages\appium\webdriver\appium_service.py", line 190, in start
    raise AppiumServiceError(error_msg)
appium.webdriver.appium_service.AppiumServiceError: Appium has failed to start on 127.0.0.1:4723 within 60000ms timeout

Process finished with exit code 1

## Code To Reproduce Issue [ Good To Have ]

import time
from appium import webdriver
from appium.webdriver.common.appiumby import AppiumBy

from appium.webdriver.appium_service import AppiumService

appium_service = AppiumService()

appium_service.start()

desired_caps = {}
desired_caps['platformName'] = 'Android'
desired_caps['automationName'] = 'UiAutomator2'
desired_caps['platformVersion'] = '10'
desired_caps['deviceName'] = 'Pixel3XL'
desired_caps['app'] = ('E:\dell\AndroidApp\Android_Appium_Demo.apk') #https://github.com/Skill2Lead/AndroidDemoApp
desired_caps['appPackage'] = 'com.skill2lead.appiumdemo'
desired_caps['appActivity'] = 'com.skill2lead.appiumdemo.MainActivity'

driver = webdriver.Remote("http://127.0.0.1:4723/wd/hub", desired_caps)

ele_id = driver.find_element(AppiumBy.ID,"com.skill2lead.appiumdemo:id/EnterValue")
ele_id.click()

time.sleep(2)

driver.quit()

appium_service.stop()

**Comment by sujithreddy-gsr** [comment]
Hi Mykola , Issue is in appium/python-client in windows.

**Comment by KazuCocoa** [comment]
If you could, can you print the log in https://github.com/appium/python-client/blob/22dfeca560f8f0d5527bfdc0e0200055ee3e30f5/appium/webdriver/appium_service.py#L59 on your local and see what error was raised?

**Comment by sujithreddy-gsr** [comment]
Hi KazuCocoa, Does the code is working from your end??

**Comment by sujithreddy-gsr** [comment]
It is working in Appium-Python-Client==2.1.2 version , But it is not working in latest version of appium python client 2.7.0

pip install Appium-Python-Client==2.1.2

**Comment by KazuCocoa** [comment]
no, since i don't have Win environment for regular use. Let me find and set my old PC up when i have time

**Comment by mykola-mokhnach** [comment]
You must provide `--base-path=/wd/hub` command line argument explicitly if you use the client with Appium 1. Otherwise it defaults to `/`, which is the default one for Appium 2

**Comment by sujithreddy-gsr** [comment]
Hi Mykola, I am executing above appium by program using AppiumService() class.

from appium.webdriver.appium_service import AppiumService

appium_service = AppiumService()
appium_service.start()

Is there any way that we can pass the command line argument from above code?

**Comment by sujithreddy-gsr** [comment]
Seems to be there is some changes b/w the appium python client of 2.1.2 and 2.7.0.

Because it is working in 2.1.2 whereas it is not working in 2.7.0 appium python client.

**Comment by sujithreddy-gsr** [comment]
Hi Mykola, I have added that argument but saw same issue again.

Please find below line of code which i added.

service.start(args=['--address', '127.0.0.1', '-p', str(DEFAULT_PORT),'--base-path=/wd/hub'])

**Comment by mykola-mokhnach** [comment]
Try changing args to: `service.start(args=['--base-path', '/wd/hub'])`

**Comment by KazuCocoa** [comment]
The below may work with appium 2 and latest python client. I would add stdout/stderr in a file to check the server's output. I have tested this on Win 10 and powershell.

```

appium_service = AppiumService()

with open('log.txt', 'w') as f:
    appium_service.start(stdout=f, stderr=f, args=['--base-path', '/wd/hub'])

    try:
        desired_caps = {}
        desired_caps['platformName'] = 'Android'
        desired_caps['automationName'] = 'UiAutomator2'
        desired_caps['platformVersion'] = '10'
        desired_caps['deviceName'] = 'Pixel3XL'
        desired_caps['udid'] = '<your connected device>'
        desired_caps['app'] = ('https://github.com/appium/ruby_lib_core/blob/master/test/functional/app/api.apk.zip?raw=true')
        desired_caps['appPackage'] = 'io.appium.android.apis'
        desired_caps['appActivity'] = 'io.appium.android.apis.ApiDemos'

        driver = webdriver.Remote("http://127.0.0.1:4723/wd/hub", desired_caps)

        time.sleep(2)

        driver.quit()
    finally:
        appium_service.stop()
```

**Comment by sujithreddy-gsr** [comment]
Hi KazuCocoa,

Now its working after add args as " appium_service.start(args=['--base-path', '/wd/hub'])"

import time
from appium import webdriver
from appium.webdriver.common.appiumby import AppiumBy

from appium.webdriver.appium_service import AppiumService

appium_service = AppiumService()

appium_service.start(args=['--base-path', '/wd/hub'])

desired_caps = {}
desired_caps['platformName'] = 'Android'
desired_caps['automationName'] = 'UiAutomator2'
desired_caps['platformVersion'] = '10'
desired_caps['deviceName'] = 'Pixel3XL'
desired_caps['app'] = ('E:\dell\AndroidApp\Android_Appium_Demo.apk') #https://github.com/Skill2Lead/AndroidDemoApp
desired_caps['appPackage'] = 'com.skill2lead.appiumdemo'
desired_caps['appActivity'] = 'com.skill2lead.appiumdemo.MainActivity'

driver = webdriver.Remote("http://127.0.0.1:4723/wd/hub", desired_caps)

ele_id = driver.find_element(AppiumBy.ID,"com.skill2lead.appiumdemo:id/EnterValue")
ele_id.click()

time.sleep(2)

driver.quit()

appium_service.stop()

**Comment by sudeepyadav5** [comment]
from appium import webdriver
from appium.webdriver.common.appiumby import AppiumBy
import time

# Step 1 : Import Appium Service class
from appium.webdriver.appium_service import AppiumService

# Step 2 : Create object for Appium Service class
appium_service = AppiumService()

# Step 3 : Call Start method by using Appium Service class object
appium_service.start(args=['--base-path', '/wd/hub'])

# Step 4 : Create "Desired Capabilities"
desired_caps = {}
desired_caps['platformName'] = 'Android'
desired_caps['automationName'] = 'UiAutomator2'
desired_caps['platformVersion'] = '10'
desired_caps['deviceName'] = 'Xiaomi M2006C3MII'
desired_caps['app'] = 'C:/Users/3Embed/Python_Ast/ApkFile/Android_Demo_App.apk'
desired_caps['appPackage'] = 'com.code2lead.kwad'
desired_caps['appActivity'] = 'com.code2lead.kwad.MainActivity'

driver = webdriver.Remote("http://127.0.0.1:4723/wd/hub", desired_caps)

ele_id = driver.find_element(AppiumBy.ID,"com.skill2lead.appiumdemo:id/EnterValue")
ele_id.click()

time.sleep(5)
driver.quit()

# Step 5 : Call stop method by using Appium Service class object
appium_service.stop()

**Comment by sudeepyadav5** [comment]
File "C:\Users\3Embed\PycharmProjects\AppiumPythonDemo\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Neither ANDROID_HOME nor ANDROID_SDK_ROOT environment variable was exported. Read https://developer.android.com/studio/command-line/variables for more details
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Neither ANDROID_HOME nor ANDROID_SDK_ROOT environment variable was exported. Read https://developer.android.com/studio/command-line/variables for more details
    at getResponseForW3CError (C:\Users\3Embed\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
    at asyncHandler (C:\Users\3Embed\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:380:37)

Process finished with exit code 1
this is the error some one can help me to solve this issue

**Comment by eglitise** [comment]
@sudeepyadav5 your error is not related to this issue. You are also using Appium 1, which is no longer supported. Consider updating to Appium 2, then follow [the documentation for setting up Android automation](http://appium.io/docs/en/2.0/quickstart/uiauto2-driver/).

**Comment by Shantham1234** [comment]
Can you help me to solve this?
appium.webdriver.appium_service.AppiumServiceError: NodeJS main executable cannot be found. Make sure it is installed and present in PATH

**Comment by KazuCocoa** [comment]
Perhaps your NodeJS installation has not been completed yet to make it exexutable. https://discuss.appium.io/ could help to ask such a general question
