### ISSUE TITLE
Click action reports success then app crashes without appium error 

### ISSUE THREAD

**Issue by crgbaumgart** [appium/python-client#79]
ENV: iOS 8.3 real device, MAC, Appium 1.3.7, appium-python-client 0.14.

A once selectable button in my app's UI, is now, not selectable via .click()/.tap() methods. Additionally, if I instantiate a ruby console appium session, I am able to use the appium inspector tool to successfully select the element. 

I'm not confident that this is an appium related issue, but I have exhausted all my debugging resources and have come here. Appium reports that the element was successfully clicked according to the appium logs, then immediately there after the app crashes. I am unable to reproduce the button error with manual testing. 

I've attached appium and ios logs below: 

Thanks for any assistance.   

The appium logs are: 
info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: "au.getElementByName('Settings')"
info: [debug] Sending command to instruments: au.getElementByName('Settings')
info: [debug] [INST] 2015-04-28 17:06:42 +0000 Debug: Got new command 39 from instruments: au.getElementByName('Settings')
info: [debug] [INST] 2015-04-28 17:06:42 +0000 Debug: evaluating au.getElementByName('Settings')
info: [debug] [INST] 2015-04-28 17:06:42 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-04-28 17:06:42 +0000 Debug: responding with:
info: [debug] [INST] 2015-04-28 17:06:42 +0000 Debug: Running system command #40: /usr/local/Cellar/node/0.12.0/bin/node /Users/craig/git/appium/submodules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...
info: [debug] Socket data received (25 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":""}
info: [debug] Condition unmet after 734ms. Timing out.
info: [debug] Responding to client with error: {"status":7,"value":{"message":"An element could not be located on the page using the given search parameters.","origValue":""},"sessionId":"4c331478-3f8d-444a-b22f-52dcce9ed622"}
info: <-- POST /wd/hub/session/4c331478-3f8d-444a-b22f-52dcce9ed622/element 500 734.772 ms - 179
info: --> POST /wd/hub/session/4c331478-3f8d-444a-b22f-52dcce9ed622/element {"using":"name","sessionId":"4c331478-3f8d-444a-b22f-52dcce9ed622","value":"now_playing.search_btn"}
info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: "au.getElementByName('now_playing.search_btn')"
info: [debug] Sending command to instruments: au.getElementByName('now_playing.search_btn')
info: [debug] [INST] 2015-04-28 17:07:24 +0000 Debug: Got new command 40 from instruments: au.getElementByName('now_playing.search_btn')
info: [debug] [INST] 2015-04-28 17:07:24 +0000 Debug: evaluating au.getElementByName('now_playing.search_btn')
info: [debug] [INST] 2015-04-28 17:07:25 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-04-28 17:07:25 +0000 Debug: Lookup returned [object UIAButton] with the name "now_playing.search_btn" (id: 7).
info: [debug] [INST] 2015-04-28 17:07:25 +0000 Debug: responding with:
info: [debug] [INST] 2015-04-28 17:07:25 +0000 Debug: Running system command #41: /usr/local/Cellar/node/0.12.0/bin/node /Users/craig/git/appium/submodules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"ELEMENT":"7"}}...
info: [debug] Socket data received (38 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"ELEMENT":"7"}}
info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"7"},"sessionId":"4c331478-3f8d-444a-b22f-52dcce9ed622"}
info: <-- POST /wd/hub/session/4c331478-3f8d-444a-b22f-52dcce9ed622/element 200 661.038 ms - 87 {"status":0,"value":{"ELEMENT":"7"},"sessionId":"4c331478-3f8d-444a-b22f-52dcce9ed622"}
info: --> POST /wd/hub/session/4c331478-3f8d-444a-b22f-52dcce9ed622/element/7/click {"sessionId":"4c331478-3f8d-444a-b22f-52dcce9ed622","id":"7"}
info: [debug] Pushing command to appium work queue: "au.tapById('7')"
info: [debug] Sending command to instruments: au.tapById('7')
info: [debug] [INST] 2015-04-28 17:07:26 +0000 Debug: Got new command 41 from instruments: au.tapById('7')
info: [debug] [INST] 2015-04-28 17:07:26 +0000 Debug: evaluating au.tapById('7')
info: [debug] [INST] 2015-04-28 17:07:26 +0000 Debug: UIAButton.tap()
info: [debug] Socket data received (25 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":""}
info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"4c331478-3f8d-444a-b22f-52dcce9ed622"}
info: <-- POST /wd/hub/session/4c331478-3f8d-444a-b22f-52dcce9ed622/element/7/click 200 1246.794 ms - 74 {"status":0,"value":"","sessionId":"4c331478-3f8d-444a-b22f-52dcce9ed622"}
info: --> POST /wd/hub/session/4c331478-3f8d-444a-b22f-52dcce9ed622/element {"using":"xpath","sessionId":"4c331478-3f8d-444a-b22f-52dcce9ed622","value":"//UIATextField[@value = 'search']"}
info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
info: [debug] Sending command to instruments: au.mainApp().getTreeForXML()
info: [debug] [INST] 2015-04-28 17:07:26 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-04-28 17:07:26 +0000 Debug: responding with:
info: [debug] [INST] 2015-04-28 17:07:26 +0000 Debug: Running system command #42: /usr/local/Cellar/node/0.12.0/bin/node /Users/craig/git/appium/submodules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...
info: [debug] [INST] 2015-04-28 17:07:26 +0000 Fail: The target application appears to have died
info: [debug] [INST STDERR] 2015-04-28 10:07:26.640 instruments[31436:1517626] Attempting to set event horizon when core is not engaged, request ignored
info: [debug] [INST STDERR] 2015-04-28 10:07:26.640 instruments[31436:1517626] Attempting to set event horizon when core is not engaged, request ignored
info: [debug] [INST] Instruments Trace Complete (Duration : 115.550438s; Output : /tmp/appium-instruments/instrumentscli0.trace)
info: [debug] [INSTSERVER] Instruments exited with code 0
info: [debug] Cleaning up after instruments exit
info: [debug] Instruments exited unexpectedly
info: [debug] Shutting down command proxy and ignoring any errors
info: [debug] Closing socket server.
info: [debug] Instruments socket server was closed
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killall iOS Simulator
info: [debug] Killing any other simulator daemons
info: [debug] On a real device; cannot clean device state
info: [debug] We were in the middle of processing a command when instruments died; responding with a generic error
info: [debug] Cleaning up appium session
error: Error getting source, can't continue finding element by XPath
info: [debug] Condition unmet after 751ms. Timing out.
info: [debug] Responding to client with error: {"status":13,"value":{"message":"Instruments died while responding to command, please check appium logs","name":"UnknownError","origValue":"Instruments died while responding to command, please check appium logs"},"sessionId":null}
info: <-- POST /wd/hub/session/4c331478-3f8d-444a-b22f-52dcce9ed622/element 500 752.216 ms - 230
info: --> POST /wd/hub/session/4c331478-3f8d-444a-b22f-52dcce9ed622/element {"using":"xpath","sessionId":"4c331478-3f8d-444a-b22f-52dcce9ed622","value":"//*[(@name = 'now_playing.play') or (@name = 'now_playing.pause')]"}
info: <-- POST /wd/hub/session/4c331478-3f8d-444a-b22f-52dcce9ed622/element 404 0.691 ms - 40

iOS Logs:

Apr 28 10:07:26 Craig-Baumgartens-iPhone MobileGestaltHelper[81] <Error>: libMobileGestalt MobileGestalt.c:273: server_access_check denied access to question UniqueDeviceID for pid 3432
Apr 28 10:07:26 Craig-Baumgartens-iPhone ScriptAgent[3432] <Error>: libMobileGestalt MobileGestaltSupport.m:170: pid 3432 (ScriptAgent) does not have sandbox access for re6Zb+zwFKJNlkQTUeT+/w and IS NOT appropriately entitled
Apr 28 10:07:26 Craig-Baumgartens-iPhone ScriptAgent[3432] <Error>: libMobileGestalt MobileGestalt.c:534: no access to UniqueDeviceID (see <rdar://problem/11744455>)
Apr 28 10:07:26 Craig-Baumgartens-iPhone ReportCrash[3434] <Error>: task_set_exception_ports(B07, 400, D03, 0, 0) failed with error (4: (os/kern) invalid argument)
Apr 28 10:07:26 Craig-Baumgartens-iPhone ReportCrash[3434] <Notice>: ReportCrash acting against PID 3431
Apr 28 10:07:26 Craig-Baumgartens-iPhone ReportCrash[3434] <Notice>: Formulating crash report for process Aether Cone[3431]
Apr 28 10:07:26 Craig-Baumgartens-iPhone locationd[57] <Notice>: Gesture EnabledForTopCLient: 0, EnabledInDaemonSettings: 0
Apr 28 10:07:26 Craig-Baumgartens-iPhone locationd[57] <Notice>: Gesture EnabledForTopCLient: 0, EnabledInDaemonSettings: 0
Apr 28 10:07:26 Craig-Baumgartens-iPhone locationd[57] <Notice>: Gesture EnabledForTopCLient: 0, EnabledInDaemonSettings: 0
Apr 28 10:07:26 Craig-Baumgartens-iPhone locationd[57] <Notice>: Gesture EnabledForTopCLient: 0, EnabledInDaemonSettings: 0
Apr 28 10:07:26 Craig-Baumgartens-iPhone com.apple.xpc.launchd[1] (UIKitApplication:com.aether.cone[0x8f61][3431]) <Notice>: Service exited due to signal: Segmentation fault: 11
Apr 28 10:07:26 Craig-Baumgartens-iPhone SpringBoard[50] <Warning>: Unable to get short BSD proc info for 3431: No such process
Apr 28 10:07:26 Craig-Baumgartens-iPhone ReportCrash[3434] <Notice>: Saved report to /var/mobile/Library/Logs/CrashReporter/Aether Cone_2015-04-28-100726_Craig-Baumgartens-iPhone.ips
Apr 28 10:07:26 Craig-Baumgartens-iPhone SpringBoard[50] <Warning>: Application 'UIKitApplication:com.aether.cone[0x8f61]' crashed.
Apr 28 10:07:26 Craig-Baumgartens-iPhone assertiond[60] <Warning>: pid_suspend failed for <BKNewProcess: 0x100150450; com.aether.cone; pid: 3431; hostpid: -1>: Unknown error: -1, Unknown error: -1
Apr 28 10:07:26 Craig-Baumgartens-iPhone assertiond[60] <Warning>: Could not set priority of <BKNewProcess: 0x100150450; com.aether.cone; pid: 3431; hostpid: -1> to 2, priority: No such process
Apr 28 10:07:26 Craig-Baumgartens-iPhone assertiond[60] <Warning>: Could not set priority of <BKNewProcess: 0x100150450; com.aether.cone; pid: 3431; hostpid: -1> to 4096, priority: No such process
Apr 28 10:07:26 Craig-Baumgartens-iPhone UserEventAgent[17] <Warning>: id=com.aether.cone pid=3431, state=0
Apr 28 10:07:27 Craig-Baumgartens-iPhone DTMobileIS[194] <Warning>: Could not create service named com.apple.instruments.server.services.processcontrol.posixspawn
Apr 28 10:07:27 Craig-Baumgartens-iPhone DTMobileIS[194] <Warning>: Could not create service named com.apple.instruments.server.services.launchdaemon
Apr 28 10:07:27 Craig-Baumgartens-iPhone notification_proxy[133] <Error>: 0x100584000 -[MNPLockdownConnection receiveMessage]: lockdown_receive_message error!
Apr 28 10:07:27 Craig-Baumgartens-iPhone notification_proxy[133] <Error>: 0x10060c000 -[MNPLockdownConnection receiveMessage]: lockdown_receive_message error!
Apr 28 10:07:27 Craig-Baumgartens-iPhone locationd[57] <Notice>: Gesture EnabledForTopCLient: 0, EnabledInDaemonSettings: 0
Apr 28 10:07:40 Craig-Baumgartens-iPhone kernel[0] <Notice>: 1119287.328542 wlan0.A[70186] AppleBCMWLANConfigManager::configureRoamingProfile(): Received new roaming profile 3 (was 3, flag=0x0)

**Comment by imurchie** [comment]
This works on a real device using some tool? I'm not sure why the Python client would make a difference.

The errors look like it is trying to start an app that is not automatable. Or that the button is attempting to start another application. That is not the case, correct?

**Comment by crgbaumgart** [comment]
Pardon the extraneous env info. 

And correct. I know my developer recently upgraded the app to be compiled as 64 bit app, don't think that has anything to do with this. 

I've attempted to locate the element via xpath, name, and even a location based .click()/.tap(), but still nothing. 

Also, I misspoke above. The ruby_console/inspector method only works 50% of the time. Leaving me more confused.. Could appium possibly be locating a duplicate object in that same spot, then trying to interact with a non-active element? There is a possibility theres an element hidden in the desired button's location

**Comment by imurchie** [comment]
I would expect interacting with a non-active element would not cause the app to crash, it would just say that the element could not be clicked. I'm not sure about this case.

**Comment by crgbaumgart** [comment]
Closing ticket. Developer still doesn't know how he fixed it. But the issue was on our end.

**Comment by imurchie** [comment]
I'm glad it was resolved, even if in unknown ways. Thanks!
