### ISSUE TITLE
How to delete IOS app from real device

### ISSUE THREAD

**Issue by jainswati02** [appium/python-client#83]
I am trying to delete ios app from real device but no luck.
Can we do that on a real Ipad. Please suggest

I tried "/usr/local/bin/ideviceinstaller","-u",deviceUDID, "-U", appBundleID  but it is not working locally too

**Comment by marloncruz** [comment]
@jainswati02 
driver.remove_app('com.example.android.apis')

**Comment by claudemasso** [comment]
This does not work anymore with Appium 1.5

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/blob/master/CHANGELOG.md#changes-in-version-180-from-172
