### ISSUE TITLE
Returns unexpected entries on Android 13 Galaxy Z Flip 4

### ISSUE THREAD

**Issue by carbonheartt** [appium/python-client#832]
When trying to run app & activity, it is excuted well on real device but below error is occured.

[ADB] Getting focused package and activity
[ADB] Running '/Users/XXXXX/Library/Android/sdk/platform-tools/adb -P 5037 -s XXXXXXXXXXX shell dumpsys window displays'
[ADB] Found package: 'com.android.systemui' and fully qualified activity name : 'com.android.systemui.subscreen.SubHomeActivity'
[ADB] Incorrect package and activity. Retrying.

I guess below is same issue, but can I get solution for python environment?

https://github.com/appium/appium/issues/17106
https://github.com/appium/appium-adb/pull/604

## Environment
- Appium version (or git revision) that exhibits the issue: Appium Python Client 2.8.1
- Desktop OS/version used to run Appium: macOS Ventura 13.2.1
- Mobile platform/version under test: Android 13
- Real device or emulator/simulator: Galaxy Z Flip 4

**Comment by KazuCocoa** [comment]
What version of Appium/UIA2 driver did you use? The attached ones are server side stuff, so please use the latest UIA2 with Appium2.0 first

**Comment by carbonheartt** [comment]
Updated Appium/UIA2 but it still occurs. Anyway, I decided to do not use start_activity and test is not stucking.

[Appium] Welcome to Appium v2.0.0-beta.55
[Appium] Attempting to load driver uiautomator2...
[debug] [Appium] Requiring driver at /Users/1112491/.appium/node_modules/appium-uiautomator2-driver
[Appium] Attempting to load driver xcuitest...
[debug] [Appium] Requiring driver at /Users/1112491/.appium/node_modules/appium-xcuitest-driver
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] Available drivers:
[Appium]   - uiautomator2@2.12.5 (automationName 'UiAutomator2')
[Appium]   - xcuitest@4.18.0 (automationName 'XCUITest')
[Appium] Available plugins:
[Appium]   - images@2.0.6
[Appium]   - execute-driver@3.0.6
