### ISSUE TITLE
how to resolve signature issue when running appium

### ISSUE THREAD

**Issue by vbpatel73** [appium/python-client#841]
[UiAutomator2] Waiting up to 30000ms for UiAutomator2 to be online...
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","R58R36842KN","shell","am","instrument","-w","-e","disableAnalytics",true,"io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner"]
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8200/wd/hub/status] with no body
[WD Proxy] socket hang up
[debug] [Instrumentation] java.lang.SecurityException: Permission Denial: starting instrumentation ComponentInfo{io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner} from pid=15386, uid=2000 not allowed because package io.appium.uiautomator2.server.test does not have a signature matching the target io.appium.uiautomator2.server
[debug] [Instrumentation] at android.os.Parcel.createExceptionOrNull(Parcel.java:3023)
[debug] [Instrumentation]       at android.os.Parcel.createException(Parcel.java:3007)
[debug] [Instrumentation]       at android.os.Parcel.readException(Parcel.java:2990)
[debug] [Instrumentation]       at android.os.Parcel.readException(Parcel.java:2932)
[debug] [Instrumentation]       at android.app.IActivityManager$Stub$Proxy.startInstrumentation(IActivityManager.java:6399)  
[debug] [Instrumentation]       at com.android.commands.am.Instrument.run(Instrument.java:532)
[debug] [Instrumentation]       at com.android.commands.am.Am.runInstrument(Am.java:208)
**### [debug] [Instrumentation] INSTRUMENTATION_STATUS: Error=Permission Denial: starting instrumentation ComponentInfo{io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner} from pid=15386, uid=2000 not allowed because package io.appium.uiautomator2.server.test does not have a signature matching the target io.appium.uiautomator2.server**
[debug] [Instrumentation] INSTRUMENTATION_STATUS: id=ActivityManagerService
[debug] [Instrumentation] INSTRUMENTATION_STATUS_CODE: -1
[debug] [Instrumentation] at com.android.commands.am.Am.onRun(Am.java:85)
[debug] [Instrumentation]       at com.android.internal.os.BaseCommand.run(BaseCommand.java:62)
[debug] [Instrumentation]       at com.android.commands.am.Am.main(Am.java:54)
[debug] [Instrumentation]       at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
[debug] [Instrumentation]       at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:378)
[debug] [Instrumentation] Caused by: android.os.RemoteException: Remote stack trace:
[debug] [Instrumentation]       at com.android.server.am.ActivityManagerService.startInstrumentation(ActivityManagerService.java:17202)
[debug] [Instrumentation]       at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3036)
[debug] [Instrumentation]       at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3077) 
[debug] [Instrumentation]       at android.os.Binder.execTransactInternal(Binder.java:1316)
[debug] [Instrumentation]       at android.os.Binder.execTransact(Binder.java:1280)
[debug] [Instrumentation] The process has exited with code 1
[UiAutomator2] The instrumentation process cannot be initialized. Make sure the application under test does not crash and investigate the logcat output.

**Comment by mykola-mokhnach** [comment]
Try https://github.com/appium/appium-uiautomator2-driver#session-startup-issues
