### ISSUE TITLE
Tapping with coordinates is tapping twice

### ISSUE THREAD

**Issue by casschin** [appium/python-client#85]
I've been trying to execute a single point tap, with both driver.tap and TouchActions with an offset, and it's doing two taps actions. The timing between the two taps vary. Sometimes it's super fast, other times it's a little slower. 

I'm using identical code that's used in the readme with a test I'm writing for an Android app:

```
action.tap(el, 100, 100).perform()
driver.tap(100, 100)
```

Has anyone else experienced this?

**Comment by imurchie** [comment]
Can you give a little more information? The Appium server log would be ideal.

Thanks.
