### ISSUE TITLE
Issue with current_activity in 2.10.0

### ISSUE THREAD

**Issue by kakooloukia** [appium/python-client#865]
## Breaking change in 2.10.0
**WebDriverException: Message: Unknown mobile command "getCurrentActivity"**

## Environment
- Appium-Python-Client-2.10.0
- Android 10
- UiAutomator2

## Details

![image](https://github.com/appium/python-client/assets/52101924/617b46de-7fa8-4d1a-a556-576cbd9e867b)

## Breaking Change:
![image](https://github.com/appium/python-client/assets/52101924/2241868b-06dd-49b0-b72a-b85c29cc8c6a)
source [appium/webdriver/extensions/android/activities.py](https://github.com/appium/python-client/compare/v2.9.0...master#diff-5f03459b034110b120fd24abae517d2bf9c1e93faa5d55e31dae9117b5309849)

## Code To reproduce issue
open a driver with android UiAutomator on an android device and run `driver.current_activity`

**Comment by kakooloukia** [comment]
The fallbacks is not working : https://github.com/appium/python-client/blob/a369b6fa9efee502a31349a6a84dd1cdd9c5d070/appium/webdriver/webdriver.py#L505-L517

`self._absent_extensions` is empty, so `return self` instead `UnknownMethodException`

**Comment by kakooloukia** [comment]
3 Solutions:
- feed `self._absent_extensions` during the driver creation
- remove `UnknownMethodException` exception filter
- add and use `self._activated_extensions`

**Comment by chrisgraham24** [comment]
Can we expect a fix for this? Or do we need to just use 2.9.0?

**Comment by KazuCocoa** [comment]
Please use 2.9.0 right now

**Comment by KazuCocoa** [comment]
2.10.1 has the fix.
