### ISSUE TITLE
Will Instruments die while responding to appium command?

### ISSUE THREAD

**Issue by ChenFromNB** [appium/python-client#88]
When I use Appium(version 1.3.4) for iOS automation, the Appium client stopped and I get the crash message as the picture showed below, the iPhone has been running about 12 hours. Is there a way to solve the problem?
![2015-06-05 11 07 09](https://cloud.githubusercontent.com/assets/4630185/7998730/428b5338-0b73-11e5-967d-6701d41aecfa.png)

**Comment by imurchie** [comment]
Can you provide the Appium server logs? Instruments does occasionally crash, but without the logs it's difficult to say what the problem might be.
