### ISSUE TITLE
Selenium breaking change

### ISSUE THREAD

**Issue by kakooloukia** [appium/python-client#880]
https://github.com/appium/python-client/blob/2f45ef935c12dec2ab8de044ce6a1c1e0b9aa46f/Pipfile#LL22C1-L22C19

``` 
File "/home/jenkins_slave/.local/lib/python3.9/site-packages/appium/webdriver/webdriver.py", line 235, in __init__
    super().__init__(
TypeError: __init__() got an unexpected keyword argument 'desired_capabilities'
```
Fixed on my side with selenium "~=4.9.0"

**Comment by tim-corley-bose** [comment]
+1 - same issue here. had to downgrade to `4.9.1`

**Comment by KazuCocoa** [comment]
Duplicated of https://github.com/appium/python-client/issues/878

**Comment by chrisgraham24** [comment]
APC 3.0.0 and Selenium 4.13.0 and this is still happening
