### ISSUE TITLE
No module named 'appium.webdriver.common.appiumby'

### ISSUE THREAD

**Issue by NguyenLamIT** [appium/python-client#883]
## The problem
Hi all. When I imported appiumby like "from appium.webdriver.common.appiumby import AppiumBy". I met an error like below:

> D:\GC\python\puzzle-captcha-resolver>python main.py
> Traceback (most recent call last):
>   File "D:\GC\python\puzzle-captcha-resolver\main.py", line 2, in <module>
>     from tasks.appium.multi_thread_tiktok_app import MultiThreadTiktokApp
>   File "D:\GC\python\puzzle-captcha-resolver\tasks\appium\multi_thread_tiktok_app.py", line 8, in <module>
>     from pages.appium.tiktok_app import TiktokApp
>   File "D:\GC\python\puzzle-captcha-resolver\pages\appium\tiktok_app.py", line 24, in <module>
>     from appium.webdriver.common.appiumby import AppiumBy
> ModuleNotFoundError: No module named 'appium.webdriver.common.appiumby'

Anyone here met that? Please help me
Thanks you

## Environment
- Python 310
- Appium-Python-Client version 1.1
- Selenium 3.141

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium Logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.

## Code To reproduce issue
```
from appium.webdriver.common.touch_action import TouchAction
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.actions import interaction
from selenium.webdriver.common.actions.action_builder import ActionBuilder
from selenium.webdriver.common.actions.pointer_input import PointerInput
from appium.webdriver.common.appiumby import AppiumBy
```

**Comment by KazuCocoa** [comment]
Please try out client version 2.1.0 and later for AppiumBy
https://github.com/appium/python-client/blob/master/CHANGELOG.rst#v210-2021-11-27
