### ISSUE TITLE
The duration argument of WebDriver.tap is inconsistent between code and doc.

### ISSUE THREAD

**Issue by WKPlus** [appium/python-client#89]
I found the doc and code inconsistent in `WebDriver.tap` method.

The doc of `WebDriver.tap` says argument `duration` is in milliseconds:
> \- duration - (optional) length of time to tap, in ms

But the code deal with duration as it's in seconds:

```
if duration:
    duration *= 1000  # we take seconds, but send milliseconds
    action.long_press(x=x, y=y, duration=duration).release()
```

Am I misunderstand anything?

**Comment by imurchie** [comment]
You are not misunderstanding things. You'll also notice that the duration is treated as `ms` in the case of the single tap. Alas. This is a bug. Thanks for noticing and bringing it to our attention!
