### ISSUE TITLE
Remove IOS_UIAUTOMATION

### ISSUE THREAD

**Issue by KazuCocoa** [appium/python-client#913]
the locator is no longer used

**Comment by lana-20** [comment]
### FYI: Similar Deprecations in Java & Ruby

Hi Kazu, 

I was about to raise an issue about deprecating the **IOS_UIAUTOMATION** locator strategy, but came across this one instead.

There've been analogous deprecations in [Java](https://github.com/appium/java-client/commit/0cb3fcbd5443e904f246d5d21a4393d5feda5531) and [Ruby](https://github.com/appium/ruby_lib_core/commit/9b9f18611c4bd9168f982270d9e6acf0b4cf6005).

**Java** Deprecation description: "_UIAutomation is going to get deprecated. It is recommended to use XCUITest._"

**Ruby** Deprecation description: "_Remove iOS/UiAutomation classes. The version may work for iOS 8. XCUITest driver will be the default behavior for iOS._"

Cheers, 
-Lana

**Comment by zeufack** [comment]
Hello, is this still open ? Want to work on it

**Comment by KazuCocoa** [comment]
Yes

**Comment by zeufack** [comment]
ok, i'll try to work on it

**Comment by zeufack** [comment]
hello, please should i add a Deprecation description or just remove the IOS_UIAUTOMATION logic ?

**Comment by KazuCocoa** [comment]
I think you could remove the locator simply because the locator works only for legacy Appium iOS driver, which no longer works for so long and has been removed over a couple of years or more already.

**Comment by zeufack** [comment]
ok !
