### ISSUE TITLE
Not clear what I should be using instead of 'desired_capabilities'

### ISSUE THREAD

**Issue by chrisgraham24** [appium/python-client#916]
## The problem

Using APC==3.0.0 and Selenium==4.13.0 (and Python 3.9.6) I am getting: 
`TypeError: __init__() got an unexpected keyword argument 'desired_capabilities'`
I have seen a lot of these tickets get closed, but I still am not clear on what exactly I should be using instead of desired caps for my iOS and Android Appium tests using these versions. Please do not just close this and link an already closed ticket. I want to know what I should be using instead...thank you!

## Environment
- Appium version (or git revision) that exhibits the issue: **3.0.0**
- Mobile platform/version under test: **iOS and Android**
- Real device or emulator/simulator: **Real**
- Appium CLI or Appium.app|exe: **CLI**

**Comment by mykola-mokhnach** [comment]
You should be using driver-specific or generic options. Check https://github.com/appium/python-client#usage

**Comment by chrisgraham24** [comment]
Is there a list of driver-specific options? Do they translate from Desired Capabilities. Just seems such a massive change should be better documented...

**Comment by mykola-mokhnach** [comment]
Unfortunately, the documentation has never been a strong side of this project, especially the part that targets beginners. You could always help yourself and others by improving it.

Look at https://github.com/appium/python-client/tree/master/appium/options if you want to find specific option implementations
