### ISSUE TITLE
Lack of the start_activity method in WebDriver class.

### ISSUE THREAD

**Issue by wojciu94** [appium/python-client#917]
## The problem
I was using the start_activity method to start an activity if the application was created during the session. In Appium-Python-Client 3.0.0 there is no such method. I found that I should use the method mobile: startActivity. But there is no such method in the Applications class (appium.webdriver.extensions.applications.Applications). Also, there is no such command in the MobileCommand class (appium.webdriver.mobilecommand.MobileCommand).

How can I use the method to start an activity, by using the command mobile: startActivity?

## Environment
- Appium version (or git revision) that exhibits the issue: Appium-Python-Client 3.0.0
- Last Appium version that did not exhibit the issue (if applicable): Appium-Python-Client 2.11.1

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/python-client/blob/fa7ba6ee5ee91c914f69e34547993af62995462f/test/functional/android/activities_tests.py#L26

**Comment by wojciu94** [comment]
Thank you for your answer. The method from your link works for me.
