### ISSUE TITLE
'NoneType' object has no attribute 'to_capabilities' is displayed

### ISSUE THREAD

**Issue by RYenike** [appium/python-client#918]
## The problem

Unable to initialize appium driver. 

## Environment
- Appium version (or git revision) that exhibits the issue: 1.22.3
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: Windows 11
- Node.js version (unless using Appium.app|exe): 18.18.0
- Mobile platform/version under test: Android 12
- Real device or emulator/simulator:Real Device
- Appium CLI or Appium.app|exe: Appium.applexe
- Appium - Python -Client - 2.11.1
- Selenium - 4.7.2

## Code To reproduce issue

desired_cap = {
    "appium:uuid": f"{serial}",
    "platformName": "Android",
    "appium:platformVersion" : f"{platform_version}",
    "appium:deviceName": 'Pixel 4 API 29',
    "automationName": 'UiAutomator2',
    "appium:app": f"{apk_Path}"
}
driver = webdriver.Remote("http://localhost:4723/wd/hub", desired_cap)

ERROR - [2023-09-29_12:53:20] Traceback (most recent call last):
  File "C:\Users\spolnati\Desktop\local\CD_IQConnect\TestFramework\test_suites\Mobile_application\functional.py", line 94, in verify_joinmeeting
    driver = desired_caps_android("Daikin", "Mobile Application", self.serial)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\spolnati\Desktop\local\CD_IQConnect\TestFramework\utilities\libraries\lib_functions.py", line 2490, in desired_caps_android
    driver = webdriver.Remote("[http://127.0.0.1:4723/wd/hub"](http://127.0.0.1:4723/wd/hub%22), desired_cap)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3115\Lib\site-packages\appium\webdriver\webdriver.py", line 229, in __init__
    super().__init__(
  File "C:\Python3115\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 185, in __init__
    capabilities = options.to_capabilities()
                   ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'to_capabilities'

**Comment by KazuCocoa** [comment]
I'm not sure what selenium client version your environment had, but you might need to follow options style:
https://github.com/appium/python-client?tab=readme-ov-file#usage

This is compatibility matrix:
https://github.com/appium/python-client?tab=readme-ov-file#compatibility-matrix

**Comment by AdrianoSandry** [comment]
> [RYenike](/RYenike)
Try this:

from appium.options.android import UiAutomator2Options

desired_cap = {
"appium:uuid": f"{serial}",
"platformName": "Android",
"appium:platformVersion" : f"{platform_version}",
"appium:deviceName": 'Pixel 4 API 29',
"automationName": 'UiAutomator2',
"appium:app": f"{apk_Path}"
}

options = UiAutomator2Options().load_capabilities(desired_cap)
driver = webdriver.Remote("http://localhost:4723/wd/hub", options=options)

**Comment by RYenike** [comment]
Issue is fixed after doing pip install requirements.txt might be selenium n appium were not compatible earlier

**Comment by denji-glitch** [comment]
Can you share me the solution

**Comment by Rexze001** [comment]
@denji-glitch I encountered the same issue, but I have resolved it now. The reason was that the version of the 'appium-python-client' package was not compatible with the version of 'selenium'. This is their version compatibility list:
<img width="841" alt="image" src="https://github.com/appium/python-client/assets/22924327/5f9b39f3-b1da-4f49-af96-ccde346aa2ed">

**Comment by MauricioJacaraci** [comment]
Estou encontrando o mesmo problema, já instalei as versões compativeis do cliente appium e selenium e não tem jeito.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[c:\Users\MAURICIO\Desktop\AUTOMA](file:///C:/Users/MAURICIO/Desktop/AUTOMA)ÇÃO-GESTOR\AUTOMAÇÃO_GPS_APP_GESTOR.ipynb Célula 1 line 1
      [9](vscode-notebook-cell:/c%3A/Users/MAURICIO/Desktop/AUTOMA%C3%87%C3%83O-GESTOR/AUTOMA%C3%87%C3%83O_GPS_APP_GESTOR.ipynb#W0sZmlsZQ%3D%3D?line=8) caps["appium:appPackage"] = "br.com.hbsis.gestor"
     [10](vscode-notebook-cell:/c%3A/Users/MAURICIO/Desktop/AUTOMA%C3%87%C3%83O-GESTOR/AUTOMA%C3%87%C3%83O_GPS_APP_GESTOR.ipynb#W0sZmlsZQ%3D%3D?line=9) caps["appium:appActivity"] = "crc644d5dea12284da3cb.ActivityLogin"
---> [12](vscode-notebook-cell:/c%3A/Users/MAURICIO/Desktop/AUTOMA%C3%87%C3%83O-GESTOR/AUTOMA%C3%87%C3%83O_GPS_APP_GESTOR.ipynb#W0sZmlsZQ%3D%3D?line=11) driver = webdriver.Remote("http://127.0.0.1:4723/wd/hub", caps)

File [c:\Users\MAURICIO\Desktop\AUTOMA](file:///C:/Users/MAURICIO/Desktop/AUTOMA)ÇÃO-GESTOR\venv\Lib\site-packages\appium\webdriver\webdriver.py:229, in WebDriver.__init__(self, command_executor, keep_alive, direct_connection, extensions, strict_ssl, options)
    226 if isinstance(command_executor, str):
    227     command_executor = AppiumConnection(command_executor, keep_alive=keep_alive)
--> 229 super().__init__(
    230     command_executor=command_executor,
    231     options=options,
    232 )
    234 if hasattr(self, 'command_executor'):
    235     self._add_commands()

File [c:\Users\MAURICIO\Desktop\AUTOMA](file:///C:/Users/MAURICIO/Desktop/AUTOMA)ÇÃO-GESTOR\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py:185, in WebDriver.__init__(self, command_executor, keep_alive, file_detector, options)
    183     _ignore_local_proxy = False
    184 else:
--> 185     capabilities = options.to_capabilities()
    186     _ignore_local_proxy = options._ignore_local_proxy
    187 self.command_executor = command_executor

**AttributeError: 'NoneType' object has no attribute 'to_capabilities'**

**Comment by KazuCocoa** [comment]
Please use Options for `caps` -> https://github.com/appium/python-client?tab=readme-ov-file#quick-migration-guide-from-v2-to-v3 https://github.com/appium/python-client?tab=readme-ov-file#usage
We set deprecation warning messages in past client versions to use Options as well, so if you used appium python lib v2.3.0 or later, the deprecation log might be there.

for the inspector, it looks like we need to update

**Comment by rahulgupta020** [comment]
In My case I update Appium-Python-Client. So I downgrade the python version.
`pip install Appium-Python-Client==2.6.0`

**Comment by MauricioJacaraci** [comment]
Estava usando o java 8 e não tava funcionando, depois que atualizei para o mais recente, tudo funcionou.

**Comment by NaveenKum07** [comment]
This worked for me this is due to the selenium and python bindings.

**Comment by dron4ik86** [comment]
Try this solution
```
from appium.webdriver.webdriver import AppiumOptions

appium_options = AppiumOptions()
appium_options.load_capabilities(capabilities)
driver = webdriver.Remote(appium_server_url, options=appium_options)
```
