### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'to_capabilities'

### ISSUE THREAD

**Issue by amclaire** [appium/python-client#927]
been facing serious issues  since after updating my appium and python-client to latest version

this python code below works with previous version but after the update i got the error below it 

import time
from appium.webdriver.common.appiumby import AppiumBy
from selenium.common.exceptions import TimeoutException, NoSuchElementException
from appium import webdriver
from appium.webdriver.common.touch_action import TouchAction

# Desired capabilities for your Android device or emulator
desired_caps = {
                'platformName': 'Android',
                'skipServerInstallation': True,
                'automationName': 'UiAutomator2',
                "appPackage": "com.blissfulmeet.com",
                "appActivity": "com.blissfulmeet.com.Activity",
                "uiautomator2ServerInstallTimeout": 30000,  
                'newCommandTimeout': 30000,  
                'adbExecTimeout': 30000,  
                'uiautomator2ServerReadTimeout': 30000,  
                'appium:settings[waitForIdleTimeout]': 30000,  
                'settings[waitForSelectorTimeout]': 30000,  
                'uiautomator2ServerLaunchTimeout': 30000  
}

# Initialize the Appium driver
driver = webdriver.Remote(f'http://127.0.0.1:4723', desired_caps)
time.sleep(60)

The error i get after running the above code is 

C:\Users\Airbone\AppData\Local\Programs\Python\Python311\python.exe C:\Users\Airbone\Desktop\Agada\thescrew.py 
Traceback (most recent call last):
  File "C:\Users\Airbone\Desktop\Agada\thescrew.py", line 24, in <module>
    driver = webdriver.Remote(f'http://127.0.0.1:4723', desired_caps)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Airbone\AppData\Local\Programs\Python\Python311\Lib\site-packages\appium\webdriver\webdriver.py", line 229, in __init__
    super().__init__(
  File "C:\Users\Airbone\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 185, in __init__
    capabilities = options.to_capabilities()
                   ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'to_capabilities'

Process finished with exit code 1

i tried with emulator and real device it wont even connect to any of them, it will just show the error below 
please i need assistance

**Comment by KazuCocoa** [comment]
What version of selenium binding did you use?
https://github.com/appium/python-client?tab=readme-ov-file#compatibility-matrix is the compatibility table

**Comment by amclaire** [comment]
> What version of selenium binding did you use? https://github.com/appium/python-client?tab=readme-ov-file#compatibility-matrix is the compatibility table

i had latest version but i uninstalled to install the version on the link above  
https://prnt.sc/eYzkgQ4Fv36C
it didnt solve the error, 
when i run it i still get the below error 

C:\Users\Airbone\AppData\Local\Programs\Python\Python311\python.exe C:\Users\Airbone\Desktop\Agada\thescrew.py 
Traceback (most recent call last):
  File "C:\Users\Airbone\Desktop\Agada\thescrew.py", line 24, in <module>
    driver = webdriver.Remote(f'http://127.0.0.1:4723', desired_caps)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Airbone\AppData\Local\Programs\Python\Python311\Lib\site-packages\appium\webdriver\webdriver.py", line 229, in __init__
    super().__init__(
  File "C:\Users\Airbone\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 185, in __init__
    capabilities = options.to_capabilities()
                   ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'to_capabilities'

Process finished with exit code 1

**Comment by KazuCocoa** [comment]
Btw, did you follow the options way https://github.com/appium/python-client?tab=readme-ov-file#usage ?

**Comment by amclaire** [comment]
well i did reinstall the previous version i had to get rid of the error
