### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'to_capabilities' Appium-Python-Client==3.1.0

### ISSUE THREAD

**Issue by Anna-Ku** [appium/python-client#928]
## The problem
Unable to initialize Appium driver.
**[AttributeError]: 'dict' object has no attribute 'to_capabilities'**

## Environment
- Appium version - 2.0.0-beta.45
- Last Appium-Python-Client version that did not exhibit the issue - 2.11.1
- Desktop OS/version used to run Appium - Windows pro 10
- Node.js version (unless using Appium.app|exe) - 16.18.0
- Mobile platform/version under test- Android
- Real device or emulator/simulator- real device
- Selenium - 4.14.0

## Details
I got error from remote/webdriver.py module in the following line:             capabilities = options.to_capabilities()

## Additional Details
{'noReset': True,
 'fullReset': False, 
'appPackage': 'com.shs.iot',
 'appActivity': 'com.shs.iot.MainActivity',
 'udid': '***',
 'automationName': 'UiAutomator2',
 'uiautomator2ServerInstallTimeout': '120000', 
'app': 'C:\\workspace\\...', 
'chromedriverExecutable': 'C:\\workspace\\...',
 'unicodeKeyboard': True,
 'resetKeyboard': True, 
'enableWebviewDetailsCollection': True,
 'autoWebview': True, 
'platformName': 'Android'}

self.driver_ = webdriver.Remote(self.__appium_server_ip,
                                                options=self.__desired_capabilities
                                                )

**Comment by KazuCocoa** [comment]
Please try out options class such as https://github.com/appium/python-client?tab=readme-ov-file#usage

**Comment by Anna-Ku** [comment]
@KazuCocoa I forgot to do load capabilities, thanks!!
