### ISSUE TITLE
app_strings missing stringFile parameters

### ISSUE THREAD

**Issue by lnnp1910** [appium/python-client#93]
Since version 1.3.7, appium server could take "stringFile" parameters to extract the content of a custom localized string file. Otherwise, it will point to the default string file (e.g. ios localizable.strings)
https://github.com/appium/appium/issues/3957

But looks like appium python client - app_strings function has not updated with this feature yet. 
Is there a way that we can update this feature soon?
something like: app_strings(language='en', string_file='')

**Comment by Jonahss** [comment]
:+1:

**Comment by imurchie** [comment]
Whoops!
