### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: The requested resource could not be found, or a request was received using an HTTP method that is not supported 

### ISSUE THREAD

**Issue by apatheticL** [appium/python-client#949]
## The problem

I try example for text of appium in this link : https://appium.io/docs/en/2.4/quickstart/test-py/ . but it not work and show error 
self = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x000001EFC51A8EC0>
response = {'status': 404, 'value': '{"status":9,"value":{"error":"unknown command","message":"The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource","stacktrace":""}}'}
Please help me fix it. Thank so much,-.

## Environment
- Appium version (or git revision) that exhibits the issue:2.4.1
- Desktop OS/version used to run Appium: Windown 11
- Node.js version (unless using Appium.app|exe): v16.20.0
- Mobile platform/version under test: Android 13
- Real device or emulator/simulator: real device xiaomi node 11 pro
- Appium CLI or Appium.app|exe:  all, appium CLI and appium application same error 

## Link to Appium Logs
(https://gist.github.com/apatheticL/4f99a3ce0552b3a0e67f1efe14079c2a)

## Code To reproduce issue
this is my code:
import unittest
from appium import webdriver
from appium.webdriver.common.appiumby import AppiumBy
from appium.options.android import UiAutomator2Options

capabilities = dict(
    platformName='Android',
    automationName='uiautomator2',
    deviceName=*'My device name*',
    appPackage='com.android.settings',
    appActivity='.Settings',
    # language='en',
    # locale='US'
)

appium_server_url = 'http://localhost:4723/wd/hub'
APPIUM_PORT = 4723
APPIUM_HOST = '127.0.0.1'

capabilities_options = UiAutomator2Options().load_capabilities(capabilities)

class TestAppium(unittest.TestCase):
    def setUp(self) -> None:
        self.driver = webdriver.Remote(command_executor=appium_server_url, options=capabilities_options)

    def tearDown(self) -> None:
        if self.driver:
            self.driver.quit()

    def test_find_battery(self) -> None:
        el = self.driver.find_element(by=AppiumBy.XPATH, value='//*[@text="Battery"]')
        el.click()

if __name__ == '__main__':
    unittest.main()

**Comment by KazuCocoa** [comment]
What about using `http://localhost:4723`' as https://appium.io/docs/en/2.4/quickstart/test-py/ instead of `http://localhost:4723/wd/hub`?

**Comment by apatheticL** [comment]
I try replace appium_server_url = 'http://localhost:4723/wd/hub'
 to appium_server_url = 'http://localhost:4723' but it not work and it show same error you can see it in this link error https://gist.github.com/apatheticL/d3a477dee2520ac6ea96dc1b3e7ebbe2
Thanks

**Comment by KazuCocoa** [comment]
Could you share the appium server log as well?

**Comment by apatheticL** [comment]
Yes, this is log of appium server when i use
appium_server_url = 'http://localhost:4723/'
link log
 https://gist.github.com/apatheticL/afa892c34e73f2cb86c0e0be1243b27d

**Comment by KazuCocoa** [comment]
> Welcome to Appium v1.9.1

Please use the latest version. I'm not sure how you installed the Appium, but current Appium is v2.x and newer driver version.

https://appium.io/docs/en/2.4/quickstart/install/
https://appium.io/docs/en/2.4/quickstart/uiauto2-driver/

**Comment by apatheticL** [comment]
Thanks. but i remove this appium version 1.9.1 and i run it in appium version v2.4.1 but in appium server not show any error but in  log build in IDE error in this link  https://gist.github.com/apatheticL/476f75fcc7621ffaeb376350339d969c

**Comment by s0unt** [comment]
`appium_server_url = 'http://localhost:4723'` WORKED instead of `http://localhost:4723/wd/hub` or `http://localhost:4723/`

**Comment by VinitaPatil11** [comment]
**http://localhost:4723**  worked for me no need to mention wd/hub
