### ISSUE TITLE
how to use appium:settings[snapshotMaxDepth] in new appium client 3 ?

### ISSUE THREAD

**Issue by DaffaPintu** [appium/python-client#952]

**Comment by KazuCocoa** [comment]
https://github.com/appium/python-client/tree/bdac0b89b51d70ffea12df15adaec86ba4a986a2?tab=readme-ov-file#relax-ssl-validation
```
options.set_capability('browser_name', 'safari')
```
This example would help to set an arbitrary caps. (I guessed this was your question)

**Comment by DaffaPintu** [comment]
ahhh i see, thanks lot sir @KazuCocoa 🫡
