### ISSUE TITLE
UiAutomator2Options has no option to set wait_for_idle_timeout

### ISSUE THREAD

**Issue by nick-imvu** [appium/python-client#954]
## The problem

The `UiAutomator2Options` object has no option to set the `wait_for_idle_timeout`, although this option does exist for `XCUITestOptions`.

With Appium-Python-Client 2.x, I was able to set `waitForIdleTimeout` via the `desired_capabilities` even when using UiAutomator2. This capability is critical for us. Without the ability to reduce this timeout, some of our testing flows run much too slowly.

## Environment
- Appium-Python-Client version: 3.1.1
- Last Appium-Python-Client version that did not exhibit the issue: 2.7.1 (for example)
- Appium Version: 2.2.1
- Desktop OS/version used to run Appium: MacOS Ventura 13.5
- Node.js version (unless using Appium.app|exe): v20.11.0
- Mobile platform/version under test: Android
- Real device or emulator/simulator: both
- Appium CLI or Appium.app|exe: Appium CLI

## Details

Can the `wait_for_idle_timeout` option be added for `UiAutomator2Options`, or is there a recommended alternative?

So far, the workaround I have found is to create the webdriver first and then call `webdriver.update_settings({'waitForIdleTimeout': 100})` to set the desired value. However, I worry this will not be a viable long-term solution.

**Comment by KazuCocoa** [comment]
It is settings api, not capabilities. If you set the capability in uia2 before instead of settings api's usage, perhaps it did not work.
https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#settings-api

**Comment by KazuCocoa** [comment]
As https://appium.io/docs/en/2.4/guides/settings/, you also can set the settings in capabilities as https://appium.io/docs/en/2.4/guides/settings/#initializing-settings-via-capabilities
