### ISSUE TITLE
MultiAction.add() Incorrect Docstring

### ISSUE THREAD

**Issue by Ferny44** [appium/python-client#956]
## The problem
In appium/webdriver/common/multi_action.py:

MultiAction.add method docstring states that it returns self instance. The method's type hint states that it returns none.

````    
    def add(self, *touch_actions: 'TouchAction') -> None:
        """Add TouchAction objects to the MultiAction, to be performed later.

        Args:
            touch_actions: one or more TouchAction objects describing a chain of actions to be performed by one finger

        Usage:
            | a1 = TouchAction(driver)
            | a1.press(el1).move_to(el2).release()
            | a2 = TouchAction(driver)
            | a2.press(el2).move_to(el1).release()
            | MultiAction(driver).add(a1, a2)

        Returns:
            `MultiAction`: Self instance
        """
        for touch_action in touch_actions:
            if self._touch_actions is None:
                self._touch_actions = []

            self._touch_actions.append(copy.copy(touch_action))
````

## Environment
- Appium version (or git revision) that exhibits the issue: 
    - Currently on master branch, 3.3.1
- Last Appium version that did not exhibit the issue (if applicable):
    - docstring was updated in this commit: https://github.com/appium/python-client/commit/8205776240b4c92e021064751e5b113d0c915d50#diff-a825035d2eb075516862e3f675dee371524899335873de35074e9300d63b0d9f
    - type hint was added in this commit: https://github.com/appium/python-client/commit/9c597a3afe76ff1283c45259ed6e1c4aadac530d#diff-a825035d2eb075516862e3f675dee371524899335873de35074e9300d63b0d9f

**Comment by KazuCocoa** [comment]
It would be appreciated to create a PR if you don't mind.
These classes will be removed as the deprecation, btw.

**Comment by KazuCocoa** [comment]
3.2.0 has the update
