### ISSUE TITLE
What is the alternative for MultiAction on v3?

### ISSUE THREAD

**Issue by vadimnakonechny** [appium/python-client#959]
Hi, as TouchAction is deprecated, the MultiAction is deprecated as well.
But what's the alternative? For example i want to zoom/pinch the screen.
I didn't find any solution.
Thanks.

**Comment by mykola-mokhnach** [comment]
Check https://www.youtube.com/watch?v=oAJ7jwMNFVU

**Comment by KazuCocoa** [comment]
https://github.com/appium/python-client?tab=readme-ov-file#multiactiontouchaction-to-w3c-actions
https://github.com/appium/python-client/blob/92583ce39003b740bb5e57bbf2114d283d884d22/appium/webdriver/extensions/action_helpers.py

these also would help to learn w3c actions
