### ISSUE TITLE
Session can't be created

### ISSUE THREAD

**Issue by Taitalus** [appium/python-client#96]
the package name is  com.automationsolutionz.sunshine.app
the main activity name is com.automationsolutionz.sunshine.app.MainActivity

    def setup(**kwargs):
        desired_caps={}
        for each in kwargs:
            desired_caps[each]=kwargs[each]
        android_driver=webdriver.Remote(hub_path,desired_caps)
        return android_driver
    def main():
        setup(platformName = 'Android',platformVersion = '4.2',deviceName ='F4AZCY05A885',appPackage='com.automationsolutionz.sunshine.app',appActivity='MainActivity')

But calling this giving me an error:
selenium.common.exceptions.WebDriverException: Message: A new session could not be created. (Original error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity)

but when I run from the adb shell:

    adb -s F4AZCY05A885 shell am start -W -a android.intent.action.MAIN -n com.automationsolutionz.sunshine.app/.MainActivity
then it runs successfully.
Any help??

**Comment by sazid** [comment]
Can this be of any help? https://github.com/appium/appium/issues/338

**Comment by imurchie** [comment]
Can you provide the server logs? In there we ought to be able to see the commands being used to launch the app, and what is going on in more detail.

**Comment by imurchie** [comment]
Closing.
