### ISSUE TITLE
Facing Touch_Actions issue after V4.0.0 changes

### ISSUE THREAD

**Issue by sookinchun** [appium/python-client#974]
## The problem

Facing Issue on ModuleNotFoundError: No module named 'appium.webdriver.common.touch_action'. According to the changelog I saw there is suggestion to use w3c actions, sry I just started to join the community and does not know much the ecosystem. Is there and instruction of guide to use it instead of WebDriver? Or it is managed by the contributors community, just wait for the updates?

## Environment

Name: Appium-Python-Client
Version: 4.0.0
Summary: Python client for Appium
Home-page: http://appium.io/
Author: Isaac Murchie
Author-email: isaac@saucelabs.com
License: Apache 2.0
Location: C:\Users\JJ\AppData\Local\Programs\Python\Python312\Lib\site-packages
Requires: selenium
Required-by: robotframework-appiumlibrary

Windows 11

Nodejs v18.15.0

Python 3.12.2

## Details

Currently I am planning to have mobile testing using robot-framework with AppiumLibrary. But face import issue as it mentions can't found the Library even thought has been well configured and reinstall environment carefully. After some investigation, I found it is showing ModuleNotFoundError: No module named 'appium.webdriver.common.touch_action'. 

Since the installation process is fully pip managed and does not involve much manual input, I found it seems to be cause by the changes.

![image](https://github.com/appium/python-client/assets/67315915/ec379f93-8f02-4b9a-a136-68a35e1d23c6)

## Link to Appium Logs

https://gist.github.com/sookinchun/036e7d60cd9110c8be45d963af553e0b

## Code To reproduce issue

**Robot Framework**

```
*** Settings ***
Library AppiumLibrary
```

**Command Prompt**
-python
-import AppiumLibrary

**Comment by eglitise** [comment]
[This is a known issue with robotframework-appiumlibrary](https://github.com/serhatbolsu/robotframework-appiumlibrary/issues/417). For now you can use the temporary workaround mentioned there.

**Comment by cavs63** [comment]
as usual stupid people are changing the code then programs that were working are now not working!

**Comment by mykola-mokhnach** [comment]
@cavs63 consider refraining from adding comments if they are not constructive, and/or are not helpful to other readers. People that are deliberately abusing our code of conduct will be banned from this project.
