### ISSUE TITLE
'PATH' not defined

### ISSUE THREAD

**Issue by thlengane** [appium/python-client#98]
Hi,

I am very much new in this. I apologise in advance if my question is lame.

I am trying to execute "desired_caps['app'] = PATH('Documents/fnbconnect-bernice-112-B43.tar.gz')" in python but I am getting 'PATH' not defined. What am I missing here? Please help..

\>>> import unittest
\>>> from appium import webdriver
\>>> desired_caps = {}
\>>> desired_caps['platformName'] = 'iOS'
\>>> desired_caps['platformVersion'] = '8.3'
\>>> desired_caps['deviceName'] = 'iPhone Simulator'
\>>> desired_caps['app'] = PATH('Documents/fnbconnect-bernice-112-B43.tar.gz')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'PATH' is not defined
\>>>

**Comment by imurchie** [comment]
Sorry, yes, `PATH` is a helper method.

```python
# Returns abs path relative to this file and not cwd
PATH = lambda p: os.path.abspath(
    os.path.join(os.path.dirname(__file__), p)
)
```
