### ISSUE TITLE
How TouchAction to W3C actions implement partial refresh

### ISSUE THREAD

**Issue by jepson66** [appium/python-client#988]
How to implement partial refresh using TouchAction to W3C actions? For example, I want to refresh to see if the text of a button changes.

**Comment by KazuCocoa** [comment]
I'm not sure what "refresh" means in this context, but links around https://github.com/appium/python-client?tab=readme-ov-file#quick-migration-guide-from-v3-to-v4 will help to check W3C actions.

**Comment by KazuCocoa** [comment]
https://discuss.appium.io/ would also help to ask general questions like how to do XXX.

**Comment by jepson66** [comment]
@KazuCocoa  Thank you for your answer.
1. My scenario is like this. I have a button. When the countdown is completed, the button text will change. I want to re-obtain the changed text information of the button, so I need to refresh it.
<img width="454" alt="image" src="https://github.com/appium/python-client/assets/108441697/94558342-c769-4bcd-ba65-3b76679f27c1">
                        ||
<img width="440" alt="image" src="https://github.com/appium/python-client/assets/108441697/efbbdfba-b4be-46f4-84f7-ce2daca11f2c">
2. If the element object captured before the countdown ends, after a period of time, even if the page does not change or the page is not switched, is the element object captured previously unusable? Unusable means that it cannot pass "outdated" "object to perform click and other operations. I have tried it. If I call it after a while, an error will be reported directly. I wonder if you have encountered it.

**Comment by KazuCocoa** [comment]
if the element state changes, usually you may need to get the element again. Or you could keep getting the text value. it would depend on the implementation though.
